### ISSUE TITLE
WinDirStat can't be installed

### ISSUE THREAD

**Issue by medoni** [lukesampson/scoop-extras#1002]
```
λ scoop install WinDirStat
Installing 'WinDirStat' (1.1.2) [64bit]
wds_current_setup.exe (630.6 KB) [==] 100%
Checking hash of wds_current_setup.exe... ok.
Extracting... done.
Linking ~\scoop\apps\WinDirStat\current => ~\scoop\apps\WinDirStat\1.1.2
Creating shim for 'windirstat'.
Can't shim 'windirstat.exe': File doesn't exist.
```

**Comment by r15ch13** [comment]
Works for me. Also, there shouldn't be problems with antiviruses tools.

https://www.virustotal.com/#/file/cc3ee246f2710dc9ba9e2a88e3192b88f1db4caa2eefb8641642a33df04e585c/detection
https://www.virustotal.com/#/file/6fa92dd2ca691c11dfbfc0a239e34369897a7fab/detection

**Comment by brandon93s** [comment]
Confirmed - works for me as well.

![image](https://user-images.githubusercontent.com/4730164/42254741-2b9dbd18-7f16-11e8-84e9-5875df2afe87.png)

**Comment by medoni** [comment]
Now works for me too. Dont know why.

**Comment by Lockszmith** [comment]
Had a similar issue crop up today, eventually resolved by installing aria2 which replaced the download method.
posting this in case someone else experiences a similar issue and needs idea for resolution.
