### ISSUE TITLE
apache ivy

### ISSUE THREAD

**Issue by smithtrenton** [lukesampson/scoop-extras#101]
Apache Ivy would be nice to add.
http://ant.apache.org/ivy/download.cgi

**Comment by lukesampson** [comment]
Sounds good—do you want to give it a shot and submit a PR? The JSON file format for manifests is described on the Scoop wiki [here](https://github.com/lukesampson/scoop/wiki/App-Manifests) if you haven't seen it.

**Comment by matthewjberger** [comment]
I know this is a few years late, but I submitted a [pull request](https://github.com/lukesampson/scoop-extras/pull/503) adding a manifest that can install and uninstall apache-ivy
