### ISSUE TITLE
Inkscape doesn't run in cmd

### ISSUE THREAD

**Issue by matthias-t** [lukesampson/scoop-extras#1013]
After installing inkscape with `scoop install inkscape`, `inkscape --version` works in PowerShell, but not in cmd. At first I thought it was a problem with my PATH, but running `get-command inkscape` returned
```
CommandType     Name                          Version    Source
-----------     ----                          -------    ------
ExternalScript  inkscape.ps1                             C:\Users\matth\scoop\shims\inkscape.ps1
```
Is this intended? I don't personnally use cmd, but I need the inkscape cli for svg support in LaTeX.

**Comment by rasa** [comment]
@r15ch13 Does scoop support shims to .com files? inkscape is the only package that shims a .com. See https://inkscape.org/en/learn/faq/#how-use-inkscape-command-line : 

> However, if you type 'inkscape' from a command prompt, and if the install directory (C:\Program Files (x86)\Inkscape\) is in your path, then inkscape.com will be executed. This is actually a windows executable, that calls inkscape.exe and attaches it to the console window, thus displaying stdout and stderr to the console.
> 
> If you type "inkscape.exe" from a command prompt, things like exporting or converting to plain SVG will work, but will not output error messages or warnings to the console.

**Comment by r15ch13** [comment]
@rasa nope, see https://github.com/lukesampson/scoop/blob/master/lib/core.ps1#L276
