### ISSUE TITLE
libreoffice-fresh@6.0.5.2: hash check failed

### ISSUE THREAD

**Issue by ArminVieweg** [lukesampson/scoop-extras#1018]
Checking hash of LibreOffice_6.0.5.2_Win_x64.msi... ERROR Hash check failed!
App:       extras/libreoffice-fresh
URL:       https://downloadarchive.documentfoundation.org/libreoffice/old/6.0.5.2/win/x86_64/LibreOffice_6.0.5.2_Win_x64.msi
Expected:  52e2ae72baa2e4251e9de71fcd1b1d8c360729f71a7172fae96dcf9d304cf5b5
Actual:    b201aeb8ada245300144805f737d45a0e0c54b2b0b4fbb8e2b8f61d9b73a3f5b

**Comment by brandon93s** [comment]
@Ardelean-Calin 

Libre installs successfully for me with the expected hash of `52e2ae72baa2e4251e9de71fcd1b1d8c360729f71a7172fae96dcf9d304cf5b5`. Do you mind trying again - they may have fixed the bin. If you're still having trouble report back and we can help troubleshoot.
