### ISSUE TITLE
resource-hacker@4.5.30: hash check failed

### ISSUE THREAD

**Issue by anwarjaved** [lukesampson/scoop-extras#1109]
ERROR Hash check failed!
App:         extras/resource-hacker
URL:         http://www.angusj.com/resourcehacker/resource_hacker.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    2010fd5c5411838647d7fc5a2dedd29cbb600f5076e241bd8a2c3e2f6cba2469
Actual:      de24309105f589d0c4f6d19c85d0354c0c8ffe9a2f34054ab2028b4a380c664d

**Comment by r15ch13** [comment]
Fixed and updated. Please try again.

**Comment by anwarjaved** [comment]
Thanks its fixed
