### ISSUE TITLE
irfanview@4.51: hash check failed

### ISSUE THREAD

**Issue by LexSong** [lukesampson/scoop-extras#1125]
App:         extras/irfanview
URL:         https://www.fosshub.com/IrfanView.html/iview451_plugins_x64.zip
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    c938d7ae4dcbb2b531f416cffb772bd91b3c8eba84d7a787d936f962aa80e00e
Actual:      3b3c7b0e991c092e8cb8d98f81fc31549523c78f813ee03b57131159472e1640

**Comment by rasa** [comment]
The hash listed at https://www.fosshub.com/IrfanView.html is c938d7ae4dcbb2b531f416cffb772bd91b3c8eba84d7a787d936f962aa80e00e
