### ISSUE TITLE
firefox-beta/firefox-developer/firefox-nightly: fix version

### ISSUE THREAD

**Issue by Retia-Adolf** [lukesampson/scoop-extras#1140]
firefox-beta/firefox-developer major.minor version number available here: 
https://www.mozilla.org/en-US/firefox/beta/notes/

firefox-nightly major.minor version number available here: 
https://www.mozilla.org/en-US/firefox/nightly/notes/

Only their patch version number is not updated on Mozilla's page.

**Comment by r15ch13** [comment]
There is no complete version number to find.
The beta is currently at `62.0b17`.

**Comment by rasa** [comment]
Is this still an issue?

**Comment by rikuben** [comment]
You can get the complete version number of beta version [here](https://archive.mozilla.org/pub/firefox/releases/), (66.0b8 right now).
Dev version number is the same with beta.
Nightly version number is either the timestamp [here](https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/), or in `https://archive.mozilla.org/pub/firefox/nightly/{year}/{month}/`.

**Comment by raulfpl** [comment]
#2124 should fix this for firefox-nightly.

We still need to figure out a way to extract latest version numbers from firefox-beta and firefox-developer.
