### ISSUE TITLE
ccleaner@5.44.6575: hash check failed

### ISSUE THREAD

**Issue by ambhaiji** [lukesampson/scoop-extras#1143]
Installing 'ccleaner' (5.44.6575) [64bit]

downloadfile (48 B) [=========================================================================================] 100%
Checking hash of downloadfile ... ERROR Hash check failed!
App:         extras/ccleaner
URL:         https://www.piriform.com/ccleaner/download/portable/downloadfile#/dl.7z
First bytes: 3C 4D 45 54 41 20 48 54
Expected:    1aaa0621ee295147d82f168b4cdc0151dd1507d4624aa2ac5aa28eb1a6c5d93a
Actual:      fb249f429180a78992375a0f736343a8cd1f6bffe5e940411f6cca448e019471

**Comment by r15ch13** [comment]
`1aaa0621ee295147d82f168b4cdc0151dd1507d4624aa2ac5aa28eb1a6c5d93a` is still correct, please try again.

**Comment by ambhaiji** [comment]
this is still broken for me it downloads a 48 byte file
with and without aria2

**Comment by ambhaiji** [comment]
ok a dns flush fixed it.
