### ISSUE TITLE
storageexplorer@1.3.0: hash check failed

### ISSUE THREAD

**Issue by leomwa** [lukesampson/scoop-extras#1158]
Download: (OK):download completed.
Checking hash of StorageExplorer.exe ... ERROR Hash check failed!
App:         extras/storageexplorer
URL:         https://download.microsoft.com/download/A/E/3/AE32C485-B62B-4437-92F7-8B6B2C48CB40/StorageExplorer.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    a2df60769671805e13e776cf1ab7395f2b8b902f6fffec60a4a026a98b9d310b
Actual:      d2e470a973a445e13bf4a55976890d1cba3ba5b2dd6ecd8439767aff1e8544fa

**Comment by rasa** [comment]
Fixed in https://github.com/lukesampson/scoop-extras/commit/4c29c4c099bd1ea37fa6f96accca96fca7803ada
