### ISSUE TITLE
Unable to download VSCode nightlies

### ISSUE THREAD

**Issue by mikecarr** [lukesampson/scoop-extras#1224]
It seems vscode-insiders is hardcoded to a set version, is this deliberate? This makes downloading nightlies not possible.

"https://vscode-update.azurewebsites.net/1.26.0-insider/win32-x64-archive/insider#/dl.7z

**Comment by r15ch13** [comment]
That's a "feature" 😁

Fixed it :smile:

**Comment by r15ch13** [comment]
Yes, fixed it in cff8eba
