### ISSUE TITLE
[Request] Steam

### ISSUE THREAD

**Issue by vaguiners** [lukesampson/scoop-extras#1226]
https://store.steampowered.com/about/

**Comment by Ash258** [comment]
I have it in my [bucket](https://github.com/Ash258/scoop-Ash258). 
If anyone want to create PR to extras here is [manifest](https://github.com/Ash258/scoop-Ash258/blob/master/Steam.json): 

It's pure nightly build, because steam does not have any archive of installers. And installers are changing rapidly (sometimes few a day). After scoop isntallation, all required files will be installed via steam update.

```json
{
    "version": "nightly",
    "description": "Steam. The ultimate entertainment platform.",
    "homepage": "https://store.steampowered.com/",
    "notes": "Changing Steam library folder is HIGHLY recommended.",
    "suggest": {
        "Skins": [
            "AirSkin"
        ]
    },
    "url": "https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe#/cosi.7z",
    "installer": {
        "script": [
            "Remove-Item \"$dir\\`$PLUGINSDIR\" -Force -Recurse",
            "foreach ($fold in @(\"skins\", \"steamapps\", \"userdata\")) {",
            "    if (!(Test-Path \"$persist_dir\\$fold\")) {",
            "        Write-Host 'Folder' $fold 'does not exists. Creating.' -f Yellow",
            "        New-Item \"$dir\\$fold\" -Type Directory | Out-Null",
            "    }",
            "}"
        ]
    },
    "uninstaller": {
        "file": "uninstall.exe",
        "args": [
            "/S"
        ]
    },
    "persist": [
        "skins",
        "steamapps",
        "userdata"
    ],
    "shortcuts": [
        [
            "Steam.exe",
            "Steam",
            "-dev"
        ]
    ]
}
```

**Comment by vaguiners** [comment]
@Ash258 
For some reason this is not working
Im having not found error on steam.exe

**Comment by Ash258** [comment]
No. 

![No](https://i.imgur.com/QBTvkQe.png)

**Comment by vaguiners** [comment]
Same here. It installs successfully but when i try to run steam, steam.exe, Steam or Steam.exe from anywhere, cmd, ps, run, it says steam not found
i can found the steam directory on scoop but is not installing right

**Comment by vaguiners** [comment]
Maybe the problem is the 

            "Steam.exe",
            "Steam",

**Comment by Ash258** [comment]
Because there is no bin property inside manifest.

**Comment by vaguiners** [comment]
and why no, nude?

**Comment by Ash258** [comment]
Because i dont like it. Waste of shims. There is no reason to run GUI applications like Steam, ... to run them from CMD. Never happen in eny use case. Bins are good for some pipelines, or when the app has command line interface even with gui. (like 7zip)

**Comment by vaguiners** [comment]
You have the point

**Comment by superusercode** [comment]
@Ash258 Why is changing the library folder recommended? I've had a tough time dealing with disk write errors on steam trying to change it and the default seems to work just fine.

**Comment by opariffazman** [comment]
@superusercode I'm having the write errors issue as well when trying to edit the libraryfolders.vdf using the same disk

**Comment by jacobblock** [comment]
+1 on the steam library folder notice; it looks like steam _requires_ this to not be changed on the same drive. Only if you're using a separate partition can you add a different library folder unless I'm missing something.

**Comment by danielb2** [comment]
how can I install steam via scoop?

**Comment by rashil2000** [comment]
scoop bucket add versions
scoop install steam

**Comment by danielb2** [comment]
> scoop bucket add versions scoop install steam

that's awesome man. thank you. I don't know why this is hard to find. I also noticed that even on scoop.sh the example is vscode which will fail to install because there's no mention of the extras bucket there. it's a bad example

**Comment by rashil2000** [comment]
That's a good point, the example should probably be replaced by something in the Main bucket

**Comment by danielb2** [comment]
@vaguiners   or the example could mention the extras bucket. Would be nice if the front-page also mentioned versions. I think it's common use-case where people would want to know right up front

**Comment by rashil2000** [comment]
Could you please post your feedback here https://github.com/ScoopInstaller/scoopinstaller.github.io/issues
