### ISSUE TITLE
speccy@1.32.740: hash check failed

### ISSUE THREAD

**Issue by duzyn** [lukesampson/scoop-extras#1256]
Checking hash of downloadfile ... ERROR Hash check failed!
App:         extras/speccy
URL:         https://www.piriform.com/speccy/download/portable/downloadfile#/dl.7z
First bytes: 3C 4D 45 54 41 20 48 54
Expected:    1a662d847f16850658216634eda7c98ce06b0c861017de16e8dc8ff12a412abe
Actual:      fb249f429180a78992375a0f736343a8cd1f6bffe5e940411f6cca448e019471

**Comment by r15ch13** [comment]
It seems they have removed the portable version. This happened to ccleaner as well https://github.com/lukesampson/scoop-extras/issues/1218

Just checked the ccleaner portable URL and it works again. Strange 😕

**Comment by Ash258** [comment]
As i said in: https://github.com/lukesampson/scoop-extras/issues/1148#issuecomment-414075540 
It could be based on normal version.
