### ISSUE TITLE
azure-cli@2.0.46: hash check failed

### ISSUE THREAD

**Issue by leomwa** [lukesampson/scoop-extras#1262]
Download: (OK):download completed.
Checking hash of azure-cli-2.0.46.msi ... ERROR Hash check failed!
App:         extras/azure-cli
URL:         https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.0.46.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    90f5e38e4686eb49890803ef8a2aa136979c1da0ef2fe9551df8b76e8cb71e46
Actual:      5f69dc1fa9c99f908e95cb548c843a27c8ebc9c1e0e99a101876064c18b86248

**Comment by r15ch13** [comment]
Using the official CDN makes sense. 👍
Changed it with https://github.com/lukesampson/scoop-extras/commit/7b5da40c5ba2c6bfd8c2a833e950199f1ef55223
