### ISSUE TITLE
mpv-git@20180916: download via aria2 failed

### ISSUE THREAD

**Issue by vaguiners** [lukesampson/scoop-extras#1266]
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
DEBUG https://downloads.sourceforge.net/project/mpv-player-windows/64bit/mpv-x86_64-20180916-git-6eb59fe.7z
    dir=C:\Users\Vaguiner\scoop\cache
    out=mpv-git#20180916#https_sourceforge.net_projects_mpv-player-windows_files_64bit_mpv-x86_64-20180916-git-6eb59fe.7z

DEBUG & 'C:\Users\Vaguiner\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Vaguiner\scoop\cache\mpv-git.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=4184 --continue

**Comment by Ash258** [comment]
It's problem on your end (based on all your related issues.)
Try something like: `scoop uninstall aria2; scoop cache rm aria2; scoop cache rm mpv-git; scoop intall aria2; scoop install mpv-git`
```
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'mpv-git' (20180916) [64bit]
Starting download with aria2 ...
Download: [#1e32f0 0B/0B CN:1 DL:0B]
Download: [#1e32f0 288KiB/16MiB(1%) CN:2 DL:802KiB ETA:20s]
Download: [#1e32f0 2.7MiB/16MiB(16%) CN:2 DL:2.0MiB ETA:6s]
Download: [#1e32f0 3.9MiB/16MiB(24%) CN:2 DL:1.6MiB ETA:7s]
Download: [#1e32f0 4.8MiB/16MiB(29%) CN:2 DL:1.4MiB ETA:7s]
Download: [#1e32f0 5.5MiB/16MiB(33%) CN:2 DL:1.2MiB ETA:8s]
Download: [#1e32f0 6.4MiB/16MiB(39%) CN:2 DL:1.2MiB ETA:8s]
Download: [#1e32f0 7.4MiB/16MiB(45%) CN:2 DL:1.1MiB ETA:7s]
Download: [#1e32f0 8.0MiB/16MiB(49%) CN:2 DL:1.0MiB ETA:7s]
Download: [#1e32f0 8.6MiB/16MiB(52%) CN:2 DL:1.0MiB ETA:7s]
Download: [#1e32f0 9.4MiB/16MiB(57%) CN:2 DL:1.0MiB ETA:6s]
Download: [#1e32f0 10MiB/16MiB(63%) CN:2 DL:0.9MiB ETA:6s]
Download: [#1e32f0 11MiB/16MiB(69%) CN:2 DL:857KiB ETA:6s]
Download: [#1e32f0 12MiB/16MiB(75%) CN:2 DL:859KiB ETA:4s]
Download: [#1e32f0 13MiB/16MiB(81%) CN:2 DL:881KiB ETA:3s]
Download: [#1e32f0 14MiB/16MiB(87%) CN:2 DL:908KiB ETA:2s]
Download: [#1e32f0 14MiB/16MiB(90%) CN:1 DL:849KiB ETA:1s]
Download: [#1e32f0 15MiB/16MiB(93%) CN:1 DL:822KiB ETA:1s]
Download: [#1e32f0 16MiB/16MiB(98%) CN:1 DL:842KiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 1e32f0|OK  |   0.9MiB/s|D:/SCOOP/cache/mpv-git#20180916#https_sourceforge.net_projects_mpv-player-windows_files_64bit_mpv-x86_64-20180916-git-6eb59fe.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of mpv-x86_64-20180916-git-6eb59fe.7z ... ok.
Extracting mpv-x86_64-20180916-git-6eb59fe.7z ... done.
Linking D:\SCOOP\apps\mpv-git\current => D:\SCOOP\apps\mpv-git\20180916
Creating shim for 'mpv'.
Creating shortcut for mpv (mpv.exe)
Persisting portable_config
Running post-install script...
'mpv-git' (20180916) was installed successfully!
```
