### ISSUE TITLE
[Request] Peerblock json file lists an old version

### ISSUE THREAD

**Issue by Atavic** [lukesampson/scoop-extras#1268]
Peerblock 1.2.0.693 is the latest one.

**Comment by Atavic** [comment]
- https://filehippo.com/download_peerblock/
- http://www.snapfiles.com/apphistory/PeerGuardian_history.html

**Comment by r15ch13** [comment]
These don't seem to be official. 🤔

**Comment by Atavic** [comment]
I used it for years and never broke. From its about info:

> PeerBlock is based upon the earlier PeerGuardian 2 work.  Many thanks to Cory Nelson and his Phoenix Labs crew (http://www.phoenixlabs.org) for creating  PG2, and for making it open-source so that after they abandoned it we could pick it up and resurrect it!
