### ISSUE TITLE
android-studio@3.2.0.26: download via aria2 failed

### ISSUE THREAD

**Issue by linuxbelletian** [lukesampson/scoop-extras#1272]
Download: (80092013)
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 075410|ERR |       0B/s|C:/Users/aber/scoop/cache/android-studio#3.2.0.26#https_dl.google.com_dl_android_studio_ide-zips_3.2.0.26_android-studio-ide-181.5014246-windows.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
DEBUG https://dl.google.com/dl/android/studio/ide-zips/3.2.0.26/android-studio-ide-181.5014246-windows.zip
    referer=https://dl.google.com/dl/android/studio/ide-zips/3.2.0.26/
    dir=C:\Users\aber\scoop\cache
    out=android-studio#3.2.0.26#https_dl.google.com_dl_android_studio_ide-zips_3.2.0.26_android-studio-ide-181.5014246-windows.zip

DEBUG & 'C:\Users\aber\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\aber\scoop\cache\android-studio.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=220 --continue

**Comment by vaguiners** [comment]
Just remove aria2c or disable, this thing is buggy
Close

**Comment by r15ch13** [comment]
@vaguiners did you try run the aria2c command without scoop and get some information about this error?
