### ISSUE TITLE
[Request] WinAppDriver

### ISSUE THREAD

**Issue by devhawk** [lukesampson/scoop-extras#1286]
https://github.com/Microsoft/WinAppDriver

**Comment by Nefariis** [comment]
I was curious to try an .msi manifest - can you let me know if this works for you? 

https://github.com/lukesampson/scoop-extras/pull/1287

I dont have appium or the ui recorder installed so I havent been able to test it.

**Comment by Nefariis** [comment]
@devhawk - This was just merged on the main scoop branch here: https://github.com/lukesampson/scoop/pull/2636
