### ISSUE TITLE
jdownloader@2: hash check failed

### ISSUE THREAD

**Issue by uncaose** [lukesampson/scoop-extras#1288]
C:\Users\uncao>scoop install jdownloader
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'jdownloader' (2) [64bit]
Loading favicon.ico from cache.
Starting download with aria2 ...
Download: [#172465 96KiB/3.2MiB(2%) CN:1 DL:145KiB ETA:22s]
Download: [#172465 704KiB/3.2MiB(21%) CN:1 DL:382KiB ETA:6s]
Download: [#172465 1.6MiB/3.2MiB(50%) CN:1 DL:597KiB ETA:2s]
Download: [#172465 2.7MiB/3.2MiB(85%) CN:1 DL:714KiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 172465|OK  |   771KiB/s|C:/Users/uncao/scoop/cache/jdownloader#2#http_installer.jdownloader.org_JDownloader.jar
Download: Status Legend:
Download: (OK):download completed.
Checking hash of JDownloader.jar ... ERROR Hash check failed!
App:         extras/jdownloader
URL:         http://installer.jdownloader.org/JDownloader.jar
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    67a45b807f575ee7181ad7a02d245be20f9dd121fca4b9bdc910447f7b8bef6d
Actual:      2d670d8a3d9c177e0ba7845e62a4a7d0b747e780011add9b235b517840599d45

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=jdownloader%402%3a+hash+check+failed

**Comment by Ash258** [comment]
Maybe make it nightly. Since there is no exact version, and app is updating itself on startup?
