### ISSUE TITLE
sysinternals@July.5.2018: hash check failed

### ISSUE THREAD

**Issue by jmsdo** [lukesampson/scoop-extras#1292]
I get the following error message when trying to install the Sysinternals suite on my pc (Windows 7 Enterprise SP 1, behind a corporate firewall). A previous installation of the standalone Process Explorer and an update of Pandoc a few minutes after the failed Sysinternals installation worked without problems.

```
C:\>scoop install sysinternals
Installing 'sysinternals' (July.5.2018) [64bit]
SysinternalsSuite.zip (1,5 KB) [======================================] 100%
Checking hash of SysinternalsSuite.zip ... ERROR Hash check failed!
App:         extras/sysinternals
URL:         https://download.sysinternals.com/files/SysinternalsSuite.zip
First bytes: 3C 68 74 6D 6C 3E 0D 0A
Expected:    533e40025ee69a1b4b436dc6c996c7b34c2b16cec1b45cea0199f19092e77810
Actual:      5acb31a078f90f006bfc8d5117a407e8fccad08851920b8540875d944302438b

Please try again or create a new issue by using the following link and paste you
r console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=sysinternals%40July
.5.2018%3a+hash+check+failed

**Comment by r15ch13** [comment]
Does the download work in a Browser? The first bytes indicate that it's a website (maybe a block page from the firewall)

**Comment by jmsdo** [comment]
Actually it doesn't work. I could have guessed it for myself. Our firewall claims "PUS:App/PsExec-Gen" is being found. Not sure if that really is the case or if it is a false positive.

Then I guess there is no workaround. I'll have to try to download at least Process Explorer from a 3rd party site that virus tests its packages.

**Comment by r15ch13** [comment]
According to [VirusTotal](https://www.virustotal.com/#/url/709d6d3d33101cf7cd42e0db84619ffd4c4bc799c8848611de1e5662b1f5bfe7/detection) it's safe.

**Comment by jmsdo** [comment]
Yes it is safe in the sense that it's not malware. But it can be a security loophole if present on a Windows machine as far as I understood.

But it's no problem. I can get Process Explorer from the download site and use it "standalone" (without scoop) on my PC. I only need this application from the whole suite. I can understand the decision to rather incorporate the whole suite and not wanting to maintain 15 or 20 JSON files. My case is a corner case so I close this issue.

**Comment by jmsdo** [comment]
And thanks!
