### ISSUE TITLE
Fosshub downloads

### ISSUE THREAD

**Issue by superudo** [lukesampson/scoop-extras#1304]
Scoop is trying to get 

`https://www.fosshub.com/IrfanView.html/iview451_plugins.zip` or
`https://www.fosshub.com/IrfanView.html/iview451_plugins_x64.zip`

the links at fosshub points to

`https://www.fosshub.com/IrfanView.html?dwl=iview451_plugins.zip` or 
`https://www.fosshub.com/IrfanView.html?dwl=iview451_plugins_x64.zip`

Error message while trying to install irfanview via scoop:

```
~ $ scoop install irfanview -a 32bit
Installing 'irfanview' (4.51) [32bit]
Loading iview451.zip from cache
Checking hash of iview451.zip ... ok.
Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
URL https://www.fosshub.com/IrfanView.html/iview451_plugins.zip is not valid
```

**Comment by se35710** [comment]
Same with [`kitty.json`](https://github.com/lukesampson/scoop-extras/blob/master/kitty.json) here in extras. Originial cause should be in commits [14a4612](https://github.com/lukesampson/scoop/commit/14a461296bebf18ee137046f43bf8a883cb39b4f) and [803525a](https://github.com/lukesampson/scoop/commit/803525a8661ffaa39fc4ad6f0dc776cccad4c45e).

**Comment by Fleshgrinder** [comment]
Bump: just ran into this issue as well.

**Comment by superudo** [comment]
Hm, the real problem here: Irfanview plugins does not support direkt download anymore, so scoop might not be able to download the ZIP files. I did not find another place to get the plugin ZIPs as a direct download.

**Comment by rasa** [comment]
Fixed in #1449

**Comment by brandon93s** [comment]
@rasa - `kitty` is still through Fosshub and will continue to fail.

**Comment by rasa** [comment]
Good point. Duh.
