### ISSUE TITLE
Everything settings don't persist

### ISSUE THREAD

**Issue by joserebelo** [lukesampson/scoop-extras#1312]
After opening Everything for the first time, the Everything.db and Everything.ini hardlinks get broken, turning into normal files. I am not sure why this is happening, but I'm guessing Everything deletes and recreates them.

If it turns out to be Everything's fault, one option might be saving the settings to APPDATA, using [the -app-data switch](https://www.voidtools.com/support/everything/command_line_options/#-app-data), or even using the [installer](https://www.voidtools.com/forum/viewtopic.php?f=5&t=5673&p=15546), as it was done with Ditto

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
