### ISSUE TITLE
Request: OpenSpades

### ISSUE THREAD

**Issue by Guard13007** [lukesampson/scoop-extras#1321]
It's a video game! A shooter with completely destructable terrain.

Homepage: http://openspades.yvt.jp/ <br>
Releases: https://github.com/yvt/openspades/releases

**Comment by r15ch13** [comment]
@Calinou maintains a great bucket for open source games: https://github.com/Calinou/scoop-games
Adding it there might be better 😄

**Comment by Calinou** [comment]
I just added OpenSpades to scoop-games :smiley: https://github.com/Calinou/scoop-games/commit/0e0c771b0f4b688d6e1461b93eae625f703bba4b

**Comment by matthewjberger** [comment]
Would it be okay to add Calinou's bucket to the official bucket list? I made a pr for this at https://github.com/lukesampson/scoop/pull/2673

**Comment by r15ch13** [comment]
Done 😄

**Comment by Guard13007** [comment]
Sweet! I knew there was a repo with games I just couldn't remember where it
was. o.o

On Oct 15, 2018 1:14 PM, "Richard Kuhnt" <notifications@github.com> wrote:

Done 😄

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lukesampson/scoop-extras/issues/1321#issuecomment-429996825>,
or mute the thread
