### ISSUE TITLE
recuva@1.53.1087: hash check failed

### ISSUE THREAD

**Issue by jiem-takase** [lukesampson/scoop-extras#1347]
Installing 'recuva' (1.53.1087) [64bit]

downloadfile (48 B) [====================================] 100%
Checking hash of downloadfile ... ERROR Hash check failed!
App:         extras/recuva
URL:         https://www.piriform.com/recuva/download/portable/downloadfile#/dl.7z
First bytes: 3C 4D 45 54 41 20 48 54
Expected:    997a082fb03fcdf272d58c25aba488a136cf115a1e1b53930339fb5ef95bf91f
Actual:      fb249f429180a78992375a0f736343a8cd1f6bffe5e940411f6cca448e019471

**Comment by r15ch13** [comment]
Please try again. Piriform has made some changes to their URLs.

`997a082fb03fcdf272d58c25aba488a136cf115a1e1b53930339fb5ef95bf91f` is still correct.
