### ISSUE TITLE
Calibre doesn't work

### ISSUE THREAD

**Issue by lpintes** [lukesampson/scoop-extras#1349]
Nothing happened after running calibre-portable.exe.

I then dived into the directory structure, ran another exe and the following error appeared, translated from localized version:

calibre, version 3.33.1
ERROR: unable to create temporary directory: cannot create temporary directory Calibre cannot be run

Traceback (most recent call last):
  File "site-packages\calibre\gui2\__init__.py", line 824, in __init__
  File "site-packages\calibre\ptempfile.py", line 136, in base_dir
  File "tempfile.py", line 339, in mkdtemp
WindowsError: [Error 3] Syst�m nem��e nal�zt uvedenou cestu: u'C:\\Users\\pintes\\AppData\\Local\\Temp\\7-ZipPortableTemp\\calibre_mwqm2y'

**Comment by Ash258** [comment]
Calibre manifest does not have `bin` property, so it cannot be runned via running `calibre-portable` anywhere.

Try running Calibre shortcut from start menu.

**Comment by lpintes** [comment]
Doesn't work either.

**Comment by Ash258** [comment]
I have no problem with both calibre manifests. 

See: https://bugs.launchpad.net/calibre/+bug/1654242 . Test latest suggestion about environment variable

**Comment by lpintes** [comment]
After reviewing the mentioned bug I suppose this is a kind of local problem.
