### ISSUE TITLE
Cannot install paint.net

### ISSUE THREAD

**Issue by KeKsBoTer** [lukesampson/scoop-extras#1358]
When I try to install paint.net via scoop I get this error:
```bash
$ scoop install paint.net
Installing 'paint.net' (4.1.1) [64bit]
Loading paint.net.4.1.1.install.zip from cache
Checking hash of paint.net.4.1.1.install.zip ... ok.
Extracting paint.net.4.1.1.install.zip ... done.
Running pre-install script...
Exit code was 1619.
Failed to extract files from C:\Users\Simon\scoop\apps\paint.net\4.1.1\tmp\PaintDotNet_x86.msi.
Log file:
  ~\scoop\apps\paint.net\4.1.1\tmp\msi.log
```
The log file is empty

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop-extras/commit/e37e91dd1f21c67ed222c98ae607899c7310ed56 ?

**Comment by Ash258** [comment]
I am not sure. Error 1619 is mostly about existing of that msi file. Maybe permissions, Anti Viruses... Lot's of possibilities.

**Comment by KeKsBoTer** [comment]
@r15ch13 no same error :(

**Comment by KeKsBoTer** [comment]
@Ash258 I do not run any Anti Viruses and also tried it with Windows Defender disabled.
Any suggestions how to trace down the issue?

**Comment by Ash258** [comment]
What happen when you run `scoop checkup`?

**Comment by KeKsBoTer** [comment]
@Ash258 
```bash
$ scoop checkup
No problems identified!
```

**Comment by Ash258** [comment]
Have you tried normal flow with `scoop cache rm paint.net; scoop uninstall paint.net; scoop install paint.net -k`.

Try to unpack that msi manually, if it's problem with file itself, or you system.

**Comment by KeKsBoTer** [comment]
It seams like there is something wrong with the installer script. 
The folder where the installer looks for the .msi file is the wrong one.

I changed  the installer script from:
`"extract_msi \"$dir\\tmp\\PaintDotNet_x64.msi\" \"$dir\""`
to
```"extract_msi \"$dir\\tmp\\`$_OUTDIR\\PaintDotNet_x64.msi\" \"$dir\""```
and it worked.

**Comment by Ash258** [comment]
So your problem is with 7zip. Try reinstalling it.
