### ISSUE TITLE
 scoop-extras/gimp.json requires admin to install

### ISSUE THREAD

**Issue by felipecrp** [lukesampson/scoop-extras#1369]
It would be better to use a portable version.

**Comment by rasa** [comment]
I don’t see a .zip version on 
https://download.gimp.org/mirror/pub/gimp/v2.10/windows/?C=M;O=D or anywhere else. Perhaps we can 7z the exe?

Also, we may want to use the above URL for our checkver.

**Comment by Calinou** [comment]
The installer uses Inno Setup and can be extracted using innounp, but the output filenames make it unusable (all 32-bit-only files have a `,1` suffix, whereas 64-bit-only files end with `,2`). Perhaps this is fixable with a post-installation script, but it doesn't sound trivial.

I created an issue to [request a ZIP distribution from upstream](https://gitlab.gnome.org/GNOME/gimp/issues/2861), but they need to be sure someone is willing to maintain it.
