### ISSUE TITLE
vscode-insiders-portable doesn't update

### ISSUE THREAD

**Issue by lpintes** [lukesampson/scoop-extras#1377]
When I run code-insiders, it notifies me about update after a while, but scoop doesn't reflect it.
It incorrectly states that a newest version is already installed.

**Comment by Ash258** [comment]
When there is vscode update. Run `scoop update vscode-insiders-portable -kf`. It's nightly version, which has always same URL, so hash checks would fail often.

**Comment by lpintes** [comment]
Closing because this is not a bug/problem and a workaround exists.
