### ISSUE TITLE
simplewall@2.3.7: hash check failed

### ISSUE THREAD

**Issue by John3** [lukesampson/scoop-extras#1380]
$ scoop install simplewall
Installing 'simplewall' (2.3.7) [64bit]
simplewall-2.3.7-bin.zip (607.4 KB) [==================================================================] 100%
Checking hash of simplewall-2.3.7-bin.zip ... ERROR Hash check failed!
App:         extras/simplewall
URL:         https://github.com/henrypp/simplewall/releases/download/v.2.3.7/simplewall-2.3.7-bin.zip#/dl.7z
First bytes: 50 4B 03 04 14 00 00 00
Expected:    072a064213e8bbe501326d60f89c4e1f2db9243e765cf24257f66f926eb26907
Actual:      9b28dc998bc95dac4114f0c1fa3d81d3693c0a9da3bbd239228153e4e8b71041

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=simplewall%402.3.7%3a+hash+check+failed

**Comment by r15ch13** [comment]
Auto update to version 2.3.8 fixed it: 
https://github.com/lukesampson/scoop-extras/commit/1797496156ca2e40ef830121729a03b9f862eb75
