### ISSUE TITLE
Question about dart-dev.json location

### ISSUE THREAD

**Issue by sestegra** [lukesampson/scoop-extras#139]
I have just pulled dart-dev.json in scoop repository.
I found out that it was in scoop-extras.

In my opinion, its location should be in scoop.
What about your opinion ?

**Comment by lukesampson** [comment]
We use a convention that the main bucket/repo is only for stable versions. The [readme](https://github.com/lukesampson/scoop-extras/blob/master/README.md) for extras has some more info.

I'll move your latest dart-dev back to scoop-extras for now. Thanks for these commits

**Comment by sestegra** [comment]
Ok, you can close this issue.
