### ISSUE TITLE
fastcopy@3.61: download failed (with or without aria2)

### ISSUE THREAD

**Issue by SuperTitanjr** [lukesampson/scoop-extras#1403]
The link that is using https://fastcopy.jp/archive/FastCopy361_installer.zip doesn't exist

**Comment by brandon93s** [comment]
The archive download is no longer provided. To fix this, we'll need to:

1. Update to use a mirror
2. Use a post_install to `/extract` the contents

https://fastcopy.jp/help/fastcopy_eng.htm#install

**Comment by Ash258** [comment]
why post_install? 

You should be fine with `installer.args = ["/silent", "/extract64or32")", "/DIR=$dir"]`
and 
`uninstaller.args = ["/r", "/silent"]`

> hows the installer options. (/silent, /extract or etc)

![args](https://i.imgur.com/qZvcloj.png)

**Comment by rasa** [comment]
Here's an example of supporting 32bit: https://github.com/lurdan/scoop-bucket/blob/master/fastcopy.json

**Comment by rasa** [comment]
Fixed in #1480
