### ISSUE TITLE
kitty@0.70.0.6: hash check failed

### ISSUE THREAD

**Issue by tomasorti** [lukesampson/scoop-extras#1476]
etomort@ES-00002604 ~
λ scoop install kitty
Installing 'kitty' (0.70.0.6) [64bit]
Loading kitty from cache
Checking hash of kitty ... ok.
kitty (283.5 KB) [====================================================================================================================================================================================] 100%
Checking hash of kitty ... ERROR Hash check failed!
App:         extras/kitty
URL:         https://www.9bis.net/kitty/?file=kageant.exe#/kageant.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    3bdea85a5ef121a059fa04b41b24ed0ff14a804549a1aa73f3be076958bd0371
Actual:      19960928c72d3d94aed10cd8044e93c2a193ffba8a3cd8bfee1311e4666e42fc

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=kitty%400.70.0.6%3a+hash+check+failed
etomort@ES-00002604 ~

**Comment by Ash258** [comment]
#1471

**Comment by rasa** [comment]
Fixed in https://github.com/lukesampson/scoop-extras/pull/1477
