### ISSUE TITLE
zeal.ini is installed as a folder instead of a file

### ISSUE THREAD

**Issue by zhaocai** [lukesampson/scoop-extras#1481]
https://github.com/lukesampson/scoop-extras/blob/ae9d03c0ce987e3741bd12c2558fe5ec1430d70d/zeal.json#L19

`zeal.ini` is a config file. No settings can be saved if it is a folder.

**Comment by Ash258** [comment]
lukesampson/scoop#2779

**Comment by Ash258** [comment]
If you want temporary solution:

1. Uninstall Zeal: `scoop unisntall zeal --purge`
1. Go to $env:SCOOP\persist
1. Create folder zeal
1. Create zeal.ini file inside zeal folder
1. `scoop install zeal`

It should correctly assume file instead of folder

**Comment by rasa** [comment]
Closing as a dup of https://github.com/lukesampson/scoop/pull/2779

**Comment by studoot** [comment]
It seems to me that lukesampson/scoop#2779 doesn't actually fix the underlying problem, which is that zeal.ini is created as a driectory, not as a file. Is some change required in the zeal recipe to tell scoop that zeal.ini is a linked file, not a linked directory?

Looking in the text of lukesampson/scoop#2779, I see the following text:

```
 "pre_install": [
        "if (!(test-path \"$dir\\dummy.txt\")) { new-item -force \"$dir\\dummy.txt\" -itemtype file | out-null }",
        "if (!(test-path \"$dir\\dummydir\")) { new-item \"$dir\\dummydir\" -itemtype directory | out-null }",
        "if (!(test-path \"$dir\\subdir\")) { new-item \"$dir\\subdir\" -itemtype directory | out-null }",
        "if (!(test-path \"$dir\\subdir\\subdummydir\")) { new-item \"$dir\\subdir\\subdummydir\" -itemtype directory | out-null }",
        "if (!(test-path \"$dir\\subdir\\subdummy.txt\")) { new-item -force \"$dir\\subdir\\subdummy.txt\" -itemtype file | out-null }",
    ],
    "persist": [
        "dummy.txt",
        "dummydir",
        "subdir\\subdummydir",
        "subdir\\subdummy.txt"
    ]
```

which implies that the zeal recipe needs a pre-install step to create the `zeal.ini` file and `cache` and `docsets` directories? Like this:

```
 "pre_install": [
        "if (!(test-path \"$dir\\zeal.ini\")) { new-item -force \"$dir\\zeal.ini\" -itemtype file | out-null }",
    ],
    "persist": [
        "zeal.ini",
        "cache",
        "docsets",
    ]
```
If that's the case, I'll do a pull request for Zeal to fix this...
