### ISSUE TITLE
whois 404

### ISSUE THREAD

**Issue by Bazalia** [lukesampson/scoop-extras#150]
I tried running "scoop install whois" and I got "downloading https://download.sysinternals.com/files/WhoIs.zip...The remote server returned an error: (404) Not Found."

**Comment by webwesen** [comment]
same issue for me when trying to install sysinternals. 
a workaround - download the zip, put it into cache, rename it in the same way scoop expects and run "install" again

**Comment by swyphcosmo** [comment]
I just checked this download, and it works now. This issue can probably be closed.
