### ISSUE TITLE
bandizip@6.18: hash check failed

### ISSUE THREAD

**Issue by chaosgrass** [lukesampson/scoop-extras#1540]
C:\Windows\system32>scoop install bandizip
Updating Scoop...
Update failed.
Installing 'bandizip' (6.18) [64bit]
BANDIZIP-PORTABLE-GL-64BIT.ZIP (3.6 MB) [=====================================================================] 100%
Checking hash of BANDIZIP-PORTABLE-GL-64BIT.ZIP ... ERROR Hash check failed!
App:         extras/bandizip
URL:         https://dl.bandisoft.com/bandizip/BANDIZIP-PORTABLE-GL-64BIT.ZIP
First bytes: 50 4B 03 04 14 00 02 00
Expected:    db7fbebce4be8076fcf362859d62fbc8af717816b99c2206d40c3cbc948c498d
Actual:      f24b48777e803cdef7ed8e2d084aca8692881f3d1dd0228d7ebc44f6ecd6a838

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=bandizip%406.18%3a+hash+check+failed

**Comment by rasa** [comment]
`Update failed ` is your issue, sorry
