### ISSUE TITLE
etcher@1.4.8: hash check failed

### ISSUE THREAD

**Issue by shacal** [lukesampson/scoop-extras#1562]
Checking hash of balenaEtcher-Setup-1.4.8-x64.exe ... ERROR Hash check failed!
App:         Extras/etcher
URL:         https://github.com/balena-io/etcher/releases/download/v1.4.8/balenaEtcher-Setup-1.4.8-x64.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    b8f8114cc2e106c2a9bd4b1855180f547b7da6ffbcb763c66a8d0d3a1655fb0c
Actual:      e96da0150428e29c9effcd6a32175a36ad49ffd5c7e5ae3823deea6b239f2ebb

Don't have time to day make pull, hope someone can :)

**Comment by r15ch13** [comment]
`b8f8114cc2e106c2a9bd4b1855180f547b7da6ffbcb763c66a8d0d3a1655fb0c` is the correct hash, please try again.
