### ISSUE TITLE
defraggler@2.22.995: hash check failed

### ISSUE THREAD

**Issue by strange-life** [lukesampson/scoop-extras#1570]
Checking hash of downloadfile ... ERROR Hash check failed!
App:         extras/defraggler
URL:         https://www.piriform.com/defraggler/download/portable/downloadfile#/dl.7z
First bytes: 3C 4D 45 54 41 20 48 54
Expected:    2edfa974fc2e8e34c0b8c152077da9c3a4ab28cad81a4ced463f0cf6634a0f01
Actual:      fb249f429180a78992375a0f736343a8cd1f6bffe5e940411f6cca448e019471

**Comment by rasa** [comment]
The hash in the manifest (the “expected” hash above) is correct. Please try again.
2edfa974fc2e8e34c0b8c152077da9c3a4ab28cad81a4ced463f0cf6634a0f01
