### ISSUE TITLE
[Request] Add Free Download Manager

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop-extras#1598]
> [Free Download Manager](https://www.freedownloadmanager.org/) is a powerful modern download accelerator and organizer for Windows and Mac.

This thing is amazing. It's a very simple GUI downloader that supports torrents, HTTP, FTP, and all sort of protocols. It is recommended by [Debian](https://www.debian.org/CD/http-ftp/).

It supports install arguments.

**Comment by MCOfficer** [comment]
Turns out that thing is InnoSetup-based, yay! However, there are multiple versions - a 3.9.7 for Windows XP and greater, and a 5.1.x for Windows 7 and greater. 

Not sure how to deal with that.

**Comment by NatoBoram** [comment]
Creating a package `freedownloadmanager` for version 5 and `freedownloadmanagerlegacy` on version 3 would satisfy everyone. I personally don't see the interest in v3 since it's so far behind and I'd rather run Linux than Windows XP, but to each their own.

According to [Wikipedia](https://en.wikipedia.org/wiki/Free_Download_Manager), older versions were GNU GPv2 hosted on [SourceForge](https://sourceforge.net/projects/freedownload/), and newer versions are proprietary.
