### ISSUE TITLE
foobar2000 ssl failed download

### ISSUE THREAD

**Issue by f0ff886f** [lukesampson/scoop-extras#1646]
```
scoop install foobar2000
Installing 'foobar2000' (1.4.1) [64bit]
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
URL https://www.videohelp.com/download/foobar2000_v1.4.1.exe is not valid
```

Can we switch to the official foobar download server?

ie. https://www.foobar2000.org/getfile/63dcd14df77833927600f68d0e9a0a5c/foobar2000_v1.4.1.exe

**Comment by rasa** [comment]
It’s now 
http://www.foobar2000.org/getfile/076644d3289a8c07fbd6d107eabf6033/foobar2000_v1.4.2.exe

**Comment by r15ch13** [comment]
The URL changes every session

**Comment by f0ff886f** [comment]
Is it proper scoop-fu to read a download page and grab the latest link on package install?

The hashes should always be the same so it shouldn't be a security issue.

`(\/getfile\/[0-9a-z]+\/foobar2000_v\d\.\d\.\d\.exe)` will match the latest foobar2000 version when parsing http://foobar2000.org/download

If this behaviour is allowed I can try to make an PR for this.

**Comment by Ash258** [comment]
This should not be problem. You need only this:

```json
"checkver": {
    "url": "http://foobar2000.org/download",
    "regex": "getfile/(?<junk>.+)/foobar2000_v([\\d\\.]+)\\.exe"
},
"autoupdate": {
    "url": "http://www.foobar2000.org/getfile/$matchJunk/foobar2000_v$version.exe"
}
```
That junk could be stricted to something like `[a-zA-Z\\d]`, but everything should be good since it is followed with slash and unchanged string.

**Comment by f0ff886f** [comment]
Ah wait, I see this manifest was upgraded to not download from foobar2000.org at all, it now downloads from videohelp.com.

https://github.com/lukesampson/scoop-extras/blob/master/bucket/foobar2000.json

Is this OK? If so this issue can just be closed.

**Comment by Ash258** [comment]
If you no longer meet this then close this.

But that manifest could be edited to not install. Only extraction should be enough

![image](https://user-images.githubusercontent.com/13260377/56271117-fc718f00-60f7-11e9-8a3e-2a1926844b85.png)

**Comment by f0ff886f** [comment]
I will leave that re-work for a different issue in that case, since this one was specifically about the download link and the hash failing, but it seems to be happy, I apologize for the confusion.
