### ISSUE TITLE
streamlink@1.0.0 package broken (fails to install)

### ISSUE THREAD

**Issue by f0ff886f** [lukesampson/scoop-extras#1680]
```
Updating 'streamlink' (0.14.2 -> 1.0.0)
Uninstalling 'streamlink' (0.14.2)
Removing shim for 'streamlink'.
Unlinking ~\scoop\apps\streamlink\current
Installing 'streamlink' (1.0.0) [64bit]
streamlink-1.0.0.exe (38.9 MB) [==============================================================================] 100%
Checking hash of streamlink-1.0.0.exe ... ok.
Extracting dl.7z ... done.
Linking ~\scoop\apps\streamlink\current => ~\scoop\apps\streamlink\1.0.0
Creating shim for 'streamlink'.
Can't shim 'bin\streamlink.exe': File doesn't exist.
```

The dl.7z archive in the cache indeed contains no `streamlink.exe` in the `bin/` folder, could be an upstream issue.

**Comment by r15ch13** [comment]
Interesting! The installer appends the content of `bin\streamlink-append.zip` to `bin\launcher_exe.dat` including a path to python to create the `streamlink.exe`

Running the following from the `bin` directory works 😁 
```powershell
'#!"..\Python\python.exe"' | Set-Content python.txt
Get-Content -AsByteStream launcher_exe.dat,python.txt,streamlink-append.zip | Set-Content -AsByteStream streamlink.exe
```

**Comment by f0ff886f** [comment]
Question: this requires Powershell 6.0, in 5.1 and older `-AsByteStream` should `-Encoding Byte`. Is there a minimum version of Powershell required for Scoop? I don't know if `-Encoding Byte` works in 6.0, I haven't installed it yet.

**Comment by r15ch13** [comment]
Ah, dang it.I'm aware of this but missed add a check nonetheless ...
