### ISSUE TITLE
Access denied to BCUninstaller settings file inside the install folder

### ISSUE THREAD

**Issue by Klocman** [lukesampson/scoop-extras#1682]
First of all, great work on the project, and thank you for including BCUninstaller!

The issue:
At least some users that use BCU through scoop are reporting a problem with saving settings. They get `Access to the path (...)\BCUninstaller.settings is denied.` error. Because of this they lose settings or see an error at program start. The same issue might also interfere with .xml caches that BCU saves to the same folder.
(The settings are stored in a BCUninstaller.settings file in the same folder as program executable, and are created, modified and deleted as necessary.)

What I would expect to happen:
BCU should have write access to BCUninstaller.settings and *.xml files. BCUninstaller.exe is always supposed to be running elevated, so only admin permissions should be needed.

**Comment by rikuben** [comment]
I think it's because BCUninstaller.settings is created as a folder during installation instead of as a file.
