### ISSUE TITLE
kitty@0.70.0.7: hash check failed

### ISSUE THREAD

**Issue by maddhaze** [lukesampson/scoop-extras#1685]
Starting download with aria2 ...
Download: [#8c379d 0B/0B CN:1 DL:0B]
Download: [#8c379d 0B/0B CN:1 DL:0B]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 8c379d|OK  |   533KiB/s|D:/SysTools/apps/Scoop/cache/kitty#0.70.0.7#https_www.9bis.net_kitty_file_kageant.exe_kageant.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of kitty ... ok.
Checking hash of kitty ... ERROR Hash check failed!
App:         extras/kitty
URL:         https://www.9bis.net/kitty/?file=kageant.exe#/kageant.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    afd3681f32332eca7e2a323bfee860cb6e8cac2485385e1a3a171efb345b816d
Actual:      4cbe17fd75ec628d7f0ce3b530b227b24878d9ccd971fa13835028bd9bf4b84d

**Comment by rasa** [comment]
Dup of #1569

**Comment by r15ch13** [comment]
@rasa wrong issue number? 😲

**Comment by rasa** [comment]
Lysdexic, sorry.
