### ISSUE TITLE
cheat-engine@6.8.3: hash check failed

### ISSUE THREAD

**Issue by ReduxxedPollux** [lukesampson/scoop-extras#1731]
~ $ scoop install cheat-engine
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'cheat-engine' (6.8.3) [64bit]
Starting download with aria2 ...
Download: [#d3cc83 0B/14MiB(0%) CN:1 DL:0B] [FileAlloc:#d3cc83 8.0MiB/14MiB(56%)]
Download: [#d3cc83 6.7MiB/14MiB(48%) CN:2 DL:11MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d3cc83|OK  |    12MiB/s|~/Scoop/cache/cheat-engine#6.8.3#https_github.com_cheat-engin
e_cheat-engine_releases_download_6.8.3_CheatEngine683.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of CheatEngine683.exe ... ERROR Hash check failed!
App:         extras/cheat-engine
URL:         https://github.com/cheat-engine/cheat-engine/releases/download/6.8.3/CheatEngine683
.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    bbe0a00833e54a6ce70fefa15f0f09c637ce894047d4ce534b2654508cba8bfb
Actual:      e642d38bb0fefca31f8ffd81a3e60b0980a0a57d9567a93a0cb616e6cb7aeeda

Please try again or create a new issue by using the following link and paste your console output
:
https://github.com/lukesampson/scoop-extras/issues/new?title=cheat-engine%406.8.3%3a+hash+check+
failed

**Comment by r15ch13** [comment]
Fixed with #1726
