### ISSUE TITLE
potplayer@1.7.17508: hash check failed

### ISSUE THREAD

**Issue by Melvinkooi** [lukesampson/scoop-extras#1750]
> Updating 'potplayer' (1.7.16291 -> 1.7.17508)  
> Uninstalling 'potplayer' (1.7.16291)
> Unlinking ~\scoop\apps\potplayer\current
> Installing 'potplayer' (1.7.17508) [64bit]
> PotPlayerSetup64.exe (27,0 MB) [==============================================================================] 100%
> Checking hash of PotPlayerSetup64.exe ... ERROR Hash check failed!
> App:         Ash258/potplayer
> URL:         https://t1.daumcdn.net/potplayer/PotPlayer/Version/Latest/PotPlayerSetup64.exe#/cosi.7z
> First bytes: 4D 5A 90 00 03 00 00 00
> Expected:    521672085381e1ab5d2d58d56e0aee38d99ccb15cafcef0223049e2d3522d352
> Actual:      2dcc9a625b27b1730c02d5398c7f20cf88e43982124516d1606cb62210f88a97
> Please contact the bucket maintainer!

**Comment by r15ch13** [comment]
@Ash258 is the maintainer of this program.

**Comment by Melvinkooi** [comment]
Whoops. Didn't read the repository name. I also see that he has fixed it. So I'll close this.
