### ISSUE TITLE
GitExtensions v3.0.2

### ISSUE THREAD

**Issue by devhawk** [lukesampson/scoop-extras#1753]
https://github.com/gitextensions/gitextensions/releases/tag/v3.0.2. 

There was also a [v3.0.1 release](https://github.com/gitextensions/gitextensions/releases/tag/v3.0.1) but it's marked as pre-release so I'm not sure if scoop should have picked that up. I only noticed v3.0.2 was available becuase GitExtensions GUI prompted me to update to the latest version. It did NOT do that for v3.0.1.

I don't know how the autoupdate feature is supposed to work, but it appears that the #964 fix has been reverted as gitextensions.json appears to be looking for GitExtensions-$version-Mono.zip instead of GitExtensions-$version-Portable.zip

**Comment by devhawk** [comment]
As far as I can tell, scoop still hasn't picked up the 3.0.2 release of Git Extensions, even with #1756. Tagging @r15ch13 and @ebugusey for visibility.

**Comment by ebugusey** [comment]
Try `scoop update --force`. There are some problems in scoop with update detection.

**Comment by devhawk** [comment]
`scoop update gitextensions -f` downloaded 3.0.2 but scoop still listed 3.0.0 as the current version. I deleted both 3.0.2 and 3.0.0 and reinstalled to pick up the right version
