### ISSUE TITLE
musicbee not being updated

### ISSUE THREAD

**Issue by Spiraster** [lukesampson/scoop-extras#1764]
A new version was released ~3 months ago (Nov 26, 2018), but the manifest has yet to be updated to reflect it.

I tested the existing manifest and it correctly recognizes the new version, so I'm not sure what the issue is.

**Comment by r15ch13** [comment]
They only provide a mediafire.com URL, which can't be auto updated.
Fixed it manually.

**Comment by kerhbal** [comment]
@r15ch13 it seems the expected hash is wrong.
Expected:    e1ff59e5ec5faeef023247bc1107419d4edeccd967881a6c062c4c636afdf689
Actual:      fe4875f540c3e066e8c12c82696da71b940bfa8d88419bbb6f888f589b15a900

And I found the expected hash above is from installer, not the portable version.

**Comment by r15ch13** [comment]
Fixed 😁

**Comment by kerhbal** [comment]
@r15ch13 sorry to bother, but it seems the pre_install process is based on portable version, which was used in older versions. So error will show up during installation.
```
"pre_install": "(Get-ChildItem \"$dir\\MusicBeePortable_*.exe\" | Rename-Item -NewName \"setup.exe\");",
```

**Comment by Spiraster** [comment]
Oh sorry, I should have looked more closely. Thanks for the manual fix!

**Comment by r15ch13** [comment]
Fixed again. Now it should be the portable version, with the correct hash and a working pre_install script ... 😁
