### ISSUE TITLE
ConEmu 19.02.24 is broken

### ISSUE THREAD

**Issue by ggobbe** [lukesampson/scoop-extras#1773]
There is an issue with ConEmu 19.02.24 which makes it broken for most users.
https://github.com/Maximus5/ConEmu/issues/1835

Could we revert to 19.02.17 until a fix is released by the ConEmu team?

Commit to revert: https://github.com/lukesampson/scoop-extras/commit/401dff86dac536c29b10f74bcd0d016cd659a513#diff-8fc99483cd514d2c650e762ddf99cd2d

**Comment by Ash258** [comment]
`scoop install conemu@19.02.17`

**Comment by ebugusey** [comment]
ConEmu 19.02.25 is released. Issue should be closed.

**Comment by Ash258** [comment]
Excavator already updated b05ff3d70d60e76f96b51ef23ff8f4f71d27a8fa

Test and close if issue no longer occurs
