### ISSUE TITLE
posh-git: The syntax of the command is incorrect.

### ISSUE THREAD

**Issue by jemgraves** [lukesampson/scoop-extras#1781]
Scoop version bc9272f6, not happening on my other machine which has version 6e989ad6, both commits from today so I don't think there's any breaking change there but it's possible.

### $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Receiving an error when attempting a fresh install of posh-git: `The syntax of the command is incorrect.`

```
PS C:\Users\jemgraves\source> scoop install posh-git
Installing 'posh-git' (0.7.1) [64bit]
Loading v0.7.1.zip from cache
Checking hash of v0.7.1.zip ... ok.
Extracting v0.7.1.zip ... done.
Linking ~\scoop\apps\posh-git\current => ~\scoop\apps\posh-git\0.7.1
Installing PowerShell module 'posh-git'
Linking ~\scoop\modules\posh-git => ~\scoop\apps\posh-git\current
The syntax of the command is incorrect.
'posh-git' (0.7.1) was installed successfully!
Notes
-----
See usage: https://github.com/dahlbyk/posh-git#using-posh-git
```

Scoop lists the program as installed, but when attempting to import the posh-git module in powershell I get this:

```
PS C:\Users\jemgraves\source> Import-Module posh-git
Import-Module : The specified module 'posh-git' was not loaded because no valid module file was found
in any module directory.
At line:1 char:1
+ Import-Module posh-git
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (posh-git:String) [Import-Module], FileNotFoundExc
   eption
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleComman
   d
```

Received the same error when updating openssh today, although I don't know if openssh tries to install a psmodule, the line that appears to be failing inthat bucket is `"cmd /c mklink /j \"$dir\\home\\%UserName%\\.ssh\" \"%UserProfile%\\.ssh\""` in the pre-install section of that bucket:

```
...
Running pre-install script...


    Directory: C:\ProgramData\scoop\apps\openssh\7.6p1


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2/26/2019   4:48 PM                tmp
d-----        2/26/2019   4:48 PM                home


    Directory: C:\ProgramData\scoop\apps\openssh\7.6p1\home


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2/26/2019   4:48 PM                Jennifer Graves


    Directory: C:\Users\Jennifer Graves


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/14/2019   2:13 PM                .ssh
The syntax of the command is incorrect.
Linking C:\ProgramData\scoop\apps\openssh\current => C:\ProgramData\scoop\apps\openssh\7.6p1
Creating shim for 'findssl.sh'.
Creating shim for 'scp'.
Creating shim for 'sftp'.
Creating shim for 'ssh'.
Creating shim for 'ssh-add'.
Creating shim for 'ssh-agent'.
Creating shim for 'ssh-copy-id'.
Creating shim for 'ssh-keygen'.
Creating shim for 'ssh-keyscan'.
Creating shim for 'sshd'.
'openssh' (7.6p1) was installed successfully!
```

Should I open up an issue in main as well regarding openssh? I'm not sure if they're related.

**Comment by manuhornung** [comment]
The same issue occurs for me.

I compared the commits mentioned above but I couldn't find any difference in the scoop logic itself. Just some version updates in different buckets which should have no impact on this.

Any ideas what else might cause this?

**Comment by TyPh00nCdr** [comment]
I debugged `<scoop-dir>/lib/psmodules.ps1` and @manuhornung's comment points in the right direction. The directories in [`install_psmodule#L29`](https://github.com/lukesampson/scoop/blob/b9b48182b4d921aa92e9b3e53ab2d2c376d467d7/lib/psmodules.ps1#L29) and [`uninstall_psmodule#L43`](https://github.com/lukesampson/scoop/blob/b9b48182b4d921aa92e9b3e53ab2d2c376d467d7/lib/psmodules.ps1#L43) are not escaped properly and throw _The syntax of the command is incorrect_ when called with a user dir containing white spaces. 

Fixed by escaping:
```
& "$env:COMSPEC" /c "mklink /j `"$linkfrom`" `"$dir`"" | out-null
```
```
& "$env:COMSPEC" /c "rmdir `"$linkfrom`""
```

**Comment by TyPh00nCdr** [comment]
lukesampson/scoop#3538 should fix this.
