### ISSUE TITLE
[Request] Add VMWare Horizon Client

### ISSUE THREAD

**Issue by beppegg** [lukesampson/scoop-extras#1784]
Hello,

I'd like to have vmware horizon client available in Scoop.
I tried to create a manifest for it by myself but it seems I'm not good enough 😞 

The link for downloading the client is at:
https://download3.vmware.com/software/view/viewclients/CART19FQ4/VMware-Horizon-Client-4.10.0-11021086.exe
while the general homepage for the product should be:
https://my.vmware.com/web/vmware/info?slug=desktop_end_user_computing/vmware_horizon_clients/4_0

**Comment by Ash258** [comment]
https://github.com/Ash258/scoop-Ash258/blob/master/bucket/VMware.json Could help you

**Comment by beppegg** [comment]
Thank you @Ash258 !! That really did the trick, I used your file with just the little changes needed for VMWare Horizon Client to work.

The problem is, the installation keeps asking for elevated privileges, and it automatically and forcefully reboots your computer. I don't know how to fix those problems, and I'm dubious about committing the manifest back here with those problems.

What do you think? If you like, and with @Ash258 's permission, I can craft a pull request for scoop; otherwise I will store it in a repository of mine.

Regards,
Giuseppe

**Comment by Ash258** [comment]
I think everything under extras and main bucket should be UAC popups free to confort most users.

For that restarts, You should be able to set `/norestart` see:
https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/4.10/horizon-client-windows-installation/GUID-2DDF9C24-A1E9-4357-A832-2A5A19352D61.html
https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/4.10/horizon-client-windows-installation/GUID-1DCFA762-6F08-455D-82C0-2A18C87E41D5.html
https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/4.10/horizon-client-windows-installation/GUID-AFB637E0-9395-4A71-8103-7D6DF0103295.html

**Comment by rasa** [comment]
Close
Closing as this issue is stale. Please reopen if this is still an issue.
