### ISSUE TITLE
teamviewer@14.1.9025: hash check failed

### ISSUE THREAD

**Issue by KenZZ107** [lukesampson/scoop-extras#1786]
~ $ scoop install teamviewer
Installing 'teamviewer' (14.1.9025) [64bit]
TeamViewerPortable.zip (27.2 MB) [=================================================================================================================================================================================================] 100%
Checking hash of TeamViewerPortable.zip ... ERROR Hash check failed!
App:         extras/teamviewer
URL:         https://download.teamviewer.com/download/version_14x/TeamViewerPortable.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    5d17eb37bc383f70026994acbfbf84db00ab4f324a1f4213b609021f607e63de
Actual:      b994a6bd5e273e7b77ce13bf08c61bdc85c871d23bc898396e646dea26d7d245

**Comment by rasa** [comment]
Fixed in https://github.com/lukesampson/scoop-extras/commit/edf2a38ad6a7ffc39d003435ebe3fd26916f1a66
