### ISSUE TITLE
[Request] Add android ndk

### ISSUE THREAD

**Issue by fcying** [lukesampson/scoop-extras#1802]
https://developer.android.google.cn/ndk/downloads

bucket has `android-sdk`, `android-studio` now, but have not `android-ndk`

**Comment by TheCjw** [comment]
After installing android-sdk, you can install ndk-bundle via `sdkmanager`. Then adding ndk-bundle path to your `$env:PATH`.

**Comment by fcying** [comment]
@TheCjw  tks~
