### ISSUE TITLE
sysinternals@February.18.2019: hash check failed

### ISSUE THREAD

**Issue by antonburger** [lukesampson/scoop-extras#1809]
```
> scoop install sysinternals
Installing 'sysinternals' (February.18.2019) [64bit]
SysinternalsSuite.zip (24.1 MB) [======<snip>=======]
Checking hash of SysinternalsSuite.zip ... ERROR Hash check failed!
App:         extras/sysinternals
URL:         https://download.sysinternals.com/files/SysinternalsSuite.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    a510c31c2cc591a16f342e7cba5dc8409eaf08c9b56729cf132c95c69e196787
Actual:      9b9d6bd0718a5680b2322398345271142783156dc8d6f3642bce72f80337850f
```

**Comment by antonburger** [comment]
Downloading the file using a browser, and checking it with `Get-Hash` from Pscx, confirms the actual hash is the `9b9d...` value instead of the one in the manifest. The other two instances of this so far (#1812 and #1819) report the same actual hash value.

```
Get-Hash -Algorithm SHA256 SysinternalsSuite.zip
```

**Comment by antonburger** [comment]
I happened to get this downloaded on my work machine before it changed (the failure happened on my personal one), so I have the two zip files available to compare.

_ | Original | Updated
--- | --- | ---
Size | 24,655,521 bytes | 25,313,039 bytes

These are the differences between files in the two archives:

Filename | Version (original) | Size (original) | Modified (original) | Version (updated) | Size (updated) | Modified (updated) | Individual tool page
--- | --- | --- | --- | --- | --- | --- | ---
`psloglist.exe` | 2.71.0.0 | 178,040 bytes | 2010-04-27 20:04:06 | 2.81.0.0 | 444,984 bytes | 2019-03-04 11:54:54 | [Version 2.81 published 2019-03-05][1]
`psloglist64.exe` | - (not present) | - | - | 2.81.0.0 | 579,128 bytes | 2019-03-04 11:52:44 | ditto
`sigcheck.exe` | 2.71.0.0 | 378,632 bytes | 2018-11-22 01:59:04 | 2.72.0.0 | 824,072 bytes | 2019-02-28 16:43:00 | [Version 2.72 published 2019-03-05][2]
`sigcheck64.exe` | 2.71.0.0 | 873,520 bytes | 2018-11-22 01:59:05 | 2.72.0.0 | 1,135,152 bytes | 2019-02-28 16:41:14 | ditto

[1]: https://docs.microsoft.com/en-us/sysinternals/downloads/psloglist
[2]: https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck

The original `psloglist.exe` has only a SHA1 signature, produced by a certificate that expired in 2011. But all the other differing `.exe` files have both SHA1 and SHA256 signatures (all valid). And the certs for all of _those_ SHA1 signatures have the same thumbprint, as do the certs for all of the SHA256 signatures.

Between the signatures and the updated version numbers and publish dates on the pages for the individual tools, the updated archive is probably OK, assuming the original "18 February 2019" one is. Whatever workflow publishes the combined suite of tools must just involve a manual step, or allow for some inconsistency to creep in, publishing the updated zip file but not updating the dates in the documentation to match.

**Comment by rasa** [comment]
@antonburger Thank you for the detailed error reports!

**Comment by antonburger** [comment]
@rasa No worries! Probably completely OTT checking all that stuff, especially given the source for this package, but better safe than sorry.
