### ISSUE TITLE
teamspeak3: double-packed installer breaks installation

### ISSUE THREAD

**Issue by icedream** [lukesampson/scoop-extras#1810]
The TeamSpeak3 installer seems to be double-packed now, so extracting the archive will only result in cryptic resources being written to the disk instead of the wanted installation file tree. This breaks the package as-is in the bucket.

```pslog
Installing 'teamspeak3' (3.2.3) [64bit]
Loading TeamSpeak3-Client-win64-3.2.3.exe from cache.
Checking hash of TeamSpeak3-Client-win64-3.2.3.exe ... ok.
Extracting cosi.7z ... done.
Linking ~\scoop\apps\teamspeak3\current => ~\scoop\apps\teamspeak3\3.2.3
Creating shortcut for Team Speak 3 (ts3client_win64.exe) failed: Couldn't find C:\Users\ICEDR\scoop\apps\teamspeak3\current\ts3client_win64.exe
Persisting config
Running post-install script...
Remove-Item : Der Pfad "C:\Users\ICEDR\scoop\apps\teamspeak3\current\$PLUGINSDIR" kann nicht gefunden werden, da er
nicht vorhanden ist.
In Zeile:1 Zeichen:1
+ Remove-Item "$dir\`$PLUGINSDIR" -Force -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ICEDR\...ent\$PLUGINSDIR:String) [Remove-Item], ItemNotFoun
   dException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

'teamspeak3' (3.2.3) was installed successfully!
```

The installed file tree looks like this:

![image](https://user-images.githubusercontent.com/807772/53841768-e53e6e00-3f9d-11e9-9bf5-534ff9b3c75e.png)

**Comment by Ash258** [comment]
Can't reproduce. 

![Pr](https://i.imgur.com/vCk8oAb.png)
![t](https://i.imgur.com/A7NsoyN.png)

**Comment by icedream** [comment]
I am suspecting that maybe an older version of 7-zip is registered in PATH and that it does not properly unpack the binary.l then. Will check on that later.

**Comment by icedream** [comment]
I'm confirming that this issue occured due to another 7z binary being in PATH, specifically a copy of 7z shipped with the Windows Installer of Lua for Windows (not installed via Scoop). I'm closing this issue.
