### ISSUE TITLE
recuva@1.53.1087: hash check failed

### ISSUE THREAD

**Issue by astappiev** [lukesampson/scoop-extras#1820]
App:         extras/recuva
URL:         https://www.piriform.com/recuva/download/portable/downloadfile#/dl.7z
First bytes: 3C 4D 45 54 41 20 48 54
Expected:    997a082fb03fcdf272d58c25aba488a136cf115a1e1b53930339fb5ef95bf91f
Actual:      fb249f429180a78992375a0f736343a8cd1f6bffe5e940411f6cca448e019471

**Comment by niheaven** [comment]
Please download again. The hash in manifest is the right one.

**Comment by astappiev** [comment]
Still the same error.
This could help to investigate

```
λ wget https://www.piriform.com/recuva/download/portable/downloadfile#/dl.7z
--2019-03-08 12:03:49--  https://www.piriform.com/recuva/download/portable/downloadfile
Resolving www.piriform.com (www.piriform.com)... 151.101.36.64
Connecting to www.piriform.com (www.piriform.com)|151.101.36.64|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.ccleaner.com/recuva/download/portable/downloadfile [following]
--2019-03-08 12:03:49--  https://www.ccleaner.com/recuva/download/portable/downloadfile
Resolving www.ccleaner.com (www.ccleaner.com)... 151.101.38.202
Connecting to www.ccleaner.com (www.ccleaner.com)|151.101.38.202|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48 [text/html]
Saving to: 'downloadfile'

downloadfile                                                100%[=========================================================================================================================================>]      48  --.-KB/s    in 0s

2019-03-08 12:03:49 (194 KB/s) - 'downloadfile' saved [48/48]


λ certUtil -hashfile downloadfile SHA256
SHA256 hash of downloadfile:
fb249f429180a78992375a0f736343a8cd1f6bffe5e940411f6cca448e019471
CertUtil: -hashfile command completed successfully.
```

**Comment by astappiev** [comment]
From output above you can see tha by given url I can't get an archive, instead I'm getting html page.
And hash of the page is identical to what `scoop` found. But when I put the url to browser, I can get archive as expected.

**Comment by astappiev** [comment]
Disabling `aria2` didn't help.

**Comment by niheaven** [comment]
![2019-03-08_20-18-33](https://user-images.githubusercontent.com/5832170/54028292-89632780-41df-11e9-92d9-6c74794cd2b0.png)
`wget` in macOS.

I've tried twice in Windows and I've not met hash wrong...

You could see the following info when checked [url](https://www.piriform.com/recuva/download/portable/downloadfile)'s message header:

```
HTTP/1.1 200 OK
Content-Type: unknown/unknown
X-Frame-Options: SAMEORIGIN
X-Adguard-Filtered: Adguard for Mac; version=1.5.14
content-disposition: attachment; filename=rcsetup153.zip
Age: 3
Via: 1.1 varnish
Cache-Key: /recuva/download/portable/downloadfilewww.ccleaner.comCN(null)
Cache-Control: max-age=0
Date: Fri, 08 Mar 2019 12:22:23 GMT
UserCountry: CN
Content-Length: 4007927
Connection: keep-alive
Accept-Ranges: bytes
X-Served-By: cache-tyo19945-TYO
X-Cache: MISS
```

It will actually return a file called `rcsetup153.zip` and it's length is 4007927B, 3.82MB.

**Comment by rasa** [comment]
The hash in the manifest (the “expected” hash above) is correct. Please try again.
997a082fb03fcdf272d58c25aba488a136cf115a1e1b53930339fb5ef95bf91f
