### ISSUE TITLE
msiafterburner@4.6.0: extract_dir error

### ISSUE THREAD

**Issue by scottLIR** [lukesampson/scoop-extras#1821]
Currently receiving error:

C:\Windows\system32>scoop install msiafterburner
Installing 'msiafterburner' (4.6.0) [64bit]
Loading MSIAfterburnerSetup.zip from cache
Checking hash of MSIAfterburnerSetup.zip ... ok.
Extracting MSIAfterburnerSetup460.7z ... ERROR Could not find '4.6.0'! (error 16)

Just thought i'd let you know, not a huge deal lol.

**Comment by Gargauth** [comment]
Created PR https://github.com/lukesampson/scoop-extras/pull/1822
