### ISSUE TITLE
Zeal doesn't write to persisted preferences file

### ISSUE THREAD

**Issue by studoot** [lukesampson/scoop-extras#1853]
Presuming that [the workaround in  #1481](https://github.com/lukesampson/scoop-extras/issues/1481#issuecomment-443437042) has been followed, the file `scoop/apps/zeal/current/zeal.ini` should be hard-linked to the file `scoop/persist/zeal/zeal/ini`. That's fine, the way that the Scoop install process has been designed.

Unfortunately, when Zeal updates its preferences, the way that it writes the settings file (ultimately using the `QSaveFile` functionality, which writes to a temporary file before moving the temporary file to the preferences file's location) breaks the hard-link that tied the two copies of the preferences file. This ends up with the preferences file in `scoop/apps/zeal/current/` retaining the preferences, while the file in `scoop/persist/zeal/` remains empty. This will work fine until zeal is updated, at which point the preferences file will be overwritten.

I've verified this hypothesis by looking at the file-id of the two files:

1. After installation, before the preferences are written, the file ids are the same:
    ```
    C:\Users\<me>\scoop>fsutil file queryfileid apps\zeal\0.6.1\zeal.ini
    File ID is 0x000000000000000000470000000007d7

    C:\Users\<me>\scoop>fsutil file queryfileid persist\zeal\zeal.ini
    File ID is 0x000000000000000000470000000007d7
    ```

2. After the preferences are written, the file ids are different, with the file in the `apps` directory changing:
    ```
    C:\Users\u404261\scoop>fsutil file queryfileid apps\zeal\0.6.1\zeal.ini
    File ID is 0x0000000000000000000600000002e7ac

    C:\Users\u404261\scoop>fsutil file queryfileid persist\zeal\zeal.ini
    File ID is 0x000000000000000000470000000007d7
    ```

**Comment by rasa** [comment]
This isn't something that scoop can fix, sorry. It's an upstream issue.
