### ISSUE TITLE
kakaotalk@2.7.6.2046: hash check failed

### ISSUE THREAD

**Issue by gracefullight** [lukesampson/scoop-extras#1881]
Installing 'kakaotalk' (2.7.6.2046) [64bit]
Starting download with aria2 ...
Download: [#0096bd 10MiB/41MiB(24%) CN:5 DL:11MiB ETA:2s]
Download: [#0096bd 21MiB/41MiB(51%) CN:5 DL:11MiB ETA:1s]
Download: [#0096bd 32MiB/41MiB(77%) CN:4 DL:11MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 0096bd|OK  |    11MiB/s|D:/scoop/cache/kakaotalk#2.7.6.2046#http_app.pc.kakao.com_talk_win32_KakaoTalk_Setup.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of KakaoTalk_Setup.exe ... ERROR Hash check failed!
App:         extras/kakaotalk
URL:         http://app.pc.kakao.com/talk/win32/KakaoTalk_Setup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    e0f1508eef5df317cb99775ac92adc584f7c021190ec413dd4efa63e7b79685e
Actual:      4b9ef17e8ff398ac46596a1717f2ee252a0a7fe64d0a3886e5f59ed34428fa27

**Comment by r15ch13** [comment]
Should be fixed with https://github.com/lukesampson/scoop-extras/commit/9ff391001f7679f5a5bb04b06f41d5006991d6ff
