### ISSUE TITLE
Can't find "fork" in the extras bucket anymore

### ISSUE THREAD

**Issue by eegabeeva** [lukesampson/scoop-extras#1887]
I had fork installed in my machine through scoop. Now `scoop search` won't find "fork" and I can't even see in the bucket in GutHub anymore. Was it removed?

I mean `https://git-fork.com/windows`.

**Comment by r15ch13** [comment]
There is an open issue about it: https://github.com/lukesampson/scoop-extras/issues/1094

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
