### ISSUE TITLE
kicad@5.1.0_1: hash check failed

### ISSUE THREAD

**Issue by BlueHeaven1969** [lukesampson/scoop-extras#1895]
Installing 'kicad' (5.1.0_1) [64bit]
kicad-5.1.0_1-x86_64.exe (1.1 GB) [=====================================================================================] 100%
Checking hash of kicad-5.1.0_1-x86_64.exe ... ERROR Hash check failed!
App:         extras/kicad
URL:         http://kicad-downloads.s3.cern.ch/windows/stable/kicad-5.1.0_1-x86_64.exe#/kicad-setup.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    917bf067740c2e17c3ff3ad9da342a9e9a16c61b947cc4c532cf3f37fcb2f9ca
Actual:      39b24f6e0492167ab688f45efd1bded07687a69b82e06c356ffa23cbd05e5d76

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=kicad%405.1.0_1%3a+hash+check+failed

**Comment by cycledetector** [comment]
I opened a similar issue 7 days ago, see https://github.com/lukesampson/scoop-extras/issues/1868. For some reason the CERN link did not work for me, so I modified the json file using the link from github,  with the hash 39b24f6e0492167ab688f45efd1bded07687a69b82e06c356ffa23cbd05e5d76 and the installation completed successfully.
