### ISSUE TITLE
flux does not persist user configuration

### ISSUE THREAD

**Issue by h404bi** [lukesampson/scoop-extras#1928]

**Comment by Ash258** [comment]
@h404bi  Will you open PR or give us some information about, where is configuration stored? 🤔😃

**Comment by h404bi** [comment]
![20190327214954](https://user-images.githubusercontent.com/5764917/55081257-78b91980-50da-11e9-805a-4d223c34e22e.jpg)

User can make some custom preset for flux, but I can not find where is the configuration stored, forgive me, not even mention in the settings panel. :(

**Comment by Ash258** [comment]
You lost it on update? Or what happened before losing this configuration?

**Comment by h404bi** [comment]
on update, it started the uninstaller, and all configuration got removed after update, though I didn't know where is the configuration stored.
