### ISSUE TITLE
libreoffice-fresh@6.2.2.2: hash check failed

### ISSUE THREAD

**Issue by JunJi-JiaYue** [lukesampson/scoop-extras#1965]
```
> scoop update *
libreoffice-fresh: 6.2.1.2 -> 6.2.2.2
Updating one outdated app:
Updating 'libreoffice-fresh' (6.2.1.2 -> 6.2.2.2)
Downloading new version
LibreOffice_6.2.2.2_Win_x86.msi (263.9 MB) [==================================================================] 100%
Checking hash of LibreOffice_6.2.2.2_Win_x86.msi ... ERROR Hash check failed!
App:         extras/libreoffice-fresh
URL:         http://downloadarchive.documentfoundation.org/libreoffice/old/6.2.2.2/win/x86/LibreOffice_6.2.2.2_Win_x86.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    97712455a0be321854f57bd11619d112fac15394bdf8b50f56e877f62a71a256
Actual:      87c911ce011c451c46ef5733c904ade8d38a35b8361e7e25b19edd631b83fba1
```

**Comment by linsui** [comment]
[Here](https://download.documentfoundation.org/libreoffice/stable/6.2.2/win/x86/LibreOffice_6.2.2_Win_x86.msi.mirrorlist) is the hash of 6.2.2 x86. So I guess the [hash in the bucket](https://github.com/lukesampson/scoop-extras/blob/a4037e3b66a7875161c6cab9f095bc0e87f36962/bucket/libreoffice-fresh.json#L12) is wrong. And I find that there is no hash in the [mirrorlist of 6.2.2.2](https://downloadarchive.documentfoundation.org/libreoffice/old/6.2.2.2/win/x86_64/LibreOffice_6.2.2.2_Win_x64.msi.mirrorlist) which is different from other version.

**Comment by niheaven** [comment]
If it is no need to install old version of LibreOffice, the url and hash url could be changed.

PS. Portable edition is prefered for scoop. (https://portableapps.com/apps/office/libreoffice_portable)

**Comment by JunJi-JiaYue** [comment]
04fb52
