### ISSUE TITLE
[Request] Add waifu2x-caffe

### ISSUE THREAD

**Issue by Ktr4ks** [lukesampson/scoop-extras#1973]
waifu2x is a tool for upscaling of anime-style art using Deep Convolutional Neural Networks

- _https://github.com/lltcggie/waifu2x-caffe_

**Comment by h404bi** [comment]
FYI: https://github.com/h404bi/dorado/blob/master/bucket/waifu2x-caffe.json

**Comment by Ash258** [comment]
Fixed in de0ef81367f963e1d0005a71d9ab45c8cc5972ef
