### ISSUE TITLE
[Request] Chrome Beta, Dev, and Canary

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop-extras#1984]
I saw that Chrome was supported in https://github.com/lukesampson/scoop-extras/pull/1931.

Google Chrome has multiple channels : https://www.chromium.org/getting-involved/dev-channel

I'd like to request adding the channels Beta, Dev, and Canary.

**Comment by Ash258** [comment]
There is no way how to get these work via scoop in proper way. Until google release some command line parameters / new installer (not that windows thing, which autodownload on run) / zipped application.
