### ISSUE TITLE
[Request] Add SageMath

### ISSUE THREAD

**Issue by ftsimas** [lukesampson/scoop-extras#1995]
SageMath is a free open-source mathematics software system licensed under the GPL. It builds on top of many existing open-source packages such as NumPy, SciPy, matplotlib, Sympy, Maxima, GAP, FLINT, R and many more.

Website:
https://www.sagemath.org/

Releases:
https://github.com/sagemath/sage-windows/releases

**Comment by linsui** [comment]
https://github.com/lukesampson/scoop-extras/pull/2030
