### ISSUE TITLE
defraggler@2.22.995: hash check failed

### ISSUE THREAD

**Issue by gcornejo** [lukesampson/scoop-extras#2006]
Hi, I was trying to install Defraggler, but failed:
Installing 'defraggler' (2.22.995) [64bit]

dl.7z (48 B) [==============================================================================================================================] 100%
Checking hash of dl.7z ... ERROR Hash check failed!
App:         extras/defraggler
URL:         https://www.piriform.com/defraggler/download/portable/downloadfile#/dl.7z
First bytes: 3C 4D 45 54 41 20 48 54
Expected:    2edfa974fc2e8e34c0b8c152077da9c3a4ab28cad81a4ced463f0cf6634a0f01
Actual:      fb249f429180a78992375a0f736343a8cd1f6bffe5e940411f6cca448e019471

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=defraggler%402.22.995%3a+hash+check+failed

**Comment by rasa** [comment]
2edfa974fc2e8e34c0b8c152077da9c3a4ab28cad81a4ced463f0cf6634a0f01 is correct
The hash in the manifest (the “expected” hash above) is correct. Please try again.
