### ISSUE TITLE
imageglass 6.0.12.29 does not launch when igconfig.xml is a link

### ISSUE THREAD

**Issue by klutchell** [lukesampson/scoop-extras#2007]
Since `"persist": "igconfig.xml",` is set in [imageglass.json](https://github.com/lukesampson/scoop-extras/blob/ff7c24d/bucket/imageglass.json#L9) a folder link is created rather than a config file, and imageglass will not launch.

I extracted the imageglass tarball manually, and can confirm it works when `igconfig.xml` is a valid xml file, or does not exist.

Likewise, deleting the `igconfig.xml` link will allow First-Launch Configuration to start.

![image](https://user-images.githubusercontent.com/20458272/56037414-39571380-5cfd-11e9-9aea-39d20e644245.png)

**Comment by r15ch13** [comment]
Fixed. Please remove the `igconfig.xml` directory from `~/scoop/persist/imageglass` and reinstall it.

**Comment by klutchell** [comment]
works now, thank you!
