### ISSUE TITLE
Unable on install Appium

### ISSUE THREAD

**Issue by Aby-pal** [lukesampson/scoop-extras#2011]
"convertfrom-json: Invalid JSON primitive: ." error message shown for installing appium. Please refer the screenshot for the same. I also have tried to install Maven for a check which got installed successfully. Could you please look into it. Please refer the screenshot for the same.
![scoop_issue](https://user-images.githubusercontent.com/13743176/56082476-dbc6e200-5e36-11e9-9cfe-dfdd781b72b8.png)

**Comment by Ash258** [comment]
You need to use raw URL

**Comment by Aby-pal** [comment]
@Ash258 Thank you for the response.I am new for this stuff. Detailed information would help me to resolve it.

**Comment by Ash258** [comment]
https://raw.githubusercontent.com/lukesampson/scoop-extras/master/bucket/appium.json
