### ISSUE TITLE
keepassxc doesn't persist properly

### ISSUE THREAD

**Issue by f0ff886f** [lukesampson/scoop-extras#2018]
I am not sure what would cause this behaviour, but if you upgrade from KeepassXC 2.4.0 to 2.4.1 with scoop, your persisted ini `keepassxc.ini` will be renamed to `keepassxc.ini.original` (but it will remain as `keepassxc.ini` in the `persist/keepassxc` folder), and a new `keepassxc.ini` will be installed.

The manifest is clearly asking to persist the ini, so I'm not sure what's going on here (is it KeepassXC itself managing the settings?)

**Comment by Ash258** [comment]
This is correct behaviour.
Persist flow on installing update is following:
1. Everything is installed / extracted
1. There is check if something like $env:SCOOP\persist\keepassXC\keepassxc.ini exists
    1. If yes
         1. Check if same file exists inside installation directory
               1. If yes; Move that file to `filename.original` To not lose default configuration shipped with app
               1. Move that file from persist directory into installation directory
               1. Link again to persist directory.

Is there some problem with this configuration file after update?

**Comment by f0ff886f** [comment]
Yes, I lost all settings in the app after upgrade (on the two machines I tested so far).

Moreover, as I look in the actual ini in the `persist/keepassxc` folder, I notice none of my settings pre-update are there (it is a vanilla untouched copy that ships with keepass).

**Comment by Ash258** [comment]
I suspect that Keepass do not edit the file, but they remove and create new one on change. There is need to investigate.

**Comment by hoilc** [comment]
> I suspect that Keepass do not edit the file, but they remove and create new one on change. There is need to investigate.

https://github.com/keepassxreboot/keepassxc/issues/1724

Both safe saving and unsafe saving use file transaction.

**Comment by f0ff886f** [comment]
That 

> 
> 
> > I suspect that Keepass do not edit the file, but they remove and create new one on change. There is need to investigate.
> 
> [keepassxreboot/keepassxc#1724](https://github.com/keepassxreboot/keepassxc/issues/1724)
> 
> Both safe saving and unsafe saving use file transaction.

That is related to the actual password database. I'm speaking about just the configuration settings of the app, stored in `keepassxc.ini`.

**Comment by hoilc** [comment]
> That
> 
> > > I suspect that Keepass do not edit the file, but they remove and create new one on change. There is need to investigate.
> > 
> > 
> > [keepassxreboot/keepassxc#1724](https://github.com/keepassxreboot/keepassxc/issues/1724)
> > Both safe saving and unsafe saving use file transaction.
> 
> That is related to the actual password database. I'm speaking about just the configuration settings of the app, stored in `keepassxc.ini`.

😂

The configuration settings of KeePassXC use QSetting class in which atomic saving is the default behavior. 

Also, KeePassXC doesn't disable it by `setAtomicSyncRequired`.

**Comment by f0ff886f** [comment]
So, upstream bug then? :) Sorry, not that familiar with QT stuff (and workarounds to get file writes like we need them).

**Comment by pigsflew** [comment]
This still appears to be a problem 6 months later, is [Scoop Pull 3212](https://github.com/lukesampson/scoop/pull/3212) still in progress?

In the meantime, I'm going to submit a workaround that follows the pattern of #2756.
