### ISSUE TITLE
flutter is broken due to oraclejdk8

### ISSUE THREAD

**Issue by Anidetrix** [lukesampson/scoop-extras#2036]
Flutter is broken due to oraclejdk8 being removed from the java bucket

**Comment by se35710** [comment]
Oracle Java 8 downloads are behind a pay wall now. Update to another compatible JDK/JRE, for example AdoptOpenJDK.

**Comment by r15ch13** [comment]
@se35710 we should remove the dependencies to `java/oraclejdk8` and just add suggestions:

```json
    "suggest": {
        "JDK": [
            "java/adoptopenjdk-hotspot",
            "java/adoptopenjdk-openj9",
            "java/openjdk"
        ]
    }
```

**Comment by Ash258** [comment]
All java dendents should be suggested. Unless there is imlemented something like:

```json
"depends": {
    "anyof" : "java/*jdk*"
}
```

**Comment by se35710** [comment]
There is also Zulu and Coretto that don't have JDK on their names.

I would propose oraclejdk-lts and openjdk for the normal use cases, and adopt8-hotspot for when there is a specific need for JDK8.
