### ISSUE TITLE
mupdf@1.15.0-rc1: extract_dir error

### ISSUE THREAD

**Issue by alexeiz** [lukesampson/scoop-extras#2072]
mupdf install fails after update to 1.15.0-rc1 with the following output:

```
Installing 'mupdf' (1.15.0-rc1) [64bit]
Loading mupdf-1.15.0-rc1-windows.zip from cache
Checking hash of mupdf-1.15.0-rc1-windows.zip ... ok.
Extracting mupdf-1.15.0-rc1-windows.zip ... ERROR Could not find 'mupdf-1.15.0-rc1-windows'! (error 16)
```

**Comment by ShuguangSun** [comment]
The fiels are extracted to "scoop/apps/mupdf/1.15.0-rc1/_tmp/mupdf-1.15.0-windows" which seems not be recogized.

For example, not "scoop/apps/mupdf/1.15.0-rc1/_tmp/mupdf-1.15.0-rc1-windows"?

**Comment by alexeiz** [comment]
I can't make sense of the last comment.
