### ISSUE TITLE
pandownload@2.1.0: extract_dir error

### ISSUE THREAD

**Issue by skysin** [lukesampson/scoop-extras#2088]
rt

output info:
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'pandownload' (2.1.0) [64bit]
Loading PanDownload_v2.1.0.zip from cache.
Checking hash of PanDownload_v2.1.0.zip ... ok.
Extracting PanDownload_v2.1.0.zip ... ERROR Could not find 'PanDownload_2.1.0'! (error 16)

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=pandownload%402.1.0%3a+extract_dir+error
True

**Comment by ssfjhh** [comment]
Sorry. Fixed by https://github.com/lukesampson/scoop-extras/pull/2089
