### ISSUE TITLE
eagleget-portable@2.0.5.20: hash check failed

### ISSUE THREAD

**Issue by skhe** [lukesampson/scoop-extras#2092]
`scoop install eagleget-portable`
Installing 'eagleget-portable' (2.0.5.20) [64bit]
EagleGetProtable_2.0.5.20.zip (13.8 MB) [>                                   ]   0%
Checking hash of EagleGetProtable_2.0.5.20.zip ... ERROR Hash check failed!
App:         extras/eagleget-portable
URL:         http://dl.eagleget.com/latest/EagleGetProtable_2.0.5.20.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    77c1c1aa178c06dd9a56a6974be6e211aecef5f0
Actual:      c4dc13a74e2f93c648314ce089a8bcb278af1a98

**Comment by Ash258** [comment]
> [> ] 0%

You download failed. `scoop uninstall eagleget-portable; scoop install eagleget-portable`
