### ISSUE TITLE
sourcetree@3.1.2: hash check failed

### ISSUE THREAD

**Issue by vermaakarsh** [lukesampson/scoop-extras#2141]
App:         extras/sourcetree
URL:         https://www.sourcetreeapp.com/update/windows/ga/SourceTree-3.1.2-full.nupkg
First bytes: 50 4B 03 04 14 00 00 00
Expected:    3335af6ddd8c0a378f0dd526b9d065f31bf31a28
Actual:      58724f50f17fc05dcdade81c855813c13ceb6b5c

**Comment by lisxray** [comment]
Maybe your file is broken. I tested the file and the hash is fine.

```
$ sha1sum SourceTree-3.1.2-full.nupkg
3335af6ddd8c0a378f0dd526b9d065f31bf31a28  SourceTree-3.1.2-full.nupkg
```

**Comment by brandon93s** [comment]
The hash is also matching for me:
![image](https://user-images.githubusercontent.com/4730164/57657135-69b5fa00-75a8-11e9-83eb-929178be4a61.png)

Please try reinstalling.

**Comment by vermaakarsh** [comment]
Changing the network fixed it. Works now. Thanks
