### ISSUE TITLE
anydesk@5.0.5: hash check failed

### ISSUE THREAD

**Issue by shzhiqi** [lukesampson/scoop-extras#2149]
App:         extras/anydesk
URL:         https://download.anydesk.com/AnyDesk.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    935c19977ca47ee1224e2ed738b45034a452106f1d661e7835b7f7c0683461b1
Actual:      f3feb653547f1196d7731b3dfaa56588ff32a40f08d016a9f1998262bdef4ac5

**Comment by brandon93s** [comment]
Fixed by https://github.com/lukesampson/scoop-extras/commit/e3a072714943becd6c04d32921c664a7e29cd4a8
