### ISSUE TITLE
[Request] DOSBox Frontends

### ISSUE THREAD

**Issue by indrakaw** [lukesampson/scoop-extras#2162]
See the wiki page here: https://www.dosbox.com/wiki/DOSBoxFrontends ([comparation](https://www.dosbox.com/wiki/Frontend_Comparison))

DOSBox manifest itself is in main bucket. I want a GUI program launcher for DOSBox.

**Comment by Ash258** [comment]
Fixed in 958056cafd0c4170d528864a89199843a0c6b199

**Comment by indrakaw** [comment]
There are other DOSBox Frontends aside DBGL. I wish there are more bucket of it...
