### ISSUE TITLE
github@1.6.6: hash check failed

### ISSUE THREAD

**Issue by CalElFe** [lukesampson/scoop-extras#2177]
Updating 'github' (1.6.5 -> 1.6.6)
Downloading new version
Loading GitHubDesktop-1.6.6-full.nupkg from cache.
Checking hash of GitHubDesktop-1.6.6-full.nupkg ... ERROR Hash check failed!
App:         extras/github
URL:         https://central.github.com/deployments/desktop/desktop/latest/GitHubDesktop-1.6.6-full.nupkg
First bytes: 50 4B 03 04 14 00 00 00
Expected:    c9fbe3bf46bfbcdbc501f6f102121136d8a57fd4
Actual:      154c3e78db0152fc5d258ff2d18862f312cea39a

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=github%401.6.6%3a+hash+check+failed

**Comment by rasa** [comment]
The hash c9fbe3bf46bfbcdbc501f6f102121136d8a57fd4 in the manifest (the “expected” hash above) is correct. Please try again.
