### ISSUE TITLE
Rename pwsh.json into powershell.json

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop-extras#2221]
When running `scoop search powershell`, I expect to find PowerShell. However, the name is `pwsh` in scoop, so I'm made unaware that there's a way to install PowerShell Core via scoop.

I believe it should be renamed to `powershell.json` to facilitate its discovery, even if the command's name is technically `pwsh`.

**Comment by Cologler** [comment]
I agree. PowershellCore is the application name and pwsh just the executable file name.

**Comment by Ash258** [comment]
Manifest is not in Extras bucket
