### ISSUE TITLE
grafana@6.2.1: hash check failed

### ISSUE THREAD

**Issue by rottenjonny88** [lukesampson/scoop-extras#2237]
Installing 'grafana' (6.2.1) [64bit]
Starting download with aria2 ...
Download: [#71e5f4 7.7MiB/51MiB(15%) CN:5 DL:10MiB ETA:4s]
Download: [#71e5f4 18MiB/51MiB(36%) CN:5 DL:10MiB ETA:3s]
Download: [#71e5f4 29MiB/51MiB(58%) CN:5 DL:10MiB ETA:1s]
Download: [#71e5f4 40MiB/51MiB(79%) CN:3 DL:10MiB]
Download: [#71e5f4 50MiB/51MiB(98%) CN:1 DL:10MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 71e5f4|OK  |    10MiB/s|E:/scoop/cache/grafana#6.2.1#https_dl.grafana.com_oss_release_grafana-6.2.1.windows-
amd64.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of grafana-6.2.1.windows-amd64.zip ... ERROR Hash check failed!
App:         extras/grafana
URL:         https://dl.grafana.com/oss/release/grafana-6.2.1.windows-amd64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    f1dd1e2cc9b5bb1d199f1b0b113aec33fa3ca6fad5b5c48173b875c4fbdc41f9
Actual:      19aba43ed8f11c7351d87d7a5fbf41b4e00db915cf3d8e70be8b06fd6bb187e2

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=grafana%406.2.1%3a+hash+check+failed

**Comment by brandon93s** [comment]
Fixed in https://github.com/lukesampson/scoop-extras/commit/3a35b46b2f75222e3e96c6897d7d5d48a8de6dc4.
