### ISSUE TITLE
dbvis app does not work

### ISSUE THREAD

**Issue by rwarren** [lukesampson/scoop-extras#2244]
`scoop install dbvis` installs correctly (see below), but when you try and run it you get "No JVM could be found on your system". The application should be self contained, not require Java knowledge to get it working.

A successful install:
```
>scoop install dbvis
Installing 'dbvis' (10.0.21) [64bit]
dbvis_windows-x64_10_0_21.zip (76.2 MB) [=====================================================================] 100%
Checking hash of dbvis_windows-x64_10_0_21.zip ... ok.
Extracting dbvis_windows-x64_10_0_21.zip ... done.
Linking ~\scoop\apps\dbvis\current => ~\scoop\apps\dbvis\10.0.21
Creating shim for 'dbvis'.
Creating shim for 'dbviscmd'.
Creating shortcut for DbVisualizer (dbvis.exe)
'dbvis' (10.0.21) was installed successfully!
```

What happens when you run it:
![image](https://user-images.githubusercontent.com/2751728/58918401-1f7fee80-86f8-11e9-96b1-3ff3acc5ec86.png)

**Comment by issaclin32** [comment]
scoop installs the program with ZIP file of "without JVM" version, which does not contain JVM.

I think it would be better to choose the "with JVM" version (it will be more stable and less likely to have problems). However, the installer of `dbvis` **modifies Windows Registry** (which is against the general criteria of scoop). 

If we can "crack open" the installer and extract all the required files from it, we can add it to scoop, but the installer is made with `install4j`, and I can't find a way to do that.

![jvm](https://user-images.githubusercontent.com/27724471/60387183-faea1d00-9ad1-11e9-8630-a951c01c10ac.png)

**Comment by linsui** [comment]
If dbvis depends on java, just install java with scoop. And add 

```json
    "suggest": {
        "JDK": [
            "java/oraclejdk",
            "java/openjdk"
        ]
}
```

in manifest.

**Comment by 7wells** [comment]
> However, the installer of `dbvis` **modifies Windows Registry** (which is against the general criteria of scoop).
>
> If we can "crack open" the installer and extract all the required files from it, we can add it to scoop, but the installer is made with install4j, and I can't find a way to do that.

Hello,

I have a similar problem and would like to know how you resolved this. In dbvis.json, I see this:
```
    "extract_dir": "DbVisualizer",
    "bin": [
        "dbvis.exe",
        "dbviscmd.bat"
    ],
```
Is this it? How do you handle Windows registry modifications then? Or are apps that really rely on this, out of scoop's scope?
