### ISSUE TITLE
grafana@6.2.2: hash check failed

### ISSUE THREAD

**Issue by mario8x** [lukesampson/scoop-extras#2250]
App:         extras/grafana
URL:         https://dl.grafana.com/oss/release/grafana-6.2.2.windows-amd64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    bee895c4635c54419c77a1e7694cad96e33a4e9d5657ffee0ae6be53ef30fa57
Actual:      c44ae0019834a73860ba9804965b79235be9284017d716823c316ac6b24abc4f

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=grafana%406.2.2%3a+hash+check+failed

**Comment by brandon93s** [comment]
Autoupdate was pulling the installer hash; now correctly pulls the standalone hash.
