### ISSUE TITLE
[request] Add PotPlayer.

### ISSUE THREAD

**Issue by ssfjhh** [lukesampson/scoop-extras#2251]
PotPlayer is a multimedia software player developed for the Microsoft Windows operating system by South Korean Internet company Kakao (formerly Daum Communications).
site:<https://potplayer.daum.net/>

**Comment by Ash258** [comment]
https://github.com/Ash258/scoop-Ash258/blob/master/bucket/PotPlayer.json

Anyone feel free to port this. I think generic manifest do not need that customized Settings

**Comment by ssfjhh** [comment]
Sorry.

**Comment by Ash258** [comment]
Why closing?

I would do it myself, but I do not have time to do that now. Reopen this issue and hopefully someone will port it before I found time to do it myself.
