### ISSUE TITLE
Should official buckets allow downloads from non-official sites?

### ISSUE THREAD

**Issue by vmvmpvm** [lukesampson/scoop-extras#2278]
I was trying to download Orca, its description and all looks good, but when I tried installing it, the download is actually from a personal site.

By reading the description I was under impression it was a direct download from Microsoft website.

Should official Sccop buckets allow links to personal websites for file downloads? Isn't it a security risk?

**Comment by rasa** [comment]
We extracted the file, and host it on our secure server, as Orca’s [homepage](https://docs.microsoft.com/en-us/windows/desktop/Msi/orca-exe) says:
This tool is only available in the Windows SDK Components for Windows Installer Developers. It is provided as an Orca.msi file. After installing the Windows SDK Components for Windows Installer Developers, double click Orca.msi to install the Orca.exe file.

**Comment by vmvmpvm** [comment]
Thanks @rasa, is there a policy that is followed to validate download URLs while approving new manifests?

Should Scoop have a repository for binaries that need to be staged for reasons like this?

Regarding Orca
I used Fiddler and got below URL, is this useful by chance?

https://download.microsoft.com/download/4/2/2/42245968-6A79-4DA7-A5FB-08C0AD0AE661/windowssdk/Installers/Orca-x86_en-us.msi

**Comment by vmvmpvm** [comment]
In addition can I propose below

1. Display the download URL while downloading.
2. Add a flag to manifest to indicate if download source is from the author or a staged one? And may be prompt user to confirm download if source is not from author?
