### ISSUE TITLE
slack@3.4.3: hash check failed

### ISSUE THREAD

**Issue by ishanarora** [lukesampson/scoop-extras#2281]
Updating 'slack' (3.4.2 -> 3.4.3)                                                                                       Downloading new version                                                                                                 slack-3.4.3-full.nupkg (78.1 MB) [============================================================================] 100%    Checking hash of slack-3.4.3-full.nupkg ... ERROR Hash check failed!                                                    App:         extras/slack                                                                                               URL:         https://downloads.slack-edge.com/releases_x64/slack-3.4.3-full.nupkg                                       First bytes: 50 4B 03 04 14 00 00 00                                                                                    Expected:    55848e9328049629f565cbe06c81ea495e83a6bd                                                                   Actual:      8c0c53aa15e1c2ceab739a93407abea1574bf3ea

**Comment by rasa** [comment]
Fixed in #2286
