### ISSUE TITLE
defraggler@2.22.995: hash check failed

### ISSUE THREAD

**Issue by tnotstar** [lukesampson/scoop-extras#2326]
While trying to install **defraggler**, check of the hash code from downloaded file has beed failed.  After investigation the download url has beed changed from **www.piriform.com** to **www.ccleaner.com**.

**Comment by tnotstar** [comment]
This looks as duplicate of issue #2272

**Comment by rasa** [comment]
The hash 2edfa974fc2e8e34c0b8c152077da9c3a4ab28cad81a4ced463f0cf6634a0f01 in the manifest (the “expected” hash above) is correct. Please try again.
