### ISSUE TITLE
Firefox and Firefox-ESR checkver

### ISSUE THREAD

**Issue by linsui** [lukesampson/scoop-extras#2340]
Firefox and Firefox-ESR are downgrade to 67.0.2 and 60.7.0 several times. Is this an upstream bug?

**Comment by rasa** [comment]
See https://github.com/lukesampson/scoop-extras/search?p=1&q=Firefox-esr&type=Commits

**Comment by r15ch13** [comment]
If the website is served with AB-Testing then there is nothing we can do about it.
Or we use the update API mentioned @Skrity https://github.com/lukesampson/scoop-extras/pull/2124#issuecomment-496871239

**Comment by linsui** [comment]
So should we fix it? If it caused by AB-Testing, it seems that the test has stopped...

**Comment by wenmin92** [comment]
This problem still exists, `68.0.1` and `68.0.2` frequent switching.
See https://github.com/lukesampson/scoop-extras/search?q=Firefox&type=Commits&s=committer-date&o=desc
why not use https://www.mozilla.org/en-US/firefox/notes/ for checkver?
