### ISSUE TITLE
listen1desktop extraction error

### ISSUE THREAD

**Issue by qcts33** [lukesampson/scoop-extras#2355]
```
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find '$PLUGINSDIR'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find '$PLUGINSDIR'! (error 16)
```
I checked that the cached .7z file does have a dir named `$PLUGINSDIR`. No idea what's wrong

**Comment by D-W-X** [comment]
I have seen it.
You can do as this:
1.find your extras bucket locally,
2.open listen1desktop.json
3.line 22 ： “     "extract_dir": "\\$PLUGINSDIR", ” ————> “    "extract_dir": "$PLUGINSDIR",” change as this
4.reinstall
