### ISSUE TITLE
cpu-z@1.89: hash check failed

### ISSUE THREAD

**Issue by Sion10032** [lukesampson/scoop-extras#2360]
App:         extras/cpu-z
URL:         http://download.cpuid.com/cpu-z/cpu-z_1.89-en.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    ee81ff235de6c94460f264e875fbe6d4c0d1cf1e21cd996fe1fafa59440146d4
Actual:      2567e1b039cc358a1447cfff1170dff42b19b89d8d37b97dd939ee179106494f

**Comment by rasa** [comment]
Fixed in #2364
