### ISSUE TITLE
Could you please add ccl (Clozure Common Lisp)

### ISSUE THREAD

**Issue by priyadarshan** [lukesampson/scoop-extras#2401]
[Clozure Common Lisp](https://ccl.clozure.com/) is an advanced and free Common Lisp implementation.

Windows XP and later (x86, x86-64) executable is here:
https://github.com/Clozure/ccl/releases.

Filename says x86, but zip file includes 64-bit.

Thank you!

**Comment by linsui** [comment]
As this is a command line tool, you could report issue in main bucket https://github.com/ScoopInstaller/Main

**Comment by priyadarshan** [comment]
Done, thank you for letting me know.
