### ISSUE TITLE
Libreoffice Fresh

### ISSUE THREAD

**Issue by omerakgoz34** [lukesampson/scoop-extras#2417]
libreoffice-fresh.json is correct but scoop is not able to download

**Comment by omerakgoz34** [comment]
Installing 'libreoffice-fresh' (6.2.5.2) [64bit]
The remote server returned an error: (302) Found.
URL https://downloadarchive.documentfoundation.org/libreoffice/old/6.2.5.2/win/x86_64/LibreOffice_6.2.5.2_Win_x64.msi is not valid

**Comment by Ash258** [comment]
Problem with your ISP or proxy 

![A](https://i.imgur.com/yK9tQdL.png)
![image](https://user-images.githubusercontent.com/13260377/60724773-939bf500-9f37-11e9-8fe1-0ff3429cfaa2.png)

**Comment by omerakgoz34** [comment]
@Ash258
I can download with chrome but I can't download with scoop

**Comment by linsui** [comment]
Is it a http mirror link?
https://github.com/ScoopInstaller/Main/pull/123#issuecomment-500809638
https://downloadarchive.documentfoundation.org/libreoffice/old/6.2.5.2/win/x86_64/LibreOffice_6.2.5.2_Win_x64.msi.mirrorlist

**Comment by omerakgoz34** [comment]
json file is saved as https but when I make http download is successful
