### ISSUE TITLE
lightshot

### ISSUE THREAD

**Issue by omerakgoz34** [lukesampson/scoop-extras#2418]
WARN  This is a nightly version. Downloaded files won't be verified.
Installing 'lightshot' (nightly-20190705) [64bit]
Downloading https://app.prntscr.com/build/setup-lightshot.exe (-1 B)...

Extracting setup-lightshot.exe ... done.
Linking ~\scoop\apps\lightshot\current => ~\scoop\apps\lightshot\nightly-20190705
Creating shim for 'Lightshot'.
Can't shim 'Lightshot.exe': File doesn't exist.

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop-extras/pull/2388
