### ISSUE TITLE
how to update flutter bucket

### ISSUE THREAD

**Issue by chatterzhao** [lukesampson/scoop-extras#2439]
how to update flutter bucket

**Comment by issaclin32** [comment]
You mean the `flutter` **package** under "extras" bucket?

Try `scoop update flutter`
(or `scoop update flutter -f` if you want to force re-install.)

**Comment by chatterzhao** [comment]
> You mean the `flutter` **package** under "extras" bucket?
> 
> Try `scoop update flutter`
> (or `scoop update flutter -f` if you want to force re-install.)

Sorry, i want update manifest(我想学习怎么升级flutter.json)

**Comment by rikuben** [comment]
Change the checkver regex from `"windows_v([\\w-.]+)-stable"` to `"windows_v([\\w+-.]+)-stable"`.
Then, run `.\bin\checkver.ps1 flutter -u`

**Comment by chatterzhao** [comment]
@rikuben 
thanks


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
