### ISSUE TITLE
[request] Add DiskGenius.

### ISSUE THREAD

**Issue by ssfjhh** [lukesampson/scoop-extras#2440]
DiskGenius is an excellent utility that comes packed with various useful features on data recovery, disk partition management, backup & restore.
website:http://www.diskgenius.cn/

**Comment by ssfjhh** [comment]
I have tried to add it by myself. But I found that the latest version is **5.1.2**. But the URL is http://download.eassos.cn/DG512766_x64.zip. I don't know how to deal with it.

**Comment by linsui** [comment]
You can use `$cleanVersion` . See https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#version-variables

**Comment by ssfjhh** [comment]
> The version is 5.1.2.766. You can use `$cleanVersion` . See https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#version-variables

Thank you.

**Comment by keygen-maker** [comment]
Disk Genius Activation Key is a powerful tool for data recovery, partitioning and partitioning, as it offers a lot of features. The free edition offers various parts for repairing parts and discs and recovering lost files for home and business users.
Deborah
keygenbro.com
