### ISSUE TITLE
how to write a manifest file?

### ISSUE THREAD

**Issue by chatterzhao** [lukesampson/scoop-extras#2448]
我是刚入门，看别人写的 bucket 下的manifest看不懂，我想升级一下extras/flutter这个manifest,哪位朋友能帮我写一下flutter.json的注释吗？
I'm just getting started. I can't read the manifest under the bucket written by others. I want to upgrade the manifest of extras/flutter. Can any friend help me write the notes of flutter.json?

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by linsui** [comment]
你可以阅读文档 https://github.com/lukesampson/scoop/wiki

**Comment by chatterzhao** [comment]
@linsui  谢谢


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
