### ISSUE TITLE
vscode-insiders@nightly: decompress error

### ISSUE THREAD

**Issue by wizofe** [lukesampson/scoop-extras#2451]
xxx@xxx D:\Linux\   master ≣                                                                                    [16:14]
❯ scoop install vscode-insiders
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  This is a nightly version. Downloaded files won't be verified.
Installing 'vscode-insiders' (nightly-20190713) [64bit]
Loading dl.7z from cache.
Loading vscode-install-context.reg from cache.
Loading vscode-uninstall-context.reg from cache.
Extracting dl.7z ...
ERRORS:
Headers Error
Unconfirmed start of archive

ERROR: Data Error : Code - Insiders.exe
ERROR Exit code was 2!
Failed to extract files from D:\Windows\Software\scoop\apps\vscode-insiders\nightly-20190713\dl.7z.
Log file:
  D:\Windows\Software\scoop\apps\vscode-insiders\nightly-20190713\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=vscode-insiders%40nightly%3a+decompress+error

**Comment by wizofe** [comment]
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 76762599 bytes (74 MiB)

Extracting archive: D:\Windows\Software\scoop\apps\vscode-insiders\nightly-20190713\dl.7z

WARNINGS:
There are data after the end of archive

WARNING:
D:\Windows\Software\scoop\apps\vscode-insiders\nightly-20190713\dl.7z
Can not open the file as [7z] archive
The file is open as [zip] archive

--
Path = D:\Windows\Software\scoop\apps\vscode-insiders\nightly-20190713\dl.7z
Open WARNING: Can not open the file as [7z] archive
Type = zip
ERRORS:
Headers Error
Unconfirmed start of archive
WARNINGS:
There are data after the end of archive
Physical Size = 38513101
Tail Size = 38249498
Characteristics = Local


Sub items Errors: 1

Archives with Errors: 1

Warnings: 1

Open Errors: 1

Sub items Errors: 1

**Comment by issaclin32** [comment]
It worked fine on my PC. Looks like it's a connection issue.

You can run `scoop update vscode-insiders -f --no-cache` to force re-install without using the possibly corrupted cached file.

**Comment by rasa** [comment]
Worked for me, please try again. If this is still an issue, please reopen this. Thanks!
