### ISSUE TITLE
mp3tag@2.97: hash check failed

### ISSUE THREAD

**Issue by bGraebener** [lukesampson/scoop-extras#2469]
mp3tag: 2.96 -> 2.97
Updating one outdated app:
Updating 'mp3tag' (2.96 -> 2.97)
Downloading new version
mp3tagv297setup.exe (3,4 MB) [===========================================================================================================================] 100%
Checking hash of mp3tagv297setup.exe ... ERROR Hash check failed!
App:         extras/mp3tag
URL:         https://download.mp3tag.de/mp3tagv297setup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    30880ae7a39ce952bd3ed7bf731ada26ce426d4888b75e8566e5fbbcd21823bd
Actual:      39fad93915f43af3cf69b61f1735837fdfd8a36c9e00765d795a0e397df06bc3

**Comment by rasa** [comment]
Fixed in #2461
