### ISSUE TITLE
gcc-arm-none-eabi@8-2019-q3-updsh check failed

### ISSUE THREAD

**Issue by BlueHeaven1969** [lukesampson/scoop-extras#2479]
```
App:         extras/gcc-arm-none-eabi
URL:         https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/gcc-arm-none-ea
-q3-update-win32.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    5fa382a547abe0b0d5c0a6e9eaa75c7b
Actual:      a741af7570ae4a56e86e551652e6c365

**Comment by strmpnk** [comment]
It's concerning that the download page lists the original MD5 sum still as well: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

Unless someone can contact ARM or reproduce the build, it seems risky to accept the new hash blindly (not that MD5 is much security but still).
