### ISSUE TITLE
sysinternals@February.18.2019: hash check failed

### ISSUE THREAD

**Issue by DeezCashews** [lukesampson/scoop-extras#2498]
```powershell
> scoop update sysinternals
```

> sysinternals: February.13.2018 -> February.18.2019
> Updating one outdated app:
> Updating 'sysinternals' (February.13.2018 -> February.18.2019)
> Downloading new version
> SysinternalsSuite.zip (25.5 MB) [========================================================================================================] 100%
> Checking hash of SysinternalsSuite.zip ... ERROR Hash check failed!
> App:         extras/sysinternals
> URL:         https://download.sysinternals.com/files/SysinternalsSuite.zip
> First bytes: 50 4B 03 04 14 00 00 00
> Expected:    cf9df1ed2782bb0f7da3648f8ef732ae017f044d641705f61633fce6453a3fec
> Actual:      db59efe1739a2262104874347277f9faa0805a1a7a0acd9cc29e9544fb8040c5

**Comment by niheaven** [comment]
`scoop update` then `scoop update sysinternals`, it is updated to June.28.2019

**Comment by DeezCashews** [comment]
I had done that before but it turns out to be my fault.  I didn't realize my extras bucket was corrupt so it was refusing to update.  `scoop bucket rm extras` and `scoop bucket add extras` got me back in working order.
