### ISSUE TITLE
[Request] Adobe Flash Player Standalone

### ISSUE THREAD

**Issue by indrakaw** [lukesampson/scoop-extras#2533]
Main page: https://labs.adobe.com/downloads/flashplayer.html

Windows 32-bit executable: https://fpdownload.macromedia.com/pub/labs/flashruntimes/flashplayer/flashplayer_32_sa.exe

It doesn't have 64-bit exec on Windows and Mac.

A menu shortcut is fine too.

**Comment by KnotUntied** [comment]
The debug version as well?

**Comment by indrakaw** [comment]
Debug version is fine too.
