### ISSUE TITLE
calibre-portable path error

### ISSUE THREAD

**Issue by danalec** [lukesampson/scoop-extras#2535]
"Path to Calibre Portable too long. Must be less than 59 characters"
![calibre-portable-installer-3 46 0_Ucpo3YmBGo](https://user-images.githubusercontent.com/2339131/62143701-dfd41e00-b2c6-11e9-98b1-bb1a580faed0.png)

**Comment by linsui** [comment]
See https://www.mobileread.com/forums/showthread.php?t=142913

**Comment by Ash258** [comment]
#1765

**Comment by 7wells** [comment]
Hi, I (still) have the same problem. Maybe removing the portable version of Calibre from this bucket is better than letting users run into this problem and repeating the same comments (like me, blush). Or does it work for somebody?

See there:
https://github.com/lukesampson/scoop-extras/issues/1765

**Comment by linsui** [comment]
Yep, you can install scoop to e.g. `D:/scoop` .

**Comment by 7wells** [comment]
Ah, but that involves placing scoop and all apps to another and shorter path. If no other drive is available, then maybe scoop could be installed directly to C:\scoop? Still, without any further explanation in the install process of the portable Calibre version, it will confuse more users. Maybe the json file could be amended to offer some help, e.g. by proposing a shorter installation path? Is it possible to have only Calibre installed somewhere else while keeping everything else as per scoop standard?

**Comment by linsui** [comment]
> Is it possible to have only Calibre installed somewhere else while keeping everything else as per scoop standard?

You can write a custom manifest and install it to anywhere you like.

**Comment by 7wells** [comment]
Indeed I could (try) doing it, but most of the users might not know how. Please accept my apologies if I wrongly assumed that the apps offered in this bucket work "out of the box" (understanding quite well that the maintainer/contributors do this all in their free time, for which I am very grateful). I just thought that many average users might unnecessarily stumble over this. If this remains as it is, it is perfectly fine with me, and I am still happy with scoop and this bucket. Currently, I use the "normal" Calibre from this bucket without any problems. 👍

**Comment by DOFfactory** [comment]
Same issue here with the latest version of scoop

**Comment by rashil2000** [comment]
With calibre or calibre-normal?

**Comment by gigberg** [comment]
update: you could set windows long path option by regedit. then calibre portable work properly.
https://learn.microsoft.com/zh-cn/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell

**Comment by VitaliyAT** [comment]
Other programs do not need it at all. Could you fix this problem inside Calibrie and not inside OS? Aspecially needed for portable version. It's so funny hear about problem with "path long" in 2025 year...

**Comment by NastyFlytrap** [comment]
I genuinely dont understand why in 2026 its even limited. Just raise it to 256 at minimum or remove it altogether. Why does this exist?!

Yes, i have set long paths in windows already and everything else works. Its calibre itself that doesnt.

Edit: I'm trying to use calibre portable.
