### ISSUE TITLE
dnsjumper@2.1: hash check failed

### ISSUE THREAD

**Issue by CharleyMorgan** [lukesampson/scoop-extras#2634]
下载后出现
Download: (OK):download completed.
Checking hash of DnsJumper.zip ... ERROR Hash check failed!
App:         extras/dnsjumper
URL:         https://www.sordum.org/files/dns-jumper/DnsJumper.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    50c7c9ab74612799e6be2a171aa472f187f018770b52125aa23101e8714a170c
Actual:      cda54464b4bae794eba9deaf0505621397fc9592b9f34795baaf6f322f0ae7ea

**Comment by r15ch13** [comment]
Closed via https://github.com/lukesampson/scoop-extras/pull/2633
