### ISSUE TITLE
altair@2.3.0: download via aria2 failed

### ISSUE THREAD

**Issue by tryyoung** [lukesampson/scoop-extras#2671]
Download: 08/16 16:42:56 [ERROR] CUID#8 - Download aborted. URI=https://github.com/imolorhe/altair/releases/download/v2.3.0/altair-setup-2.3.0.exe#/dl.7z
Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://github.com/imolorhe/altair/releases/download/v2.3.0/altair-setup-2.3.0.exe
Download:   -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 486971|ERR |       0B/s|C:/Users/Mingpeng/scoop/cache/altair#2.3.0#https_github.com_imolorhe_altair_releases_download_v2.3.0_altair-setup-2.3.0.exe_dl.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/imolorhe/altair/releases/download/v2.3.0/altair-setup-2.3.0.exe#/dl.7z
    referer=https://github.com/imolorhe/altair/releases/download/v2.3.0/altair-setup-2.3.0.exe#/
    dir=C:\Users\Mingpeng\scoop\cache
    out=altair#2.3.0#https_github.com_imolorhe_altair_releases_download_v2.3.0_altair-setup-2.3.0.exe_dl.7z

ERROR & 'C:\Users\Mingpeng\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Mingpeng\scoop\cache\altair.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=19088 --continue

**Comment by imolorhe** [comment]
Hey, could you try again?

**Comment by tryyoung** [comment]
Works now. Thanks a lot!
