### ISSUE TITLE
locale-emulator@2.4.1.0: Can't shim 'LEGUI.exe': File doesn't exist.

### ISSUE THREAD

**Issue by Semidio** [lukesampson/scoop-extras#2679]
Installing 'locale-emulator' (2.4.1.0) [64bit]
Loading Locale.Emulator.2.4.1.0.zip from cache.
Checking hash of Locale.Emulator.2.4.1.0.zip ... ok.
Extracting Locale.Emulator.2.4.1.0.zip ... done.
Running pre-install script...
Linking ~\scoop\apps\locale-emulator\current => ~\scoop\apps\locale-emulator\2.4.1.0
Creating shim for 'Locale-Emulator'.
Can't shim 'LEGUI.exe': File doesn't exist.

**Comment by Semidio** [comment]
2.4.1.0/:
Locale.Emulator.2.4.1.0

2.4.1.0/Locale.Emulator.2.4.1.0:
Alternative Dlls.zip
Lang
LEGUI.exe
LEInstaller.exe
LEProc.exe
LEUpdater.exe
LEVersion.xml
LoaderDll.dll
LocaleEmulator.dll

2.4.1.0/Locale.Emulator.2.4.1.0/Lang:
ca.xaml
ca.xml
DefaultLanguage.xaml
DefaultLanguage.xml
de.xaml
de.xml
es.xaml
es.xml
fr.xaml
fr.xml
ind.xaml
ind.xml
it.xaml
it.xml
ja.xaml
ja.xml
ko.xaml
ko.xml
lt.xaml
lt.xml
nb.xaml
nb.xml
nl.xaml
nl.xml
pl.xaml
pl.xml
pt-BR.xaml
pt-BR.xml
ru.xaml
ru.xml
th.xaml
th.xml
tr-TR.xaml
tr-TR.xml
zh-CN.xaml
zh-CN.xml
zh-HK.xaml
zh-HK.xml
zh-TW.xaml
zh-TW.xml

**Comment by issaclin32** [comment]
Being fixed in #2614.

**Comment by rasa** [comment]
Fixed in #2674.
