### ISSUE TITLE
v2rayn does not need to depend on v2ray

### ISSUE THREAD

**Issue by LaelLuo** [lukesampson/scoop-extras#2698]
Because it already contains v2ray-core

**Comment by Ash258** [comment]
@linsui

**Comment by linsui** [comment]
Yeah, there is two binaries, one contains v2ray core and the other not. I prefer to use the official v2ray core and maintain v2ray core with scoop, so we can keep v2ray core and gui up to date. And if someone want to ust both of them they don't need to download the v2ray core twice.

**Comment by Retia-Adolf** [comment]
However when updating v2rayn, `v2ray-core` won't be updated together, you must manually run `scoop update v2rayn v2ray` `scoop update *`

**Comment by linsui** [comment]
They have different update cycle. v2rayN updates about once a week but v2ray updates once a month. So I prefer to update them separately instead of download v2ray core everytime(900K and 15M). As v2rayN can update v2ray core and itself, maybe you can install v2rayN with scoop but update it with itself?

**Comment by LaelLuo** [comment]
So can v2rayN with v2ray-core not be used?

**Comment by LaelLuo** [comment]
So can I use a source that doesn't have v2ray-core? I don't want to store two v2ray-cores.

**Comment by linsui** [comment]
We do use the v2rayn without v2ray core. We install v2ray and create a hardlink in v2rayn's directory.

**Comment by LaelLuo** [comment]
Oh, sorry.I thought it was the version with v2ray-core and v2ray-core was installed again.

**Comment by hueyless** [comment]
> We do use the v2rayn without v2ray core. We install v2ray and create a hardlink in v2rayn's directory.

I don't  think so, no hardlink appears under win10.

**Comment by linsui** [comment]
@hueyless Does it works for you?
