### ISSUE TITLE
scoop install mkcert, download url is not valid in window

### ISSUE THREAD

**Issue by houchaowei** [lukesampson/scoop-extras#2724]
when i run
```
scoop install mkcert
```
in window shell .
and i dot know what should i do after this

**Comment by houchaowei** [comment]
![image](https://user-images.githubusercontent.com/17643027/63570296-31fb1d00-c5af-11e9-87a1-9628d40b1354.png)

**Comment by houchaowei** [comment]
anyone else knows how to solve this

**Comment by issaclin32** [comment]
It works fine for me. Maybe just a connection issue?

Please try installing it again.
If it still fails, see if you can visit https://github.com/FiloSottile/mkcert/releases/download/v1.4.0/mkcert-v1.4.0-windows-amd64.exe correctly.

![mkcert](https://user-images.githubusercontent.com/27724471/63572158-be5c0e80-c5b4-11e9-9ae3-e0ddafcd4ac6.png)
