### ISSUE TITLE
[Request] Add ONLYOFFICE Desktop Editors

### ISSUE THREAD

**Issue by gothicx** [lukesampson/scoop-extras#2742]
Hi,

There is not yet a 32-bit portable edition. There is no way to check the current version of this .zip file, even from their downloads website, there is no public portable edition. I'll try to have the authors to provide them in a more consistent way.

onlyoffice.json

```json
{
    "version": "5.3.95.506",
    "license": "AGPLv3",
    "url": "http://repo-doc-onlyoffice-com.s3-eu-west-1.amazonaws.com/windows/onlyoffice-desktopeditors/latest/DesktopEditors_x64.zip",
    "hash": "md5:d51fba54a99ada0f8cbbe44a5cdde261",
    "homepage": "https://www.onlyoffice.com/apps.aspx",
    "bin": "DesktopEditors.exe",
    "shortcuts": [
        [
            "DesktopEditors.exe",
            "ONLYOFFICE Desktop Editors 5.3"
        ]
    ]
}
```

**Comment by linsui** [comment]
Where do you find it? Is there any difference between .zip and .exe?

**Comment by gothicx** [comment]
Hi. I found it at https://github.com/ONLYOFFICE/DesktopEditors/issues/151, it seems this zip is actually a more recent version.

The exe file at https://www.onlyoffice.com/download-desktop.aspx is version 5.3.95.61

**Comment by linsui** [comment]
I thought we should wait for a public release. Is this a portable version?

> A "portable" version was for #31, which means that settings are saved to the local folder.

If you don't care about this, you can just use the exe file. As a note, I'm waiting for this https://github.com/ONLYOFFICE/DesktopEditors/issues/245 .

**Comment by gothicx** [comment]
The scoop can install .exe files ? I thought it only work for msi and zip.

I used that json file to install it in my machine and it actually works, so it's portable.

**Comment by linsui** [comment]
Yes, of course! The exe file can be unpack with 7zip. Just need to rename them as .7z file and scoop will unpack them. Such as

```
"url": "https://github.com/ONLYOFFICE/DesktopEditors/releases/download/ONLYOFFICE-DesktopEditors-5.3.3/DesktopEditors_x64.exe#/dl.7z"
```

**Comment by gothicx** [comment]
It seems it doesn't work for Inno Setup installers. I have made a new scoop manifest that you can see attached.
[onlyoffice.txt](https://github.com/lukesampson/scoop-extras/files/3554369/onlyoffice.txt)

**Comment by linsui** [comment]
> innosetup: set to the boolean true (without quotes) if the installer is InnoSetup based.

**Comment by gothicx** [comment]
It worked just great. I'll do a pull request to scoop-extras. Thanks :)
