### ISSUE TITLE
vlc@3.0.8: hash check failed

### ISSUE THREAD

**Issue by teppos** [lukesampson/scoop-extras#2748]
I get the following error message when trying to install VLC

Checking hash of vlc-3.0.8-win64.7z ... ERROR Hash check failed!
App:         extras/vlc
URL:         https://download.videolan.org/pub/vlc/3.0.8/win64/vlc-3.0.8-win64.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    0e783f6d60100e10b17e135479ffd1b5ecf8acfb76c10e0f58da29f6132fc603
Actual:      3ed0c4e47ccfd2dc296a4170d5c73bb3222f91da10ae46da6334d7a7454c5a9f

**Comment by gothicx** [comment]
Here it works fine.

**Comment by rasa** [comment]
The hash 0e783f6d60100e10b17e135479ffd1b5ecf8acfb76c10e0f58da29f6132fc603 in the manifest (the “expected” hash above) is correct. Please try again.
