### ISSUE TITLE
Cannot start chromium

### ISSUE THREAD

**Issue by eheintzmann** [lukesampson/scoop-extras#2779]
After installing chromium 76.0.3809.100-r665002 (`scoop intall chromium`), the commands `chrome.exe` and  `chromium.exe` do not work (on _cmd_ or _powershell_, they do nothing, but with _git bash_ there is a segmentation fault).
And double clicking on the chromium icon (in Scoop Apps), do nothing too

**Comment by linsui** [comment]
I can't reproduce it. Please try `scoop reset chromium` or reinstall it.

**Comment by eheintzmann** [comment]
I've tried `scoop reset chromium` and reinstall it.
It still does not work

**Comment by eheintzmann** [comment]
I've tried to run chrome with windbg:
there is an Access violation - code c0000005

**Comment by issaclin32** [comment]
I cannot reproduce the problem either.

It might be related with plugins or extensions.
You can try running `chromium --disable-extensions --disable-plugins` and see if it solves the problem.

**Comment by eheintzmann** [comment]
No changes with `chromium --disable-extensions --disable-plugins`

**Comment by eheintzmann** [comment]
You are right:
64bit doesn't work but 32bit version works fine.

**Comment by tratTalks** [comment]
close this now?
---

cheers tratTalks
