### ISSUE TITLE
sharex v13 is out

### ISSUE THREAD

**Issue by ramgp** [lukesampson/scoop-extras#2820]
The new version of sharex is out
https://github.com/ShareX/ShareX/releases/tag/v13.0.1

**Comment by equinox** [comment]
It looks like the [ShareX manifest](https://github.com/lukesampson/scoop-extras/blob/master/bucket/sharex.json) is already updated to the latest version, no?

**Comment by ramgp** [comment]
yes it is, there was an error with extras bucket for me
