### ISSUE TITLE
smartgit@19.1.3: hash check failed

### ISSUE THREAD

**Issue by warmingking** [lukesampson/scoop-extras#2844]
![image](https://user-images.githubusercontent.com/14056172/64904992-80aa5b80-d704-11e9-8a0f-4410431cdd53.png)
smartgit HASH check failed

**Comment by diseq** [comment]
Download: (OK):download completed.
Checking hash of smartgit-portable-19_1_3.7z ... ERROR Hash check failed!
App:         extras/smartgit
URL:         https://www.syntevo.com/downloads/smartgit/smartgit-portable-19_1_3.7z
First bytes: 37 7A BC AF 27 1C 00 03
Expected:    235aee14920662b835349ae488200aae5083d7d2
Actual:      f7ff82fb53d06a724984e9c2818e94895d14aa6a

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=smartgit%4019.1.3%3a+hash+check+failed

**Comment by brandon93s** [comment]
Fixed in https://github.com/lukesampson/scoop-extras/commit/6c4d6bcc66dd6b1c1963c7e082686dc2c563e04e
