### ISSUE TITLE
postman@7.7.1: download via aria2 failed

### ISSUE THREAD

**Issue by devhawk** [lukesampson/scoop-extras#2849]
PS> scoop update *
postman: 7.6.0 -> 7.7.1
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Updating one outdated app:
Updating 'postman' (7.6.0 -> 7.7.1)
Downloading new version
Starting download with aria2 ...
Download: 09/15 11:22:58 [ERROR] CUID#8 - Download aborted. URI=https://dl.pstmn.io/download/7.7.1/Postman-win64-7.7.1-full.nupkg#/dl.7z
Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://dl.pstmn.io/download/7.7.1/Postman-win64-7.7.1-full.nupkg
Download:   -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 666589|ERR |       0B/s|C:/Users/harry/scoop/cache/postman#7.7.1#https_dl.pstmn.io_download_7.7.1_Postman-win64-7.7.1-full.nupkg_dl.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR https://dl.pstmn.io/download/7.7.1/Postman-win64-7.7.1-full.nupkg#/dl.7z
    referer=https://dl.pstmn.io/download/7.7.1/Postman-win64-7.7.1-full.nupkg#/
    dir=C:\Users\harry\scoop\cache
    out=postman#7.7.1#https_dl.pstmn.io_download_7.7.1_Postman-win64-7.7.1-full.nupkg_dl.7z

ERROR & 'C:\Users\harry\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\harry\scoop\cache\postman.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=21324 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=postman%407.7.1%3a+download+via+aria2+failed

**Comment by devhawk** [comment]
uninstalled postman, disabled aria

PS> scoop install postman
Installing 'postman' (7.7.1) [64bit]
The remote server returned an error: (404) Not Found.
URL https://dl.pstmn.io/download/7.7.1/Postman-win64-7.7.1-full.nupkg#/dl.7z is not valid

**Comment by SF97** [comment]
Looks like postman is still in version 7.6.0, not 7.7.1
https://www.getpostman.com/downloads/

**Comment by Ash258** [comment]
It was fixed on their end few days after issue was opened. New release is available for installation
