### ISSUE TITLE
bucket list update

### ISSUE THREAD

**Issue by dajiugo** [lukesampson/scoop-extras#2853]

**Comment by dajiugo** [comment]
1. keepass latest edition : 2.43
2. vscode latest edition : 1.38

**Comment by Ash258** [comment]
I really do not know what are you talking about....

Vscode is currently at 1.38.1 
- https://github.com/lukesampson/scoop-extras/blob/master/bucket/vscode-portable.json
- https://github.com/lukesampson/scoop-extras/blob/master/bucket/vscode.json

Keepass is at 2.43
https://github.com/lukesampson/scoop-extras/blob/master/bucket/keepass.json

**Comment by dajiugo** [comment]
sorry,
no updates to use "scoop update"

I deleted scoop-extras and reinstall
it's really updated
