### ISSUE TITLE
switchhosts@3.4.0: hash check failed

### ISSUE THREAD

**Issue by mayongze** [lukesampson/scoop-extras#2889]
![image](https://user-images.githubusercontent.com/22066360/65672955-809f4980-e07c-11e9-9140-c991fc3710d2.png)

**Comment by rasa** [comment]
The hash in the manifest (9cf0901d733fdd2ad6b00a2de9ff97b3c230e8a0616da83fa487ab33970e5c1b) is correct. Please try again.r
