### ISSUE TITLE
brackets@1.14: decompress error

### ISSUE THREAD

**Issue by loong95** [lukesampson/scoop-extras#2915]
```
=== Logging started: 2019/9/30  16:44:13 ===
Error 1320. The specified path is too long: C:\Users\linyunlong\scoop\apps\brackets\1.14\_tmp\SourceDir\Brackets\www\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan
=== Logging stopped: 2019/9/30  16:44:32 ===
```

**Comment by Ash258** [comment]
Cannot reproduce. Even with my shorter base path I should hit this limitation. Make sure you have long path support enabled.

Run `scoop checkup` and you should get information about how to enable long path support.

![image](https://user-images.githubusercontent.com/13260377/67625869-488a5280-f844-11e9-848f-71aa1ddd7816.png)

**Comment by ratatoeey** [comment]
its been so long, loong95, any response would be welcome. is the issue resolved?

---
regards ratatoeey

**Comment by loong95** [comment]
@Ash258 @ratatoeey 
Sorry for taking so long to reply. "Win32 long paths" is enabled but it is still fail to install “brackets”.
```cmd
Installing 'brackets' (1.14) [64bit]
Loading Brackets.Release.1.14.msi from cache
Checking hash of Brackets.Release.1.14.msi ... ok.
Extracting Brackets.Release.1.14.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\linyunlong\scoop\apps\brackets\1.14\Brackets.Release.1.14.msi.
Log file:
  ~\scoop\apps\brackets\1.14\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=brackets%401.14%3a+decompress+error

C:\Users\linyunlong>scoop checkup
No problems identified!
```

![image](https://user-images.githubusercontent.com/16333958/68103312-2d3cd880-ff11-11e9-8e2b-121aced2c384.png)

**Comment by ratatoeey** [comment]
is the log in `~\scoop\apps\brackets\1.14\msi.log` the same as your first post?

I suspect controlled folder access. though it should give notifications if a program tried to access anything protected. is controlled folder access enabled for the folders which scoop uses?
here's my output for the environment variables which store the directory location. its risky, but its to avoid scoop tripping up.
```
echo $env:SCOOP_GLOBAL $env:SCOOP
D:\apps
D:\scoop
```

**Comment by loong95** [comment]
@ratatoeey @Ash258 

The log is the same as my first post. I think scoop has permission to access the folder because other softwares can be installed successfully.

Anyway, I had installing brackets successfully by using "-g" options. The path used by global installation is shorter than that path used by user installation.

Thanks for your reply.
