### ISSUE TITLE
foxit-reader@9.7.0.29455: decompress error

### ISSUE THREAD

**Issue by cybertim** [lukesampson/scoop-extras#2917]
Installing 'foxit-reader' (9.7.0.29455) [64bit]
FoxitReader97_Setup_Prom_IS.exe (65.6 MB) [===================================================================] 100%
Checking hash of FoxitReader97_Setup_Prom_IS.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
Get-ChildItem : Cannot find path 'C:\Users\cyber\scoop\apps\foxit-reader\9.7.0.29455\$PLUGINSDIR' because it does not
exist.
At line:1 char:1
+ Get-ChildItem "$dir\`$PLUGINSDIR" '*_Prom.exe' | Select-Object -Expan ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\cyber\...455\$PLUGINSDIR:String) [Get-ChildItem], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Split-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Users\cyber\scoop\apps\scoop\current\lib\decompress.ps1:182 char:30
+     $LogPath = "$(Split-Path $Path)\innounp.log"
+                              ~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Spli
   tPathCommand

Out-File : Access to the path 'C:\innounp.log' is denied.
At C:\Users\cyber\scoop\apps\scoop\current\lib\core.ps1:428 char:9
+         Out-File -FilePath $LogPath -Encoding ASCII -Append -InputObj ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], UnauthorizedAccessException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

ERROR Exit code was 1!
Failed to extract files from .
Log file:
  \innounp.log

**Comment by ebugusey** [comment]
Duplicate #2914.
