### ISSUE TITLE
[Request] Add Windows Terminal

### ISSUE THREAD

**Issue by LoZeno** [lukesampson/scoop-extras#2921]
I'm not sure if this should be here or if it would fit better on the main bucket (like cmder does), but:

Windows Terminal
https://github.com/microsoft/terminal

The Releases page of their github repo provides the installable msix bundle packages

**Comment by ratatoeey** [comment]
it would be better if the microsoft/terminal releases page had sha256 or sha512 hashes and actually provided a scoop bucket or a zip that makes 'scoop install' easier.

**Comment by fandean** [comment]
@Ash258 
I've installed WindowsTerminal before, but I want to use scoop instead
```
scoop install Ash258/WindowsTerminal
```
When I opened Windows terminal, a prompt popped up, failing to find  VCRUNTIME140_1.dll

![image](https://user-images.githubusercontent.com/25637720/68361092-7a14ef00-015d-11ea-93be-39452bf2a9dc.png)

```
System Information
---------------------------------------------------------
OS             : Windows 10 (10.0.18362)
```

**Comment by linsui** [comment]
`scoop install extras/vcredist2017`

**Comment by simnalamburt** [comment]
Actually you should try `scoop install vcredist2019` not `vcredist2017`

**Comment by rdlu** [comment]
Had exactly the same on my fresh Windows 10 18632 installation. `scoop install vcredist2019` solved.

It is not a prerequisite?

**Comment by simnalamburt** [comment]
I think it is a prerequisite.
