### ISSUE TITLE
foxit-reader@9.7.0.29455: decompress error

### ISSUE THREAD

**Issue by ryanhhtan** [lukesampson/scoop-extras#2936]
Get-ChildItem : Cannot find path 'D:\Applications\Scoop\apps\foxit-reader\9.7.0.29455\$PLUGINSDIR' because it
does not exist.
At line:1 char:1
+ Get-ChildItem "$dir\`$PLUGINSDIR" '*_Prom.exe' | Select-Object -Expan ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Applications...455\$PLUGINSDIR:String) [Get-ChildItem], Ite
   mNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Split-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At D:\Applications\Scoop\apps\scoop\current\lib\decompress.ps1:182 char:30
+     $LogPath = "$(Split-Path $Path)\innounp.log"
+                              ~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Comm
   ands.SplitPathCommand

Out-File : Access to the path 'C:\innounp.log' is denied.
At D:\Applications\Scoop\apps\scoop\current\lib\core.ps1:428 char:9
+         Out-File -FilePath $LogPath -Encoding ASCII -Append -InputObj ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], UnauthorizedAccessException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

ERROR Exit code was 1!
Failed to extract files from .
Log file:
  \innounp.log

**Comment by Velgus** [comment]
It's being handled in #2916. Would be nice if it could be pulled soon, since that manifest is completely broken at the moment.

**Comment by ebugusey** [comment]
Duplicate #2914.
