### ISSUE TITLE
cpu-z@1.90: hash check failed

### ISSUE THREAD

**Issue by averred** [lukesampson/scoop-extras#2965]
Installing 'cpu-z' (1.90) [64bit]
cpu-z_1.90-en.zip (2.9 MB) [==================================================================================] 100%
Checking hash of cpu-z_1.90-en.zip ... ERROR Hash check failed!
App:         extras/cpu-z
URL:         http://download.cpuid.com/cpu-z/cpu-z_1.90-en.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    6a6563464184a5a6158ae9a9860927ac05b73cbb6f262453cd5433d4a8d79cd9
Actual:      33e0a7c552aa337c26fb63cf07b45a05d36ac08341ced402229d3565d079a2b2

**Comment by issaclin32** [comment]
Fixed in https://github.com/lukesampson/scoop-extras/commit/5c7c59392942558837333cc0aabc453bf660ead6.
