### ISSUE TITLE
altair@2.3.5: download via aria2 failed

### ISSUE THREAD

**Issue by tryyoung** [lukesampson/scoop-extras#2981]
Download: 10/15 20:49:42 [ERROR] CUID#8 - Download aborted. URI=https://github.com/imolorhe/altair/releases/download/v2.3.5/altair_2.3.5_win.exe#/dl.7z
Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://github.com/imolorhe/altair/releases/download/v2.3.5/altair_2.3.5_win.exe
Download:   -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 0c1366|ERR |       0B/s|C:/Users/Mingpeng/scoop/cache/altair#2.3.5#https_github.com_imolorhe_altair_releases_download_v2.3.5_altair_2.3.5_win.exe_dl.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/imolorhe/altair/releases/download/v2.3.5/altair_2.3.5_win.exe#/dl.7z
    referer=https://github.com/imolorhe/altair/releases/download/v2.3.5/altair_2.3.5_win.exe#/
    dir=C:\Users\Mingpeng\scoop\cache
    out=altair#2.3.5#https_github.com_imolorhe_altair_releases_download_v2.3.5_altair_2.3.5_win.exe_dl.7z

ERROR & 'C:\Users\Mingpeng\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Mingpeng\scoop\cache\altair.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3976 --continue

**Comment by imolorhe** [comment]
Hey @r15ch13 sorry about the package name change. Unfortunately it's going to be changed back to the original naming in v2.3.6, so that might break again. 😞

**Comment by r15ch13** [comment]
No problem :smile:
Just create a PR when you have released the new version :grin:
