### ISSUE TITLE
flashplayer-sa@32.0.0.270: hash check failed

### ISSUE THREAD

**Issue by younger-1** [lukesampson/scoop-extras#3036]
Checking hash of flashplayer_32_sa.exe ... ERROR Hash check failed!                                                    App:         extras/flashplayer-sa                                                                                     URL:         https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flashplayer_32_sa.exe#/flashplayer.exe      First bytes: 3C 21 44 4F 43 54 59 50                                                                                   Expected:    c7c6424d48cc8c3d8e15442d7a58287c400a8fcf3a315a127005b596b9ed142e                                          Actual:      21d09282de5c1f9251cae45fabd2a55d7e875fcdc88f9272808bfb63cd57bdc5                                                                                                                                                                 Please try again or create a new issue by using the following link and paste your console output:                      https://github.com/lukesampson/scoop-extras/issues/new?title=flashplayer-sa%4032.0.0.270%3a+hash+check+failed

**Comment by rasa** [comment]
The hash in the manifest (the “expected” hash above) is correct. Please try again.
