### ISSUE TITLE
mattermost@4.3.1: download returns 403

### ISSUE THREAD

**Issue by LoZeno** [lukesampson/scoop-extras#3042]
When trying to upgrade mattermost, the download returns the following:
`
❯ scoop update mattermost                                                                                                                                                                   mattermost: 4.3.0 -> 4.3.1                                                                                                                                                         Updating one outdated app:                                                                                                                                                         Updating 'mattermost' (4.3.0 -> 4.3.1)                                                                                                                                             Downloading new version                                                                                                                                                            The remote server returned an error: (403) Forbidden.                                                                                                                              At C:\Users\Tesco-UKE12364653\scoop\apps\scoop\current\lib\install.ps1:130 char:9                                                                                                  +         throw $e                                                                                                                                                                 +         ~~~~~~~~                                                                                                                                                                 + CategoryInfo          : OperationStopped: (:) [], WebException                                                                                                                   + FullyQualifiedErrorId : The remote server returned an error: (403) Forbidden. 
`

looking at their website, it looks like they swapped the .zip file with an .msi file for this version: the download URL in the manifest (`https://releases.mattermost.com/desktop/4.3.1/mattermost-desktop-4.3.1-win-x64.zip`) returns 403, but changing .zip with .msi starts the download just fine.

**Comment by linsui** [comment]
It works now, please try again.

**Comment by LoZeno** [comment]
Download works now, but fails the hash check:

> ❯ scoop update mattermost                                                                                                                                                         mattermost: 4.3.0 -> 4.3.1                                                                                                                                                        Updating one outdated app:                                                                                                                                                        Updating 'mattermost' (4.3.0 -> 4.3.1)
> Downloading new version
> mattermost-desktop-4.3.1-win-x64.zip (87.7 MB) [========================================================================================================================] 100%
> Checking hash of mattermost-desktop-4.3.1-win-x64.zip ... ERROR Hash check failed!
> App:         extras/mattermost
> URL:         https://releases.mattermost.com/desktop/4.3.1/mattermost-desktop-4.3.1-win-x64.zip
> First bytes: 50 4B 03 04 14 00 00 00
> Expected:    be6760e68f5e6a31343940adc0d73261ecaad2d8741a2a98b8c688b18d5172c2
> Actual:      d4267e3e2af3a43048521905217d8ac31d57a55d881efed6affc08f8bbff4196
> 
> Please try again or create a new issue by using the following link and paste your console output:
> https://github.com/lukesampson/scoop-extras/issues/new?title=mattermost%404.3.1%3a+hash+check+failed

I obviously have tried again a few times, the actual hash after the download is always `d4267e3e2af3a43048521905217d8ac31d57a55d881efed6affc08f8bbff4196`

**Comment by linsui** [comment]
Upstream changed the file... See https://github.com/mattermost/desktop/releases
