### ISSUE TITLE
Please update brave

### ISSUE THREAD

**Issue by Jogai** [lukesampson/scoop-extras#3052]

**Comment by issaclin32** [comment]
According to its [official repo](https://github.com/brave/brave-browser/releases), the latest **stable version** (Release channel) is still at version **0.70.121**, so [the manifest](https://github.com/lukesampson/scoop-extras/blob/master/bucket/brave.json) is actually up-to-date.

We can add another `brave-beta` or `brave-nightly` package for beta/nightly releases.

**Comment by Jogai** [comment]
I opened this issue before you updated brave. Thanks for that!
