### ISSUE TITLE
notepadplusplus@7.7.1: download via aria2 failed

### ISSUE THREAD

**Issue by alex-levin** [lukesampson/scoop-extras#3078]
~ $ scoop install notepadplusplus
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'notepadplusplus' (7.7.1) [64bit]
Starting download with aria2 ...
Download: [#ce28da 0B/0B CN:0 DL:0B]
Download: [#ce28da 0B/0B CN:0 DL:0B]
Download: [#ce28da 0B/0B CN:0 DL:0B]
Download: [#ce28da 0B/0B CN:0 DL:0B]
Download: [#ce28da 0B/0B CN:0 DL:0B]
Download: [#ce28da 0B/0B CN:0 DL:0B]
Download: [#ce28da 0B/0B CN:0 DL:0B]
Download: [#ce28da 0B/0B CN:0 DL:0B]
Download: 10/31 06:43:44 [ERROR] CUID#8 - Download aborted. URI=https://notepad-plus-plus.org/repository/7.x/7.7.1/npp.7.7.1.bin.x64.7z
Download: Exception: [HttpSkipResponseCommand.cc:229] errorCode=29 The response status is not successful. status=503
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: ce28da|ERR |       0B/s|C:/Users/Alex/scoop/cache/notepadplusplus#7.7.1#https_notepad-plus-plus.org_repository_7.x_7.7.1_npp.7.7.1.bin.x64.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 29) The remote server was unable to handle the request due to a temporary overloading or maintenance
ERROR https://notepad-plus-plus.org/repository/7.x/7.7.1/npp.7.7.1.bin.x64.7z
    referer=https://notepad-plus-plus.org/repository/7.x/7.7.1/
    dir=C:\Users\Alex\scoop\cache
    out=notepadplusplus#7.7.1#https_notepad-plus-plus.org_repository_7.x_7.7.1_npp.7.7.1.bin.x64.7z

ERROR & 'C:\Users\Alex\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Alex\scoop\cache\notepadplusplus.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=10020 --continue

**Comment by filippobuletto** [comment]
They changed download URLs and also facing a DDoS because politics: https://www.theregister.co.uk/2019/10/31/notepad_china_spam/

**Comment by ratatoeey** [comment]
just hope it gets back online. attacking a site is just messed up. now they will put cloudflare and there will be the waiting 5 minutes issue

**Comment by jwhipp** [comment]
I'm having the same issue with scoop but I can download the file manually just fine.

**Comment by ohk2kt3t4** [comment]
Works for me now.
