### ISSUE TITLE
RDC Man & 7-Zip Context

### ISSUE THREAD

**Issue by GamerClassN7** [lukesampson/scoop-extras#3081]
Hi
I love scoop it is brilliant but would be even possible i tried several times (unsucesfull :( :( ) to add 

Remote Desktop Connection Manager 2.7
https://www.microsoft.com/en-us/download/details.aspx?id=44989

to scoop and also add context menu for 7zip manifest <- this think is way to difficult to me  :(

I am sis admin and if would be possible to fix this 2 thinks it would be huge think form me, id i would use scoop on all Compiuters at my company it would be such a huge time saver at my work :)

Thanks For any reaction

**Comment by Ash258** [comment]
For 7zip you can always configure it within 7zip 

![image](https://user-images.githubusercontent.com/13260377/67970534-6d4b4500-fc0b-11e9-9dfe-652056418d53.png)

But if you aim for some automatic way with registry file, it could be pretty complex to support all configuration options as in options window within 7zip. And with some default "universal" context menu there is high chance it will not fit your needs or needs of wide user base.

For RDCman its manifest could be pretty simple

```json
{
    "version": "2.7",
    "homepage": ".....",
    "description": "....",
    "url": "https://download.microsoft.com/download/A/F/0/AF0071F3-B198-4A35-AA90-C68D103BDCCF/rdcman.msi",
    "hash": "Cannot find hash right now from phone",
	"extract_dir": "program files\\Microsoft\\Remote Desktop Connection Manager",
    "shortcuts": [["RDCMan.exe", "Remote Desktop Connection Manager"]]
```

**Comment by ratatoeey** [comment]
>  with some default "universal" context menu ...

doesn't 7-zip when installed from msi or exe downloaded from https://www.7-zip.org/download.html, create context menu entries by default? i think default is to add it to context menu as it also adds other stuff that may be useful to the user, namely checksum verification.

correct me I'm wrong.
---

regards ratatoeey

**Comment by GamerClassN7** [comment]
Thanks to all :)
i will try RDC man installer tomorrow.

for the zip, I want just default ability. for most reasons to pack and unpack.
i think it would be good to add to manifest default context menu if possible 
![image](https://user-images.githubusercontent.com/22167469/68075926-c7d0d680-fdae-11e9-988a-318d9be434c1.png)
