### ISSUE TITLE
Add Caffeine

### ISSUE THREAD

**Issue by dzampino** [lukesampson/scoop-extras#3086]
Submitted PR #3085 to add Caffeine. Caffeine is a small program that sits in the tray and keeps the computer awake. Learned about it from Boxstarter. It's a tool I use on a regular basis. While it has several command-line options, it's not really a command-line tool, so I submitted it to the extras repo.

**Comment by Ash258** [comment]
Do not create issue when you alredy created PR

**Comment by dzampino** [comment]
Won't happen again
