### ISSUE TITLE
musicbee@3.3.7165: hash check failed

### ISSUE THREAD

**Issue by ly-xs** [lukesampson/scoop-extras#3133]
Checking hash of dl.zip ... ERROR Hash check failed!
App:         extras/musicbee
URL:         https://www.mediafire.com/file/aclnp3sdzb9yn94/MusicBeePortable_3_3_Update1.zip/file#/dl.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    6003ca7e35ee37fdb64389feae395c68d3e97a52725ad47d0ac1775bfe3a992f
Actual:      85e375664b97a1580a8430283a1d79bcf3297ea5d1d65a37cb4016dcb379c580

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop-extras/issues/3014
