### ISSUE TITLE
sqlyog-community@13.1.5: download via aria2 failed

### ISSUE THREAD

**Issue by tianzhiqiang11** [lukesampson/scoop-extras#3139]
**When i input  “scoop install -g sqlyog-community“，it throw some exception**
ERROR Download failed! (Error 19) Name resolution failed
ERROR https://s3.amazonaws.com/SQLyog_Community/SQLyog+13.1.5/SQLyog-13.1.5-0.x64Community.exe#/dl.7z
    referer=https://s3.amazonaws.com/SQLyog_Community/SQLyog+13.1.5/SQLyog-13.1.5-0.x64Community.exe#/
    dir=E:\scoopApp\cache
    out=sqlyog-community#13.1.5#https_s3.amazonaws.com_SQLyog_Community_SQLyog_13.1.5_SQLyog-13.1.5-0.x64Community.exe_dl.7z

ERROR & 'E:\scoopApp\apps\aria2\current\aria2c.exe' --input-file='E:\scoopApp\cache\sqlyog-community.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=45020 --continue --all-proxy='loaclhost:1080'

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=sqlyog-community%4013.1.5%3a+download+via+aria2+failed

**Comment by linsui** [comment]
> Name resolution failed

Please check your DNS config and try again.
