### ISSUE TITLE
question about waterfox and related package names

### ISSUE THREAD

**Issue by ghost** [lukesampson/scoop-extras#3143]
on https://www.waterfox.net/releases/, there are two versions for `waterfox classic`. and one for `waterfox current`.

why is there no `waterfox-classic` or `waterfox-classic-portable` package? i tried `scoop info` followed by those two names.

what i did find was `waterfox` and `waterfox-current`. Is waterfox the third version that is specific to scoop?

----

regards ratatoeey

**Comment by issaclin32** [comment]
The `waterfox` package is Waterfox Classic. We named the packages like this, so that users that have installed **old versions of Waterfox** (before Waterfox split into classic/current branches) can keep their software updated.

Both `waterfox` and `waterfox-current` packages are portable. In most cases, Scoop simply extracts files from the installer (instead of running the installer).

**Comment by ratatoeey** [comment]
my motive is to make naming more useful by either
- have names consistent across official scoop buckets like main, extras, etc.
- or just directly use the names of packages from the developer. as that would be least confusing as scoop is the younger source and should aim for compromises.

I think I would prefer it if the one consistent approach were adopted for a one package. my reason would be it makes sense. especially for new users of scoop and in this instance, waterfox.

---

> ... We named the packages like ...

I can't make sense of that decision, so never mind.

so will it be changed to be sane naming system. once it can be assumed that almost all users would have updated and won't be affected?

and will I have to do this process again for every single offending package? i don't expect a bot to be available to do it as scoop is very young and rough. well, it has only been a few months from -> https://github.com/lukesampson/scoop/releases or were there no older releases?

----

regards ratatoeey
