### ISSUE TITLE
storageexplorer@1.10.0: hash check failed

### ISSUE THREAD

**Issue by vikramvvp** [lukesampson/scoop-extras#3150]
Checking hash of StorageExplorer.exe ... ERROR Hash check failed!
App:         extras/storageexplorer
URL:         https://download.microsoft.com/download/A/E/3/AE32C485-B62B-4437-92F7-8B6B2C48CB40/StorageExplorer.exe#/storageexplorer_installer.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    69f55966ed6826d69cd290f2d9822791a59bf5c152ca4d4a6f67dcf6b6ffd625
Actual:      d22cef7d7f6d4cf0d266b714ea7d5a894063d6d92557827f58c2cca3593f1ff2

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=storageexplorer%401.10.0%3a+hash+check+failed

**Comment by outforpublic** [comment]
I have got a different answer...
```
PS C:\Users\********\AppData\Local\Temp> wget.exe https://download.microsoft.com/download/A/E/3/AE32C485-B62B-4437-92F7-8B6B2C48CB40/StorageExplorer.exe#/storageexplorer_installer.exe -q
PS C:\Users\********\AppData\Local\Temp> certutil -hashfile storageexplorer.exe sha256
SHA256 hash of storageexplorer.exe:
deae692687e8ea2e0f9612404261a5631df53fcb6a98bbe265bfef44f3ab6d46
CertUtil: -hashfile command completed successfully.
```
