### ISSUE TITLE
typora@0.9.79: decompress error

### ISSUE THREAD

**Issue by xiaobucvg** [lukesampson/scoop-extras#3155]
Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提 供一个不为 Null 或空的参数，然后重试                                                                                    该命令。                                                                                                                所在位置 C:\Users\ZhangHuan\scoop\apps\scoop\current\lib\decompress.ps1:192 字符: 38                                    + ... tus = Invoke-ExternalCommand (Get-HelperPath -Helper Innounp) $ArgLis ...                                         +                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                         + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException                + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

**Comment by linsui** [comment]
Please try `scoop uninstall innounp; scoop install innounp`
