### ISSUE TITLE
[Request] T-Clock

### ISSUE THREAD

**Issue by priyadarshan** [lukesampson/scoop-extras#3157]
A very flexible taskbar clock, with ISO week number support, bug fixes and the ability to use Windows' default calendar and tooltips:

https://github.com/White-Tiger/T-Clock

**Comment by outforpublic** [comment]
I have created a temporary way to install it <a href="https://gist.github.com/outforpublic/0cffaf7e30b2d6f5990f585a64cfe56c">Here</a>.

To install it, use

```
scoop install https://gist.github.com/outforpublic/0cffaf7e30b2d6f5990f585a64cfe56c/raw/69f7b35b2de95796ab8ed826f4dd072765117b82/T-Clock.json
```

**Comment by priyadarshan** [comment]
Thank you!

**Comment by outforpublic** [comment]
No Problem (I like helping people out)
