### ISSUE TITLE
Robo3t is not available, can you update it?

### ISSUE THREAD

**Issue by qiaoqiao888** [lukesampson/scoop-extras#3163]
Robo3t is not available, can you update it?

**Comment by Ash258** [comment]
Upstream issue. Any windows download do not work.

![A](https://i.imgur.com/KgMvQvX.gif)

![B](https://i.imgur.com/Dp9ulio.gif)

**Comment by qiaoqiao888** [comment]
Thank you, has resumed downloading~

**Comment by qiaoqiao888** [comment]
Thank you, it has been restored
