### ISSUE TITLE
[Request] Add JabRef

### ISSUE THREAD

**Issue by priyadarshan** [lukesampson/scoop-extras#3164]
JabRef: A graphical Java application for managing BibTeX and biblatex (.bib) databases.

https://github.com/JabRef/jabref

**Comment by linsui** [comment]
You can test [this](https://github.com/dodorz/scoop-bucket/blob/master/JabRef.json)

**Comment by priyadarshan** [comment]
Thank you, that works well.

The only difference, with a regular installation:

```
JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_172
```

While that bucket has 32-bit version:

```
JabRef 4.3.1
Windows 10 10.0 x86 
Java 1.8.0_201
```
