### ISSUE TITLE
linqpad@6.3: hash check failed

### ISSUE THREAD

**Issue by scottbilas** [lukesampson/scoop-extras#3165]
Checking hash of LINQPad6.zip ... ERROR Hash check failed!
App:         extras/linqpad
URL:         http://download.linqpad.net/public/LINQPad6.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    d9995e26e11faa9f03c1916d7a0382f59055c8aeef318abe8b783a47f24e458f
Actual:      78ae277876f48e594fe4a3ecc8145a29d7ff8439fe43dcf2af537871961aee72

**Comment by outforpublic** [comment]
```
PS C:\Users\******> iwr "http://download.linqpad.net/public/LINQPad6.zip" -o test.zip                                   PS C:\Users\******> certutil -hashfile test.zip sha1
SHA1 hash of test.zip:
9f9616e11ec2a5367b6f63c59a0a056b1cd86a9e
```
Ok, now i'm confused

**Comment by outforpublic** [comment]
Lol nvm, I was doing sha1, not 256

I got the same result as you

```
PS C:\Users\******> iwr "http://download.linqpad.net/public/LINQPad6.zip" -o test.zip
PS C:\Users\******> certutil -hashfile test.zip sha256
SHA256 hash of test.zip:
78ae277876f48e594fe4a3ecc8145a29d7ff8439fe43dcf2af537871961aee72
```
