### ISSUE TITLE
easyserviceoptimizer@1.2: hash check failed

### ISSUE THREAD

**Issue by Volipy** [lukesampson/scoop-extras#3176]
Checking hash of eso.zip ... ERROR Hash check failed!
App:         extras/easyserviceoptimizer
URL:         https://www.sordum.org/files/easy-service-optimizer/eso.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    7bad6041662eb09b32a7184cedd8442b6efa502e7692d1642177d35644b1ae5e
Actual:      500af1822585851cc220dc5e55365a0d5e6341fed6a39dd9801348459564cec7

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=easyserviceoptimizer%401.2%3a+hash+check+failed

**Comment by outforpublic** [comment]
I have confirmed you are right.
```
PS C:\Users\********> iwr -outfile test.zip "https://www.sordum.org/files/easy-service-optimizer/eso.zip"
PS C:\Users\********> certutil -hashfile test.zip sha256
SHA256 hash of test.zip:
500af1822585851cc220dc5e55365a0d5e6341fed6a39dd9801348459564cec7
CertUtil: -hashfile command completed successfully.
```


### I have created a temporary way to install <a href="https://gist.github.com/outforpublic/2f57e8ad20b33df0e5953f0621e01982/">Here</a>.
**Install it by using:**

```
scoop install https://gist.github.com/outforpublic/2f57e8ad20b33df0e5953f0621e01982/raw/c9c32663b4653a1144a3b4d3e390edbed6ee6abf/easyserviceoptimizer.json
```
