### ISSUE TITLE
telegram@1.8.15: download via aria2 failed

### ISSUE THREAD

**Issue by Volipy** [lukesampson/scoop-extras#3177]
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://updates.tdesktop.com/tsetup/tportable.1.8.15.zip
    referer=https://updates.tdesktop.com/tsetup/
    dir=C:\Users\10027\scoop\cache
    out=telegram#1.8.15#https_updates.tdesktop.com_tsetup_tportable.1.8.15.zip

ERROR & 'C:\Users\10027\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\10027\scoop\cache\telegram.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3584 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=telegram%401.8.15%3a+download+via+aria2+failed

**Comment by Ash258** [comment]
Everything works fine now
