### ISSUE TITLE
ida-free@7.0: decompress error

### ISSUE THREAD

**Issue by xycui** [lukesampson/scoop-extras#3183]
# Command line output
```
Extracting idafree70_windows.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\****\scoop\apps\ida-free\7.0\idafree70_windows.exe.
Log file:
  ~\scoop\apps\ida-free\7.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=ida-free%407.0%3a+decompress+error
```
![image](https://user-images.githubusercontent.com/2989428/68943518-61a07680-07e6-11ea-9b04-b10bcb6378bb.png)

# innounp.log
```
The setup files are corrupted or made by incompatible version. Maybe it's not an Inno Setup installation at all.
(00491A8A)
```
# More
- It is an installation exe. I think that is why the innounp process throw exception.
- Maybe the ida change their exe to installation one instead of the previous zip one if the previous versions worked.

**Comment by Ash258** [comment]
They changed from innosetup to some proprietary installed based on InstallShield.

- It need admin privileges
- There is GUI spawn while copying

![image](https://user-images.githubusercontent.com/13260377/68944566-647f7500-07ae-11ea-82d8-9949de861b22.png)

![image](https://user-images.githubusercontent.com/13260377/68944623-9395e680-07ae-11ea-87b7-663aa6490fb1.png)

**Comment by xycui** [comment]
I also found it by idaxxx.exe --help.

**Comment by xycui** [comment]
But I am not sure if we should provide the uninstall section.
