### ISSUE TITLE
[Request] CHK Hash Tool

### ISSUE THREAD

**Issue by sethazazel** [lukesampson/scoop-extras#3198]
CHK is an advanced hash tool with a nice gui.
[https://compressme.net/](https://compressme.net/)

**Comment by asd-collab** [comment]
its proprietary but provides more hash options than 7zip. list here.

>
    Adler32
    BLAKE2b, BLAKE2b/160, BLAKE2b/256, BLAKE2bp, BLAKE2s, BLAKE2sp
    CRC32, CRC64
    MD4, MD5
    RIPEMD-160
    SHA-1, SHA-1 (Base32)
    SHA-224, SHA-256, SHA-256 (Base64), SHA-384, SHA-512, SHA-512/224, SHA-512/256
    SHA3-224, SHA3-256, SHA3-384, SHA3-512
    Tiger
    Whirlpool

really obscure application.

can the developer also provide SHA-256 hashes instead of only BLAKE2b/160? for use with `getFileHash`.

--


asd-collab

---
