### ISSUE TITLE
[Suggestion] linqpad: remove `"depends"`

### ISSUE THREAD

**Issue by batkiz** [lukesampson/scoop-extras#3200]
in [linqpad's mainfest](https://github.com/lukesampson/scoop-extras/blob/master/bucket/linqpad.json), it depends on `dotnet-sdk`.
```json
"depends": "dotnet-sdk",
```
But if somebody installed `dotnet-sdk` via installer but not scoop(just like me), it will install `dotnet-sdk` automatically, obviously it's not necessary. So I hope we could remove the `depends`.
If ok, I'll create a PR later.

**Comment by linsui** [comment]
You can change it to
```
"suggest": {
    ".Net SDK": "dotnet-sdk"
}
```

**Comment by asd-collab** [comment]
same issue for extras/vcredist2010 in youtubedl.json

aside:
removing scoop-installed versions of vcredist , it clutters up fast. and entries shows up in control panel.

---

asd-collab
