### ISSUE TITLE
suggestion: change source for chromium package

### ISSUE THREAD

**Issue by ghost** [lukesampson/scoop-extras#3201]
chromium is still stuck at **Version: 78.0.3904.87-r693954**

in manifest its source is 'https://github.com/macchrome/winchrome/releases' which is actually slower to update than https://github.com/Hibbiki/chromium-win64/releases

compare dates for https://github.com/Hibbiki/chromium-win64/releases/tag/v78.0.3904.97-r693954 vs. https://github.com/macchrome/winchrome/releases/tag/v78.0.3904.97-r693954-Win64

https://github.com/macchrome/winchrome/releases/tag/v78.0.3904.97-r693954-Win64 also has releases for sync and nosync versions.

---

so if this proposal gets accepted. for 32-bit builds there is https://github.com/Hibbiki/chromium-win32/releases and for 64-bit releases https://github.com/Hibbiki/chromium-win64/releases

so, I suggest that package chromium not lag anymore by using slow package source.
---

cheers tratTalks

**Comment by tratTalks** [comment]
i reached the new source by chance, when I read manifest and went to https://chromium.woolyss.com/

that site also provides SHA1 checksums for Hibbiki's build. 

---



---

cheers tratTalks
