### ISSUE TITLE
suggestion: ungoogled-chromium package using github.com/macchrome/winchrome

### ISSUE THREAD

**Issue by ghost** [lukesampson/scoop-extras#3202]
after https://github.com/lukesampson/scoop-extras/issues/3201, to make naming of packages more clear and transparent; instead of obtuse and misleading, I suggest that https://github.com/macchrome/winchrome/releases be used for a ungoogled-chromium package.

Its name is derived from the released files in https://github.com/macchrome/winchrome/releases/tag/v78.0.3904.97-r693954-Win64 , releases for both 32-bit and 64-bit are available.

it takes some time to catch up, because it applies patches that `ungoogle` chromium. So, the name is self-explanatory, or intuitive. And users that don't use scoop will mostly be confused by the naming mess for chromium packages that exist now.

---

cheers tratTalks

**Comment by tratTalks** [comment]
the release names mentions the revision, I think-> by the `r693954` part. that should help in debugging issues.

----

aside: 
it would be nice if a bot handled upgrades. and simple testing was automated. 
but that's for another 2 issues, as some people get pretty aggravated by relevant issues in one place.
Maybe can call it an epic. Then they will shut up and stop pissing off folks.
---

cheers tratTalks

**Comment by tratTalks** [comment]
aside: 
it would be nice if a bot handled upgrades. and simple testing was automated. 
but that's for another 2 issues, as some people get pretty aggravated by relevant issues in one place.
Maybe can call it an epic. Then they will shut up and stop pissing off folks.
---

cheers tratTalks
