### ISSUE TITLE
gpu-z@2.27.0: hash check failed

### ISSUE THREAD

**Issue by emmett421** [lukesampson/scoop-extras#3209]
gpu-z: 2.26.0 -> 2.27.0                                                                                                WARN  Scoop uses 'aria2c' for multi-connection downloads.                                                              WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.                                    Updating one outdated app:                                                                                             Updating 'gpu-z' (2.26.0 -> 2.27.0)                                                                                    Downloading new version                                                                                                Starting download with aria2 ...                                                                                       Download: [#8ea4c0 432KiB/6.7MiB(6%) CN:1 DL:562KiB ETA:11s]                                                           Download: [#8ea4c0 4.7MiB/6.7MiB(70%) CN:1 DL:2.6MiB]                                                                  Download: Download Results:                                                                                            Download: gid   |stat|avg speed  |path/URI                                                                             Download: ======+====+===========+=======================================================                              Download: 8ea4c0|OK  |   2.7MiB/s|C:/Users/Emmett/scoop/cache/gpu-z#2.27.0#http_nl1-dl.techpowerup.com_files_GPU-Z.2.27.0.exe_GPU-Z.exe                                                                                                       Download: Status Legend:                                                                                               Download: (OK):download completed.                                                                                     Checking hash of GPU-Z.2.27.0.exe ... ERROR Hash check failed!                                                         App:         extras/gpu-z                                                                                              URL:         http://nl1-dl.techpowerup.com/files/GPU-Z.2.27.0.exe#/GPU-Z.exe                                           First bytes: 4D 5A 90 00 03 00 00 00                                                                                   Expected:    3a34f1a6fafd10b7019a12c9e9a334fe                                                                          Actual:      a8bf8436caece1a691acad62d83256bb

**Comment by asd-collab** [comment]
/close
---

asd-collab
