### ISSUE TITLE
vscode@1.36.1: hash check failed

### ISSUE THREAD

**Issue by JustinGrote** [lukesampson/scoop-extras#3225]
Checking hash of vscode-install-context.reg ... ERROR Hash check failed!
App:         extras/vscode
URL:         https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg      First bytes: 57 69 6E 64 6F 77 73 20
Expected:    3673d7767da27418c4c7eea146043fa6a7c59df65199c79850e58367fd66fb56
Actual:      b65d66860d9ccc18bfb05237b03e06db0d6c574be3d4b946c2a5e6865c08cb28

**Comment by Ash258** [comment]
You are installing pretty old version. Since then there were few updates to registry files. If you install this specific version on purpose you need to use `scoop install vscode@1.36.1 -s`
