### ISSUE TITLE
[Request] Add Yakyak

### ISSUE THREAD

**Issue by jwhipp** [lukesampson/scoop-extras#3227]
Yakyak is an opensource replacement for using the Chrome hangouts extension.

Can be found here: https://github.com/yakyak/yakyak

Artifacts are in releases, doesn't use an installer.

**Comment by dinNew** [comment]
latest  release https://github.com/yakyak/yakyak/tree/v1.5.3 on Nov 2018 no hashes or checksums.

don't even have an issues page to report issues. so they don't want to listen.

---

thanks dinNew

**Comment by jwhipp** [comment]
Actually you might be right.  I totally skipped over the release date.   We can hold off on this one, we'll wait and see if the project comes back to life at some point.
