### ISSUE TITLE
question: how do you report issues to https://github.com/stream-labs/streamlabs-obs 

### ISSUE THREAD

**Issue by dinNew** [lukesampson/scoop-extras#3230]
i just saw https://github.com/lukesampson/scoop-extras/commit/186bfca93544122b538ad144f3a5fd2781e95949 and went to the site and found issues.

but their github has no issues page to report issues. 

why do they need special treatment? I mean on their wiki page  https://github.com/stream-labs/streamlabs-obs/wiki they give this link  https://tracker.streamlabs.com/ to report issues, which doesn't work. 

So, I want to tell them to just use Github as it has issues page that projects use. And provide checksums for their releases. And help scoop developers so its less annoying to maintain their package.

---

thanks dinNew

**Comment by dinNew** [comment]
also

**Comment by Ash258** [comment]
Do not use scoop's repositories for not relevant issues.

**Comment by r15ch13** [comment]
@dinNew I'm not updating anything by hand. That is done automatically by running [bin/checkver.ps1](https://github.com/lukesampson/scoop/blob/master/bin/checkver.ps1) via https://github.com/ScoopInstaller/Excavator :smile:

Also, please stop deleting your accounts... 😁
