### ISSUE TITLE
dbeaver@6.3.0: hash check failed

### ISSUE THREAD

**Issue by summersmd** [lukesampson/scoop-extras#3311]
Updating 'dbeaver' (6.2.4 -> 6.3.0)
Downloading new version
dbeaver-ce-6.3.0-win32.win32.x86_64.zip (56.8 MB) [===========================================================] 100%
Checking hash of dbeaver-ce-6.3.0-win32.win32.x86_64.zip ... ERROR Hash check failed!
App:         extras/dbeaver
URL:         https://dbeaver.io/files/6.3.0/dbeaver-ce-6.3.0-win32.win32.x86_64.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    9996a3d251c07a0d8636e6ec8078e8c5b03d2cdbd1baa5637e4f0f0461da7fbf
Actual:      960f67be460b9f550619ccf80afdcf916695d35ae43bb1e6c184172122d85fe6

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=dbeaver%406.3.0%3a+hash+check+failed

**Comment by phloose** [comment]
After some research i found that the actual checksum in the extras bucket is from this page: https://dbeaver-portable.en.lo4d.com/windows. So the person who setup the the dbeaver.json put in the download link from the official page and the checksum from lo4d.com.
