### ISSUE TITLE
terminal: Add Windows Terminal Preview v0.7.3291.0

### ISSUE THREAD

**Issue by shytikov** [lukesampson/scoop-extras#3314]
Add new Windows Terminal: https://github.com/microsoft/terminal/

**Comment by Ash258** [comment]
Duplicate of #2921 

Being added in #3054

**Comment by shytikov** [comment]
@Ash258 on #3054 process had stuck a while ago. So I took all code from there, fixed all suggestions, updated to most recent version and submitted new PR.
