### ISSUE TITLE
brackets@1.14.1: decompress error

### ISSUE THREAD

**Issue by lepicsaintloup** [lukesampson/scoop-extras#3329]
```
Extracting Brackets.Release.1.14.1.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\xxxx\scoop\apps\brackets\1.14.1\Brackets.Release.1.14.1.msi.
Log file:
  ~\scoop\apps\brackets\1.14.1\msi.log
```

No log file was created at that location.

**Comment by lepicsaintloup** [comment]
I have now enabled long paths and get a log but still an error
[msi.log](https://github.com/lukesampson/scoop-extras/files/3937230/msi.log)

**Comment by wuya666** [comment]
I have encountered the same issue, the "Enable Win32 long paths" group policy is enabled, but still the MSI extraction reports "Error 1320. The specified path is too long".

**Comment by Mrfiregem** [comment]
Have the same issue. The `LongPathsEnabled` registry key has already been set, but I still get this error.

**Comment by Ash258** [comment]
lukesampson/scoop#3821

Then you must be on lower windows version. 

Only windows 10 come with this settings.

**Comment by Mrfiregem** [comment]
From systeminfo:
```
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18363 N/A Build 18363
```

The error:
```
=== Logging started: 3/11/2020  10:27:19 ===
Error 1320. The specified path is too long: C:\Users\firin\scoop\apps\brackets\1.14.1\_tmp\SourceDir\Brackets\www\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan
=== Logging stopped: 3/11/2020  10:27:33 ===
```

**Comment by rohancragg** [comment]
I get the same error on Microsoft Windows 10 Enterprise (version 1909) Version 10.0.18363 Build 18363

**Comment by Ash258** [comment]
Do you use lessmsi?

Try with `scoop install lessmsi; scoop install MSIEXTRACT_USE_LESSMSI $true` and then install brackets

**Comment by rohancragg** [comment]
```
scoop install MSIEXTRACT_USE_LESSMSI $true
InvalidOperation: C:\Users\rohanc\scoop\apps\scoop\current\lib\getopt.ps1:34
Line |
  34 |          if($arg.startswith('--')) {
     |             ~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [System.Boolean] does not contain a method named 'startswith'.

Couldn't find manifest for 'MSIEXTRACT_USE_LESSMSI'.
```

**Comment by Ash258** [comment]
Sure. Sorry I misplaced config for install. Fixed in original comment.

I think that native msiexec somehow ignore long path by default and needs to be configured (??).

**Comment by Mrfiregem** [comment]
Thanks, setting `MSIEXTRACT_USE_LESSMSI` (already had lessmsi installed) did the trick.
