### ISSUE TITLE
vscode@1.41.0: download via aria2 failed

### ISSUE THREAD

**Issue by kid1412621** [lukesampson/scoop-extras#3341]
vscode: 1.40.2 -> 1.41.0
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Updating one outdated app:
Updating 'vscode' (1.40.2 -> 1.41.0)
Downloading new version
Starting download with aria2 ...
Download: [DL:0B][#99284f 0B/0B][#e8cef3 0B/0B][#d1b727 0B/0B]
Download: 12/14 02:27:51 [ERROR] CUID#10 - Download aborted. URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-uninstall-context.reg
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-uninstall-context.reg
Download:   -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: An existing connection was forcibly closed by the remote host.
Download: (2746)
Download: 12/14 02:27:51 [ERROR] CUID#9 - Download aborted. URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
Download:   -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: An existing connection was forcibly closed by the remote host.
Download: (2746)
Download: [#99284f 0B/0B CN:1 DL:0B]
Download: [#99284f 3.2MiB/82MiB(3%) CN:5 DL:11MiB ETA:6s]
Download: [#99284f 14MiB/82MiB(17%) CN:5 DL:11MiB ETA:6s]
Download: [#99284f 25MiB/82MiB(30%) CN:5 DL:11MiB ETA:5s]
Download: [#99284f 36MiB/82MiB(44%) CN:5 DL:11MiB ETA:4s]
Download: [#99284f 47MiB/82MiB(57%) CN:5 DL:11MiB ETA:3s]
Download: [#99284f 58MiB/82MiB(71%) CN:4 DL:11MiB ETA:2s]
Download: [#99284f 69MiB/82MiB(84%) CN:3 DL:11MiB ETA:1s]
Download: [#99284f 80MiB/82MiB(97%) CN:1 DL:11MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d1b727|ERR |       0B/s|C:/Users/kid14/scoop/cache/vscode#1.41.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-uninstall-context.reg
Download: e8cef3|ERR |       0B/s|C:/Users/kid14/scoop/cache/vscode#1.41.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-install-context.reg
Download: 99284f|OK  |    11MiB/s|C:/Users/kid14/scoop/cache/vscode#1.41.0#https_vscode-update.azurewebsites.net_1.41.0_win32-x64-archive_stable_dl.7z
Download: Status Legend:
Download: (OK):download completed.(ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://vscode-update.azurewebsites.net/1.41.0/win32-x64-archive/stable#/dl.7z
    referer=https://vscode-update.azurewebsites.net/1.41.0/win32-x64-archive/stable#/
    dir=C:\Users\kid14\scoop\cache
    out=vscode#1.41.0#https_vscode-update.azurewebsites.net_1.41.0_win32-x64-archive_stable_dl.7z
https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
    referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
    dir=C:\Users\kid14\scoop\cache
    out=vscode#1.41.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-install-context.reghttps://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-uninstall-context.reg
    referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
    dir=C:\Users\kid14\scoop\cache
    out=vscode#1.41.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-uninstall-context.reg

ERROR & 'C:\ProgramData\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\kid14\scoop\cache\vscode.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/6.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=17912 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=vscode%401.41.0%3a+download+via+aria2+failed

**Comment by outforpublic** [comment]
```
vscode: 1.40.2 -> 1.41.0
WARN Scoop uses 'aria2c' for multi-connection downloads.
WARN Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Updating one outdated app:
Updating 'vscode' (1.40.2 -> 1.41.0)
Downloading new version
Starting download with aria2 ...
Download: [DL:0B][#99284f 0B/0B][#e8cef3 0B/0B][#d1b727 0B/0B]
Download: 12/14 02:27:51 [ERROR] CUID#10 - Download aborted. URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-uninstall-context.reg
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-uninstall-context.reg
Download: -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: An existing connection was forcibly closed by the remote host.
Download: (2746)
Download: 12/14 02:27:51 [ERROR] CUID#9 - Download aborted. URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
Download: -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: An existing connection was forcibly closed by the remote host.
Download: (2746)
Download: [#99284f 0B/0B CN:1 DL:0B]
Download: [#99284f 3.2MiB/82MiB(3%) CN:5 DL:11MiB ETA:6s]
Download: [#99284f 14MiB/82MiB(17%) CN:5 DL:11MiB ETA:6s]
Download: [#99284f 25MiB/82MiB(30%) CN:5 DL:11MiB ETA:5s]
Download: [#99284f 36MiB/82MiB(44%) CN:5 DL:11MiB ETA:4s]
Download: [#99284f 47MiB/82MiB(57%) CN:5 DL:11MiB ETA:3s]
Download: [#99284f 58MiB/82MiB(71%) CN:4 DL:11MiB ETA:2s]
Download: [#99284f 69MiB/82MiB(84%) CN:3 DL:11MiB ETA:1s]
Download: [#99284f 80MiB/82MiB(97%) CN:1 DL:11MiB]
Download: Download Results:
Download: gid |stat|avg speed |path/URI
Download: ======+====+===========+=======================================================
Download: d1b727|ERR | 0B/s|C:/Users/kid14/scoop/cache/vscode#1.41.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-uninstall-context.reg
Download: e8cef3|ERR | 0B/s|C:/Users/kid14/scoop/cache/vscode#1.41.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-install-context.reg
Download: 99284f|OK | 11MiB/s|C:/Users/kid14/scoop/cache/vscode#1.41.0#https_vscode-update.azurewebsites.net_1.41.0_win32-x64-archive_stable_dl.7z
Download: Status Legend:
Download: (OK):download completed.(ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://vscode-update.azurewebsites.net/1.41.0/win32-x64-archive/stable#/dl.7z
referer=https://vscode-update.azurewebsites.net/1.41.0/win32-x64-archive/stable#/
dir=C:\Users\kid14\scoop\cache
out=vscode#1.41.0#https_vscode-update.azurewebsites.net_1.41.0_win32-x64-archive_stable_dl.7z
https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
dir=C:\Users\kid14\scoop\cache
out=vscode#1.41.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-install-context.reghttps://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-uninstall-context.reg
referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
dir=C:\Users\kid14\scoop\cache
out=vscode#1.41.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-uninstall-context.reg

ERROR & 'C:\ProgramData\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\kid14\scoop\cache\vscode.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/6.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=17912 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=vscode%401.41.0%3a+download+via+aria2+failed
```

Just converted it to a code-block for easier reading.

**Comment by outforpublic** [comment]
Looking at it, this seems like a problem from your end. Try the download again, on a different network, or maybe even a different computer because I believe it’s the firewall blocking the connection to github for some reason.

**Comment by kid1412621** [comment]
> Looking at it, this seems like a problem from your end. Try the download again, on a different network, or maybe even a different computer because I believe it’s the firewall blocking the connection to github for some reason.

Ok, I thought vscode been put on Azure server. btw is there any proxy method for scoop?

**Comment by linsui** [comment]
https://github.com/lukesampson/scoop/wiki/Using-Scoop-behind-a-proxy

**Comment by outforpublic** [comment]
> > Looking at it, this seems like a problem from your end. Try the download again, on a different network, or maybe even a different computer because I believe it’s the firewall blocking the connection to github for some reason.
> 
> Ok, I thought vscode been put on Azure server. btw is there any proxy method for scoop?

VSCode IS on the azure server, but looking at the console output, it seems as though its trying to download `https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg` but cant reach it

```
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
Download: -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: An existing connection was forcibly closed by the remote host.
```

**Comment by kid1412621** [comment]
@outforpublic It seems even download finished, error still occurs.
![image](https://user-images.githubusercontent.com/26278054/71320844-2d5a5d00-24ec-11ea-9760-6533be69af37.png)

**Comment by outforpublic** [comment]
Ok, this seems like a bug that needs to be addressed.

**Comment by outforpublic** [comment]
It says there is a log file, could you please attempt to find it and upload it?

**Comment by kid1412621** [comment]
@outforpublic no log, just this 
![image](https://user-images.githubusercontent.com/26278054/72274662-8dfe3500-3667-11ea-8f8b-73af7d3cf613.png)
And this is the txt file:
```
https://vscode-update.azurewebsites.net/1.41.1/win32-x64-archive/stable#/dl.7z
    referer=https://vscode-update.azurewebsites.net/1.41.1/win32-x64-archive/stable#/
    dir=C:\Users\kid14\scoop\cache
    out=vscode#1.41.1#https_vscode-update.azurewebsites.net_1.41.1_win32-x64-archive_stable_dl.7z
https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
    referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
    dir=C:\Users\kid14\scoop\cache
    out=vscode#1.41.1#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-install-context.reg
https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-uninstall-context.reg
    referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
    dir=C:\Users\kid14\scoop\cache
    out=vscode#1.41.1#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-uninstall-context.reg


```
