### ISSUE TITLE
SumatraPDF@3.1.2: hash check failed

### ISSUE THREAD

**Issue by voiov** [lukesampson/scoop-extras#3344]
PS C:\Users\silen> scoop install SumatraPDF
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'SumatraPDF' (3.1.2) [64bit]
Loading SumatraPDF-3.1.2-64.zip from cache.
Checking hash of SumatraPDF-3.1.2-64.zip ... ERROR Hash check failed!
App:         extras/SumatraPDF
URL:         https://www.sumatrapdfreader.org/dl/SumatraPDF-3.1.2-64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    3c07b3fe267251d32a17f67ed5070018d69c8436df33e6db3ce757889b734676
Actual:      ddbf1477d401d6429e7a409ff5d048836f4a43a329229f01e6ba589b4907c726

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=SumatraPDF%403.1.2%3a+hash+check+failed

**Comment by Ash258** [comment]
Cannot reproduce from 4 different location.

`scoop cache rm sumatrapdf; scoop update SumatraPDF -f`

![A](https://i.imgur.com/6y6GPqu.png)
