### ISSUE TITLE
基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系

### ISSUE THREAD

**Issue by yanglk2010** [lukesampson/scoop-extras#3354]
![image](https://user-images.githubusercontent.com/14232815/70907708-7fab0200-2044-11ea-9eb7-524c45b81b1d.png)

**Comment by xycui** [comment]
Works for me. Maybe DNS issue?

**Comment by yanglk2010** [comment]
> Works for me. Maybe DNS issue?
Maybe, i'll try again!
