### ISSUE TITLE
typora@0.9.81: download via aria2 failed

### ISSUE THREAD

**Issue by xycui** [lukesampson/scoop-extras#3389]
![image](https://user-images.githubusercontent.com/2989428/71320138-2c243280-24e2-11ea-991e-3a6a498c2cd0.png)

I have tried cleanup the cache. But not working.

**Comment by issaclin32** [comment]
It works for me.  Maybe their website was down when you was installing it.  You can try install again.

**Comment by xycui** [comment]
> It works for me. Maybe their website was down when you were installing it. You can try install again.
Interesting. It works now. Maybe it is caused by unstable networking.

**Comment by jku1995** [comment]
> Interesting. It works now. Maybe it is caused by unstable networking.

mainland of China pollute DNS,I use extras/dnsJumper change to google dns and it works

**Comment by xycui** [comment]
> > Interesting. It works now. Maybe it is caused by unstable networking.
> 
> mainland of China pollute DNS,I use extras/dnsJumper change to google dns and it works

Appreciate for your info.
