### ISSUE TITLE
vnote@2.8.2: hash check failed

### ISSUE THREAD

**Issue by yh-cs** [lukesampson/scoop-extras#3442]

**Comment by yh-cs** [comment]
![image](https://user-images.githubusercontent.com/32333034/71705058-96a96c80-2e18-11ea-89b5-364899b3e3b6.png)

**Comment by Ash258** [comment]
Cannot reproduce.

`scoop cache rm vnote; scoop update vnote -f`

![image](https://user-images.githubusercontent.com/13260377/71717468-7ed1e880-2e18-11ea-9390-28608fcfb48a.png)
