### ISSUE TITLE
markdown-monster@1.20.8.1: hash check failed

### ISSUE THREAD

**Issue by spjansen** [lukesampson/scoop-extras#3445]
C:\Users\admin\Documents>scoop update -g markdown-monster freecommander
markdown-monster: 1.20.7.6 -> 1.20.8.1 (global)
freecommander: 2019.790a -> 2020.810 (global)
Updating 2 outdated apps:
Updating 'markdown-monster' (1.20.7.6 -> 1.20.8.1)
Downloading new version
MarkdownMonsterPortable.zip (21,0 MB) [=============================================================================================================================================] 100%
Checking hash of MarkdownMonsterPortable.zip ... ERROR Hash check failed!
App:         extras/markdown-monster
URL:         https://west-wind.com/files/MarkdownMonsterPortable.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    a922baf51225e5e0281ebaabc716caa779a974772c9cad584cd94a3047230912
Actual:      c74532ce96a2cad618b82e0aafe66fbfa9d385ec5ed72fd6c0c4f595cc7981c5

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=markdown-monster%401.20.8.1%3a+hash+check+failed

**Comment by spjansen** [comment]
I did try again before creating this issue, same error. Hash check failed
Actual: c74532ce96a2cad618b82e0aafe66fbfa9d385ec5ed72fd6c0c4f595cc7981c5

**Comment by Ash258** [comment]
Supressed by 94dd45805c0859cc6cb111f7277d22114d4c775e

`scoop update; scoop update markdown-monster -f`

**Comment by spjansen** [comment]
'markdown-monster' (1.20.8.3) was installed successfully!
thanks, ash!
