### ISSUE TITLE
Package has new version but scoop doesnt update it.

### ISSUE THREAD

**Issue by OdinTech3** [lukesampson/scoop-extras#3448]
The Typora package has a new version but scoop can't update it

![image](https://user-images.githubusercontent.com/14257815/71736642-9365af00-2e1f-11ea-9991-6d63b66186cd.png)

How can this be fixed?

**Comment by Ash258** [comment]
`scoop update typora -f`

**Comment by OdinTech3** [comment]
Awesome it worked, Grazie Tanto!!!

Hmmm... I didn't know of that flag. I tried to run 
`scoop update --help` and `scoop update -h` and even `scoop update -?` but didn't get any sort of man page

**Comment by Ash258** [comment]
`scoop` => `scoop help` => `scoop help update`

**Comment by OdinTech3** [comment]
Ahhhh I seee, sorry i was thinking the Unix way of doing things.
