### ISSUE TITLE
keepassxc: Settings are not persisted

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [lukesampson/scoop-extras#3459]
On update from 2.5.1 to 2.5.2, my settings were not persisted.
An instance was running before I updated, fwiw.

**Comment by r15ch13** [comment]
This was fixed in https://github.com/lukesampson/scoop-extras/pull/3162 (version 2.5.1) and should work from 2.5.2 onwards. Please copy your `keepass.ini` manually to the `~\scoop\apps\keepassxc\current` directory.

**Comment by r15ch13** [comment]
Oh, there is the error!
KeePassXC uses `keepassxc.ini`, but in the PR `keepass.ini` was used.
