### ISSUE TITLE
Add NetTraffic

### ISSUE THREAD

**Issue by wenmin92** [lukesampson/scoop-extras#3460]
[NetTraffic](https://www.venea.net/web/nettraffic_portable) is an essential network bandwidth usage monitor.
It seems can not download from outside, someone can help with this?

The [download page](https://www.venea.net/web/downloads_start/nettraffic_portable) says:
> If the download doesn't start automatically, please use this direct link. Do not use any downloader plugin or external downloading software. Disable page translation.

**Comment by issaclin32** [comment]
You can try check new versions (`checkver`) from its official site, and download the file (`autoupdate`) from another site.

The download URLs in [TechSpot](https://www.techspot.com/) seems usable.

```
https://files02.tchspt.com/storage2/temp/NetTraffic1.64.0.zip
https://files02.tchspt.com/storage2/temp/NetTraffic1.63.0.zip
https://files02.tchspt.com/storage2/temp/NetTraffic1.62.0.zip
```

There are some packages in the *extras* bucket are using this approach, such as [Foobar2000](https://github.com/lukesampson/scoop-extras/blob/master/bucket/foobar2000.json) and [MSI Afterburner](https://github.com/lukesampson/scoop-extras/blob/master/bucket/msiafterburner.json)

**Comment by wenmin92** [comment]
Thanks, help a lot. 😄

**Comment by wenmin92** [comment]
Well, at the TechSpot site, I found the [NetTraffic page](https://www.techspot.com/downloads/6058-nettraffic.html), but didn't find download url as you showed.
I found this url:
`https://www.techspot.com/downloads/downloadnow/6058/?evp=5b6b7076d30b3f85cb982d8752e0a663&file=`
How to get the static url `https://files02.tchspt.com/storage2/temp/NetTraffic1.64.0.zip`?

**Comment by issaclin32** [comment]
You will find the url in the *download tab* of your browser.
![dl](https://user-images.githubusercontent.com/27724471/71813766-7ea24900-30b5-11ea-98b7-f6e3f55ad911.png)

**Comment by wenmin92** [comment]
Oh, Thank you. 😅 
I used Chrono Download Manager plugin, and it didn't show the real url.
