### ISSUE TITLE
mpv@0.31.0: hash check failed

### ISSUE THREAD

**Issue by mykolan** [lukesampson/scoop-extras#3461]
Checking hash of mpv-0.31.0-x86_64.7z ... Resolve-Path : Cannot find path 'C:\Users\М\scoop\cache\mpv#0.31.0#https_downloads.sourceforge.net_project_mpv-player-windows_stable_mpv-0.31.0-x86_64.7z' because it d
oes not exist.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1:110 char:36
+                 $pathsToProcess += Resolve-Path $Path | Foreach-Objec ...
+                                    ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\М\scoo....31.0-x86_64.7z:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

ERROR You cannot call a method on a null-valued expression.
ERROR Hash check failed!
App:         extras/mpv
URL:         https://downloads.sourceforge.net/project/mpv-player-windows/stable/mpv-0.31.0-x86_64.7z
Expected:    93bff060e015384292118ae2fb5a07c5b7510d21
Actual:

**Comment by Ash258** [comment]
Your antivirus or something similar has to delete downloaded file.
