### ISSUE TITLE
The exact "+" sign would be decoded as a space

### ISSUE THREAD

**Issue by sinloss** [lukesampson/scoop-extras#3490]
Hi all.
I got into this issue while submitting #3489 which involves the `+` sign. Idk why but the `flutter team` did use an exact `+` sign in the releases. And when I changed the `checkver` in order to support the `+` sign and tried to `autoupdate` it, then I got a stubborn error. 

After some debugging... It turns out that the `[System.Web.HttpUtility]::UrlDecode` method in `lib/autoupdate.ps1` line `175` unexpectedly ( yet reasonable ) decoded the `+` of the `$basename` variable to an empty space. Hence the jsonpath `$.releases[?(@.archive =~ /.*$basename/)].sha256` failed

Now that the cause of this issue is clear, may I ask if we could just replace all the `+` in the `$basename` part of the URL with a `%2B` before decoding it or provide a better approach to cope with similar situations?

* *Are there some more special characters that may lead people into this trap*?
* *Will the replacing `+` with `%2B` harm the other logics*?
* *Is there a possibility that some apps do use `+` to represent a space*?

Any ideas?

**Comment by linsui** [comment]
See https://github.com/lukesampson/scoop/pull/3721
