### ISSUE TITLE
keystore-explorer 5.4.2 - Shim not working

### ISSUE THREAD

**Issue by ither** [lukesampson/scoop-extras#3499]
When I try to start keystore-explorer from the command line using the shim "kse", it shows a dialog saying "This application requires a Java Runtime Environment 1.8.0" even when I have Java 8 installed and in the PATH global variable. Is there something more I can check to diagnose better the problem? I don't really understand how the shims works, anyway. Thanks in advance.

**Comment by issaclin32** [comment]
I cannot reproduce the problem. Does the problem happens **only** when you run the program by shim-exe? or does it also happen when you run the program by shortcuts?

**Comment by issaclin32** [comment]
This may be related to the registry. 

You can try save the following content as  **java.reg**, and apply the registry file.

Replace `(YOUR JAVA PATH)` with your Java path, such as `C:\Users\W10T1\scoop\apps\adopt8-hotspot-jre\8u232-b09`

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment]
"CurrentVersion"="1.8"
"BrowserJavaVersion"="11.232.2"

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\1.8]
"RuntimeLib"="(YOUR JAVA PATH)\\bin\\server\\jvm.dll"
"JavaHome"="(YOUR JAVA PATH)"
"MicroVersion"="0"
```

**Comment by ither** [comment]
Ok, with that it works. Thanks.
