### ISSUE TITLE
flashplayer-sa@32.0.0.314: hash check failed

### ISSUE THREAD

**Issue by jxxkvs** [lukesampson/scoop-extras#3505]
Checking hash of flashplayer_32_sa.exe ... ERROR Hash check failed!
App:         extras/flashplayer-sa
URL:         https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flashplayer_32_sa.exe#/flashplayer.exe
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    7b65b3b37b060f84696633168d62eaa0b053ec289ce01b4097997de861cd5434
Actual:      a49b50b4e776a02dfcc1b1726c0f5fd1639cb4b4fb7f7b111cc5e9a676ad6ae9

**Comment by Ash258** [comment]
Cannot reproduce.

![image](https://user-images.githubusercontent.com/13260377/72620132-fcc8e000-393e-11ea-8b5a-e41e51e493b7.png)
