### ISSUE TITLE
keepassxc: Settings are not persisted (again)

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [lukesampson/scoop-extras#3514]
On update from 2.5.2 to 2.5.3, my settings were not persisted.

This was supposedly fixed in https://github.com/lukesampson/scoop-extras/commit/ee6f022c8f800c99e9f5bfb8ecbf1914963dc6fd, but something is still going on here.

**Comment by Ash258** [comment]
Did you reinstal after fix?

**Comment by Ash258** [comment]
If keepassxc behave same as normal keepass, then persist using link will not work as normal keepass is recreating file on each change. THen you need to use copy over method

23c818386fa737cb516eacb50908b2a32550734b

**Comment by ThatNerdyPikachu** [comment]
> Did you reinstal after fix?

Yup.

> If keepassxc behave same as normal keepass, then persist using link will not work as normal keepass is recreating file on each change. THen you need to use copy over method

It probably isn't the same, I don't think they share any code at all(?, pls correct)

**Comment by ThatNerdyPikachu** [comment]
@Ash258 I'd be happy to contribute a fix for this if I knew how to "fake" an update.

**Comment by linsui** [comment]
Just uninstall and reinstall is enough.
