### ISSUE TITLE
libreoffice-fresh@6.4.0.3: Download failed

### ISSUE THREAD

**Issue by habamax** [lukesampson/scoop-extras#3561]
![image](https://user-images.githubusercontent.com/234774/73745440-1605c500-4764-11ea-8c31-904e71a02d01.png)

**Comment by Ash258** [comment]
You most likely hit redirect from https to http mirror, which is not valid in powershell.

You have two options

1. Change URL in manifest and replace `https` with `http`
1. Download the file via browser, move it into cache folder and rename accordingly.

**Comment by habamax** [comment]
Is it permanent issue with libreoffice fresh and I should do it for every new version?

**Comment by Ash258** [comment]
This is general Apache issue that their mirrors are going down frequently and lots of them are not https compatible.

Just use aria2 for these and you should be fine.

**Comment by habamax** [comment]
> Just use aria2 for these and you should be fine.

Thx! Do you mean to somehow incorporate aria2 into scoop? Or manually download libreoffice?

**Comment by Ash258** [comment]
`scoop install aria2; scoop update libreoffice-fresh -f; scoop config aria2-enabled $false` will take care of update and disable aria2. You can reenable it next time you need it.

**Comment by habamax** [comment]
@Ash258 amaizing! Thx!
