### ISSUE TITLE
potplayer 200204: 404

### ISSUE THREAD

**Issue by rasa** [lukesampson/scoop-extras#3573]
```
$ scoop install potplayer
Installing 'potplayer' (200204) [64bit]
The remote server returned an error: (404) Not Found.
URL https://t1.daumcdn.net/potplayer/PotPlayer/Version/20200204/PotPlayerSetup64.exe#/dl.7z is not valid

**Comment by Ash258** [comment]
Ash258/Scoop-Ash258@747ccb04e357c2844ee72c34aed4c11ee7f60892

**Comment by rasa** [comment]
Sorry,  I forgot it was from your bucket!

**Comment by Ash258** [comment]
No it is here, but I just could not fix it by myself here as I do not have my automatic response daemon/bot running for extras

I will fix it here too
