### ISSUE TITLE
totalcommander@9.50: Hash check failed

### ISSUE THREAD

**Issue by wolfgang-github** [lukesampson/scoop-extras#3585]
Updating 'totalcommander' (9.22a -> 9.50)
Downloading new version
tcmd950x64.exe (2.4 KB) [=====================================================================================] 100%
Checking hash of tcmd950x64.exe ... ERROR Hash check failed!
App:         extras/totalcommander
URL:         http://totalcommander.ch/win/tcmd950x64.exe
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    a84cb6a6bb00353b8ec10bf078a83ec0f5badb5841ea36c1a8dce3c36ffb4d9b
Actual:      eee5b0af414bf93219f714bdd0434e208b5bcac50f25b12e418c670734ea891f

**Comment by Ash258** [comment]
Based on the size of downloaded file you downloaded webpage. If you open the downloaded file in text editor it will show that you have this page blocked (by firewall/anything)

Cannot reproduce from 4 different geo locations

![image](https://user-images.githubusercontent.com/13260377/74225096-59a78400-4cba-11ea-8592-c734279a74e4.png)
