### ISSUE TITLE
Incorrect notes on `mpv`

### ISSUE THREAD

**Issue by kidonng** [lukesampson/scoop-extras#3587]
https://github.com/lukesampson/scoop-extras/blob/master/bucket/mpv.json#L28-L29

`mpv-git` releases come with install scripts, but not stable ones.

Perhaps this should be reported to those who make Windows builds (upstream) to contain the scripts in future stable builds?

**Comment by dsbert** [comment]
It looks like the `stable` releases do not include the scripts but the x64 releases do.

https://sourceforge.net/projects/mpv-player-windows/files/64bit/
