### ISSUE TITLE
googlechrome@80.0.3987.87: download via aria2 failed

### ISSUE THREAD

**Issue by hyber-code** [lukesampson/scoop-extras#3590]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://dl.google.com/release2/chrome/APwT_PugZs0Rf9lGhVkF3QA_80.0.3987.87/80.0.3987.87_chrome_installer.exe#/dl.7z
    referer=https://dl.google.com/release2/chrome/APwT_PugZs0Rf9lGhVkF3QA_80.0.3987.87/80.0.3987.87_chrome_installer.exe#/
    dir=C:\Users\SA\scoop\cache
    out=googlechrome#80.0.3987.87#https_dl.google.com_release2_chrome_APwT_PugZs0Rf9lGhVkF3QA_80.0.3987.87_80.0.3987.87_chrome_installer.exe_dl.7z

ERROR & 'C:\Users\SA\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\SA\scoop\cache\googlechrome.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=4564 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=googlechrome%4080.0.3987.87%3a+download+via+aria2+failed

**Comment by Ash258** [comment]
Cannot reproduce. Installation without issue

![A](https://i.imgur.com/RFxy24k.png)

![B](https://i.imgur.com/fz3bi0u.png)

**Comment by hyber-code** [comment]
![image](https://user-images.githubusercontent.com/18413990/74619465-6a8f4400-5157-11ea-87c6-9950bed3eaa5.png)
