### ISSUE TITLE
linqpad@6.5: hash check failed

### ISSUE THREAD

**Issue by daniel-liuzzi** [lukesampson/scoop-extras#3626]
## Console output

```
Installing 'linqpad' (6.5) [64bit]
LINQPad6.zip (26.1 MB) [========================================================================================================] 100%
Checking hash of LINQPad6.zip ... ERROR Hash check failed!
App:         extras/linqpad
URL:         http://download.linqpad.net/public/LINQPad6.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    206117f5b72e4070608200c40784c3bd7852e5dae0788e4caccf0509df931359
Actual:      1fe87bb58f25c03353b2509bfebebecd1b156b2afa2c39f3138354bfa342ecc5

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=linqpad%406.5%3a+hash+check+failed
```

**Comment by daniel-liuzzi** [comment]
@Ash258 thank you for such a quick fix!

Also, what do I need to do in order for scoop to see the new hash? When I try installing LINQPad, it still expects 206117f5b72e4070608200c40784c3bd7852e5dae0788e4caccf0509df931359.

**Comment by Ash258** [comment]
`scoop cache rm linqpad; scoop update linqpad -f`

**Comment by daniel-liuzzi** [comment]
OK, so I did that. `scoop cache rm linqpad` worked, but `scoop update linqpad -f` did not (got a `ERROR 'linqpad' isn't installed.`) error.

If I try `scoop install linqpad` again, I still get the hash check error.

**Comment by Ash258** [comment]
Did you run `scoop update` to get latest manifest changes?

**Comment by daniel-liuzzi** [comment]
That did the trick. Thanks a lot!
