### ISSUE TITLE
everything@1.4.1.965: hash check failed

### ISSUE THREAD

**Issue by cwm12138** [lukesampson/scoop-extras#3641]
Checking hash of Everything-1.4.1.965.x64.zip ... ERROR Hash check failed!
App:         extras/everything
URL:         https://www.voidtools.com/Everything-1.4.1.965.x64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    b2afe2fd0c239ac9688f5897b096823293cc38c1f629ee2d39b3230c2be3e792
Actual:      052ae9869118fad0db403057a875d34e89772d062d68460287af3db001ab8ba1

**Comment by lcgf521lhf** [comment]
Me,too.
