### ISSUE TITLE
everything@1.4.1.965: hash check failed

### ISSUE THREAD

**Issue by lcgf521lhf** [lukesampson/scoop-extras#3643]
![image](https://user-images.githubusercontent.com/13299908/75737201-234da980-5d3a-11ea-8689-bf407047f63d.png)
i have try this several times,but it failed as well.

**Comment by lcgf521lhf** [comment]
If i download it from home website and put it in cache folder.It would get another response.
![image](https://user-images.githubusercontent.com/13299908/75737508-ddddac00-5d3a-11ea-86de-cf7d9b5b0e4c.png)

**Comment by iovw** [comment]
me too.
