### ISSUE TITLE
PSPad Wrong Version

### ISSUE THREAD

**Issue by ither** [lukesampson/scoop-extras#3649]
I have installed PSPad through Scoop and shows it as version 5.0.3 but when I start the program, it tells me that it is available a newer version. Using the Help/About option show that version 5.0.1 is installed.

**Comment by Ash258** [comment]
No it is not. Freshly installed pspad is correct 5.0.3

![image](https://user-images.githubusercontent.com/13260377/75908932-5cc20a00-5e4b-11ea-8f0e-3cfb7ee7c4d3.png)

https://github.com/lukesampson/scoop-extras/blob/64205f28db2a90205f6f45078ef129bde5f0e49b/bucket/pspad.json#L8-L10
