### ISSUE TITLE
powertoys cannot use PowerRename 

### ISSUE THREAD

**Issue by fungtion** [lukesampson/scoop-extras#3650]
Hi, I installed powertoys using scoop, and cannot see the PowerRename in the right-click context menu, while everything is fine when installing using MSI. If this is because of the portable version in scoop?

**Comment by mark05e** [comment]
it could be the case. hopefully in future releases it should not depend on registry entries.

https://github.com/microsoft/PowerToys/issues/1206

**Comment by olof-nord** [comment]
> 
> 
> it could be the case. hopefully in future releases it should not depend on registry entries.
> 
> [microsoft/PowerToys#1206](https://github.com/microsoft/PowerToys/issues/1206)

With that issue closed and fixed with v.0.17, can this issue also be closed?

I just installed powertoys, and got version `0.21.1`.
