### ISSUE TITLE
[Request] Add GOG Galaxy

### ISSUE THREAD

**Issue by superusercode** [lukesampson/scoop-extras#3659]
I've seen it in a bunch of user-created buckets but as 2.0 approaches a stable release (currently in public beta) I think this should be considered for the scoop-extras bucket.

see https://www.gog.com/galaxy

**Comment by Ciberbago** [comment]
Hello, I'm sorry for commenting on this after is closed. But it says it is completed, even though I cannot find gog galaxy in any of the scoop buckets :(
Can you point me in the right direction?
