### ISSUE TITLE
Apps request & version bumps

### ISSUE THREAD

**Issue by ridjis** [lukesampson/scoop-extras#366]
Don't if this is right place to request but should be fine to add [Audacity](http://www.audacityteam.org/) and [Cmder mini](http://cmder.net/).

For robomongo there is [1.0.0-rc1 version](https://robomongo.org/download).
And for eclipse-ee there is [Eclipse Neon](http://www.eclipse.org/neon/), latest of Eclipse products, so you can consider replacement.

**Comment by lukesampson** [comment]
We usually stick to stable versions, although you could add the robomongo RC1 to the [versions](https://github.com/scoopinstaller/versions/) bucket if you like.

I'm not too familiar with the Java world, so I won't try to do Eclipse Neon, although it looks like a worthy addition. Feel free to submit a pull request if you like!

**Comment by r15ch13** [comment]
Audacity, cmder and eclipse have been added.
