### ISSUE TITLE
potplayer@200204: download via aria2 failed

### ISSUE THREAD

**Issue by WisdomKwan** [lukesampson/scoop-extras#3661]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://t1.daumcdn.net/potplayer/PotPlayer/Version/200204/PotPlayerSetup64.exe#/dl.7z
    referer=https://t1.daumcdn.net/potplayer/PotPlayer/Version/200204/PotPlayerSetup64.exe#/
    dir=D:\Users\Root\Scoop\cache 
out=potplayer#200204#https_t1.daumcdn.net_potplayer_PotPlayer_Version_200204_PotPlayerSetup64.exe_dl.7z

ERROR & 'D:\Library\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Users\Root\Scoop\cache\potplayer.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=13768 --continue

**Comment by Ash258** [comment]
Cannot reproduce either with/without aria2 enabled
