### ISSUE TITLE
Trojan in Calibre ?

### ISSUE THREAD

**Issue by g-berthiaume** [lukesampson/scoop-extras#3669]
Calibre-portable is detected as a trojan by Bitdefender. 
Is it a false positive ?

![image](https://user-images.githubusercontent.com/19377511/76165027-f9c1c300-6129-11ea-83a2-f3796d7d5cb8.png)

Regards

**Comment by Dabombber** [comment]
Yes, you might need to update bitdefender.
> \> scoop virustotal calibre
> calibre: 0/70, see https://www.virustotal.com/#/file/a41a488a3e1703088d968e8e75d50441ce7e06288a217532ef802573bb367732/detection

[Calibre FAQ](https://manual.calibre-ebook.com/faq.html#my-antivirus-program-claims-calibre-is-a-virus-trojan)

**Comment by g-berthiaume** [comment]
Thanks for the followup.
