### ISSUE TITLE
[Request] Tftpd64 / Tftpd32

### ISSUE THREAD

**Issue by mark05e** [lukesampson/scoop-extras#3673]
Tftpd64 is a free, opensource IPv6 ready application which includes DHCP, TFTP, DNS, SNTP and Syslog servers as well as a TFTP client.

http://tftpd32.jounin.net/tftpd32_download.html

**Comment by rasa** [comment]
If these are cli apps, perhaps they should live in the main bucket?

**Comment by mark05e** [comment]
This is a GUI app.

![Tftpd64 GUI](http://tftpd32.jounin.net/images/working_tftpd32.jpg)
