### ISSUE TITLE
Error while installing Audacity

### ISSUE THREAD

**Issue by ridjis** [lukesampson/scoop-extras#368]
![image](https://cloud.githubusercontent.com/assets/11313640/24081010/cf06a13e-0caa-11e7-9c31-8c07b3251448.png)

And seems like that provided majorgeeks audacity download link is dynamically generated so one thats in audacity.json is not working anymore.

**Comment by r15ch13** [comment]
Not so fast Luke, i found a good site:
https://fossies.org/windows/misc/

**Comment by lukesampson** [comment]
Thanks @r15ch13, I've updated.

I'm not sure what the innounp error is—it installs fine for me and I don't recognize where the error is coming from. Innounp isn't required for the newest Audacity install though.

**Comment by r15ch13** [comment]
Download doesn't work either... The Referer-Header has to be `https://fossies.org/windows/misc/audacity-win-2.1.3.zip/` ...

**Comment by lukesampson** [comment]
Argh. It works for... maybe it recognises my IP from loading the page in a browser? Any idea how to fix? I'm ready to let this one go.

**Comment by r15ch13** [comment]
We could add the referer header to all requests. This should not effect other sites, because the browser sends it anyway.
