### ISSUE TITLE
Teamviewer hash issue when it is downloaded in China

### ISSUE THREAD

**Issue by sinloss** [lukesampson/scoop-extras#3680]
Hi, all!

As I recently tried to submit a pr #3678 to fix the issue I've encountered ( *or maybe someone else has encountered as well, say #3676* ) which is a tiny hash mismatch issue of `Teamviewer`. It turns out that @Dabombber @Ash258 and the `bot` are all free from this issue.

According to the screenshot provided by @Ash258, I did some investigation. And here are some facts I've found
* If I download the teamviewer.zip using a proxy (*which bridges to a server located in **California***), the `sha256sum` of the file is identical to the hash stated in the `manifest.json`
![image](https://user-images.githubusercontent.com/4133131/76397974-04dd5300-63b7-11ea-962b-6a69a5501a03.png)
* If I download it without the proxy, that is downloading directly (*and I myself is located in **China***), then I'll get a different hash
![image](https://user-images.githubusercontent.com/4133131/76398297-9c42a600-63b7-11ea-97cc-80464f13d9e1.png)
![image](https://user-images.githubusercontent.com/4133131/76398353-b41a2a00-63b7-11ea-9b3b-c2c15ab27893.png)

I may assume that the Teamviewer I downloaded in **China** might have been specially treated by the Teamviewer team. 

So, should I submit a special version of `teamviewer.json` (*which should not be auto-updated from outside **China**, since the hash generated from outside **China** will not work in **China***)

**Comment by Ash258** [comment]
If you are sure the file is correct then install it with skip parameter.

`scoop install teamviewer -s` And installation will continue even with hash mismatch.

There is no reason for extras bucket to handle it (same as #3280 ). If you want custom use custom generated manifest, but fastest way is to install it with skip.
