### ISSUE TITLE
quiterss: cannot open sqlite database

### ISSUE THREAD

**Issue by vuongggggg** [lukesampson/scoop-extras#3681]
https://github.com/lukesampson/scoop-extras/blob/f75081c452d7675e3aa132581e53aebbe71b5d5a/bucket/quiterss.json#L17

After install, I got this message when try opening.
```
Cannot open SQLite database!
Error: unable to open database file Error opening database
```
I've deleted `feeds.db` then it works. The installation has persisted `feeds.db` as folder, but it seems no need. I also curious how if the new version updated, does it still keep current database file in new updated app when open?

Could please help to check? 
Thanks!

**Comment by Ash258** [comment]
Please reinstall/force update quiterss
