### ISSUE TITLE
[Issue] Firefox-developer version updates ALWAYS require --force to be installed

### ISSUE THREAD

**Issue by LoZeno** [lukesampson/scoop-extras#3687]
See this:
https://github.com/lukesampson/scoop/issues/3876

essentially, the version number parsing doesn't work anymore with firefox-developer's format (Major.minor[b]betaversion).
Running `scoop update` and `scoop status` does not notify the user of a new version of firefox-developer, even when present, if the change in version number is only on the last beta version number.
Moreover, running `scoop cleanup firefox-developer` breaks the `/current/` folder junction. Example follow:

install firefox-developer@75.0b1, firefox-developer@75.0b2 and firefox-developer@75.0b3, in this order. `/current/` will point to 75.0b3
Now run `scoop cleanup`: only 75.0b1 will be left, but `/current/` will still point to a (non-existant) 75.0b3

**Comment by Ash258** [comment]
lukesampson/scoop#3721

Nonse to open issue here
