### ISSUE TITLE
potplayer@200317: hash check failed

### ISSUE THREAD

**Issue by unbright** [lukesampson/scoop-extras#3737]
Checking hash of PotPlayerSetup64.exe ... ERROR Hash check failed!
App:         extras/potplayer
URL:         https://t1.daumcdn.net/potplayer/PotPlayer/Version/200317/PotPlayerSetup64.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    2f187b1ba9d15619f6943c17c43c53aa0c096ef90494b166511819604acc91b0
Actual:      3226a7adbb4f6d182290258cb299ed165fac30ec29b9f5dacaeb3c8b9b7b70e8

**Comment by ssfjhh** [comment]
I have got a same error.

**Comment by ssfjhh** [comment]
`Updating 'potplayer' (200204 -> 200317)
Downloading new version
PotPlayerSetup64.exe (27.4 MB) [==============================================================================] 100%
Checking hash of PotPlayerSetup64.exe ... ERROR Hash check failed!
App:         extras/potplayer
URL:         https://t1.daumcdn.net/potplayer/PotPlayer/Version/200317/PotPlayerSetup64.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    3226a7adbb4f6d182290258cb299ed165fac30ec29b9f5dacaeb3c8b9b7b70e8
Actual:      6b578e65262a4bfd2450714ff6a45749d388dbf59a5cbbc40ad8c16b8eb9cdf8`

There must be something wrong.

**Comment by Ash258** [comment]
Then open other issue with proper name and it will be checked. Potplayer change artifacts in first 5 days after release. This is known.
