### ISSUE TITLE
Transmission missing VCRUNTIME140.dll

### ISSUE THREAD

**Issue by e2xistz** [lukesampson/scoop-extras#375]
On a new install of Windows 10 Home, after scoop install transmission, transmission won't start.

Popup dialog says VCRUNTIME140.dll is missing.

**Comment by r15ch13** [comment]
You can now install Microsoft Visual C++ Redistributable Packages via Scoop (https://github.com/lukesampson/scoop-extras/commit/42c230cbf6b9e3314d9d3e9e1771b408dfabf190).
Run `scoop update` and install `scoop install vcredit2017` or `scoop install vcredist` to install all versions from 2008 until 2017
