### ISSUE TITLE
potplayer symlinked persisting extension folder spelled wrong

### ISSUE THREAD

**Issue by DessertArbiter** [lukesampson/scoop-extras#3764]
![image](https://user-images.githubusercontent.com/12720300/77500140-88bd2380-6e2a-11ea-9528-0c4d164d47e6.png)
the names of both the symlink and the folder it points to in persist are spelled wrong, so the folder that is used is getting overwritten every update

**Comment by Ash258** [comment]
#3056

> added relevant folders to persist (note that "Extention" is indeed not my typo)

The folder name is correct. Or last it was on manifest addition.

**Comment by DessertArbiter** [comment]
I just checked and PotPlayer is definitely only looking in the folder with "Extension" spelled correctly

**Comment by DessertArbiter** [comment]
i edited my reply to include more info, not sure if github notifies of edits to issues
