### ISSUE TITLE
archwsl update deletes existing installation including the entire filesystem

### ISSUE THREAD

**Issue by pluth** [lukesampson/scoop-extras#3800]
rip

**Comment by TheWiresharkGuy** [comment]
For me it does not delete the persistent rootfs but it fails the update

See https://github.com/lukesampson/scoop-extras/pull/1877#issuecomment-607688487

**Comment by Esgariot** [comment]
Just to be clear: Is this issue related to updating `archwsl` from Arch itself or generally?

**Comment by tcztzy** [comment]
Maybe this [wiki](How-to-Use(for-Installed-Instance)) help you.

**Comment by escape0707** [comment]
This happens to me today, when updating to 20.10.31.0.

**Comment by bartlibert** [comment]
The really strange thing is that I had held archwsl from update just to
prevent this, but this update went through nonetheless.

Op di 3 nov. 2020 om 07:45 schreef Escape0707 <notifications@github.com>:

**Comment by escape0707** [comment]
@bartlibert Although that a complete different issue, I'm still wondering about how is that possible?

**Comment by akuntsch** [comment]
Same thing happened to me when updating to 20.10.31.0.

I reckon the problem is the uninstaller script running `Arch.exe -clean` which is also run when updating.

**Comment by rasa** [comment]
It certainly isn’t intuitive to a package author that uninstall is called when an app is being updated. I will update the wiki.
