### ISSUE TITLE
archwsl update executed in Arch completely breaks the installation

### ISSUE THREAD

**Issue by Esgariot** [lukesampson/scoop-extras#3810]
When I run `scoop update archwsl` from Arch itself the process crashes and leaves the distro broken. Files are there but one needs to somehow manually re-register leftover files as distro. Reinstallation doesn't help because it overwrites persisted `data` folder. A check for distro running before updating would be needed but I'm not sure how to identify which distro might be the one executing scoop from `wsl(config).exe` output.

**Comment by Ash258** [comment]
Duplicate of #3800
