### ISSUE TITLE
[Request] Add flipper

### ISSUE THREAD

**Issue by M4RC3L05** [lukesampson/scoop-extras#3824]
Home page: https://fbflipper.com/
Download (github releases): https://github.com/facebook/flipper/releases

> Flipper is a platform for debugging iOS, Android and React Native apps. Visualize, inspect, and control your apps from a simple desktop interface. Use Flipper as is or extend it using the plugin API.

**Comment by digrouz** [comment]
see #3945

**Comment by M4RC3L05** [comment]
Should i close the issue, or wait the pull request to be merged?
