### ISSUE TITLE
[Update] Anydesk 5.5.2

### ISSUE THREAD

**Issue by mark05e** [lukesampson/scoop-extras#3830]
Current release on website: 5.5.2
https://download.anydesk.com/changelog.txt
SHA256: D3B606E08C524995B585D6649183387068EE1DDA60DC7E11C950966A7E73F234

Present version on the bucket: 5.4.2

**Comment by Ash258** [comment]
Updated yesterday to 5.5.3

eb4a802e644f5038eb2b494e0d1d25974f521dfb

**Comment by mark05e** [comment]
thanks.
