### ISSUE TITLE
Brave 80.1.5.115 cannot start

### ISSUE THREAD

**Issue by quantuumsnot** [lukesampson/scoop-extras#3832]
Message Box when starting:
> D:\scoop\apps\brave\current\brave.exe
> 
> The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

---
In the `Event Viewer`:

> Activation context generation failed for "D:\scoop\apps\brave\current\brave.exe". Dependent Assembly 80.1.5.115,language="&#x2a;",type="win32",version="80.1.5.115" could not be found. Please use sxstrace.exe for detailed diagnosis.
---

The exact executable version is 80.1.5.115

**Comment by Ash258** [comment]
Latest available version in this bucket is `1.4.96`.

#3803

**Comment by quantuumsnot** [comment]
IT'S NOT

I have the problem with **1.4.96**.

After 2-3 months not using the browser (which worked then), today decided to test some sites with it and saw the error -> updated to the current version an hour ago which is **1.5.115**

**Comment by Ash258** [comment]
Then it cannot be from extras bucket

https://github.com/lukesampson/scoop-extras/blob/bf352c2617bac7f1ff995fe02a9af53288f1e898/bucket/brave.json#L2

Checkver was disabled before weak and no updates were done after.

**Comment by quantuumsnot** [comment]
I thought the same:

> PS C:\Windows\system32> scoop uninstall brave
> Uninstalling 'brave' (1.5.115).
> Removing shim for 'brave'.
> Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Brave.lnk
> Unlinking D:\scoop\apps\brave\current
> Removing older version (1.0.1).
> Removing older version (1.1.20).
> Removing older version (1.1.23).
> Removing older version (1.2.42).
> Removing older version (1.2.43).
> Removing older version (1.3.115).
> Removing older version (1.3.118).
> Removing older version (1.4.96).
> 'brave' was uninstalled.

**Comment by Ash258** [comment]
`scoop update`
