### ISSUE TITLE
gimp@2.10.18-2: decompress error

### ISSUE THREAD

**Issue by carlosrabelo** [lukesampson/scoop-extras#3835]
When trying to install Gimp, the following message appears:

Failed to extract files from C: \ Users \ ... \ scoop \ apps \ gimp \ 2.10.18-2 \ gimp-2.10.18-setup-2.exe.
Log file:
   ~ \ scoop \ apps \ gimp \ 2.10.18-2 \ innounp.log

**Comment by Ash258** [comment]
Duplicate of #3804
