### ISSUE TITLE
typora@0.9.86: decompress error

### ISSUE THREAD

**Issue by MistyMt** [lukesampson/scoop-extras#3839]
> scoop install typora
Installing 'typora' (0.9.86) [64bit]
Loading typora-setup-x64.exe from cache
Checking hash of typora-setup-x64.exe ... ok.
Extracting typora-setup-x64.exe ... Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数 为 Null 或空。请提供一个不为 Null 或
空的参数，然后重试该命令。
所在位置 E:\SCOOP\apps\scoop\current\lib\decompress.ps1:192 字符: 38
+ ... tus = Invoke-ExternalCommand (Get-HelperPath -Helper Innounp) $ArgLis ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationEx
    ception
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from E:\SCOOP\apps\typora\0.9.86\typora-setup-x64.exe.
Log file:
  E:\SCOOP\apps\typora\0.9.86\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=typora%400.9.86%3a+decompress+error

**Comment by Ash258** [comment]
`scoop install innounp; scoop install typora`

**Comment by MistyMt** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jakub &amp;#x10C;ábera"<notifications@github.com&gt;; 
发送时间: 2020年4月11日(星期六) 下午3:12
收件人: "lukesampson/scoop-extras"<scoop-extras@noreply.github.com&gt;; 
抄送: "樊开"<fankai1999@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lukesampson/scoop-extras] typora@0.9.86: decompress error (#3839)





 
scoop install innounp; scoop install typora
