### ISSUE TITLE
VSCodium wrong version update

### ISSUE THREAD

**Issue by nixls** [lukesampson/scoop-extras#3862]
https://github.com/lukesampson/scoop-extras/commit/a65b4af96ef427760cc42708567286988640de38
VSCodium has been updated recently to version 1.43.2 from.. 1.44.0. The newest version is 1.44.1, this could've been done by a mistake.

**Comment by Ash258** [comment]
Latest version is NOW 1.44.1, it was create one hour ago.

![image](https://user-images.githubusercontent.com/13260377/79334734-2505b200-7f21-11ea-9b8b-51775adebef2.png)

The update commit is 4 hours old.
