### ISSUE TITLE
URL for portable-virtualbox has changed

### ISSUE THREAD

**Issue by lx4r** [lukesampson/scoop-extras#3863]
When trying to install `portable-virtualbox` from the `extras` bucket I get this error message:

```
λ  scoop install portable-virtualbox
Installing 'portable-virtualbox' (6.4.10) [64bit]
The remote name could not be resolved: 'files.vbox.me'
URL http://files.vbox.me/files/Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all.exe#/dl.7z is not valid
```

It seems, when looking at the site, that the right URL would be <https://www.vbox.me/files/Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all.exe>.

Thanks in advance for the help :).

**Comment by mark05e** [comment]
> remote name could not be resolved

This seems to be a network/dns issue. Are you able to browse the URL manually?

Maybe test with powershell using below command.

```powershell
Invoke-WebRequest http://files.vbox.me/files/Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all.exe -OutFile C:\temp\VirtualBox_dl.7z
Invoke-Item C:\temp\VirtualBox_dl.7z
```

**Comment by lx4r** [comment]
Interesting, you're right, there seems to be a network issue. When I try to download the file using your PowerShell command I get nothing and when I visit the link using Firefox I get this:

![image](https://user-images.githubusercontent.com/1402895/79383056-d24de980-7f64-11ea-8f99-cdcc718415b6.png)

And this using Chrome:

![image](https://user-images.githubusercontent.com/1402895/79383072-ded24200-7f64-11ea-8890-b6595ffeaee4.png)

To me it looks like vbox.me somehow got on some kind of blacklist, right? But then it's weird that you can access the site fine, I would have thought that Chrome's blacklist are the same worldwide 🤔 .

**Comment by mark05e** [comment]
I do not seem to be getting the same issue when I try to browse or download the file. I am on Chrome Version 80.0.3987.163. I guess this could be something that a firewall or AV controls.

**Comment by lx4r** [comment]
Very weird, I just have the standard Windows Defender as AV and no special firewall. Anyway, looks like this is a problem only I have, thanks for the help.
