### ISSUE TITLE
libreoffice-fresh@6.4.3.2: Error trying to install this version

### ISSUE THREAD

**Issue by ferxohn** [lukesampson/scoop-extras#3869]
Hello.

Every time I try to install this version, PowerShell throws this error:

![image](https://user-images.githubusercontent.com/35642546/79520334-2071f400-801c-11ea-9281-934b60710faf.png)

I found that there is a difference between the extract directory created when LibreOffice is being installed, and I think this is the reason of this error.

This is the directory created when version 6.4.3.2 is installing:

![image](https://user-images.githubusercontent.com/35642546/79520713-fff66980-801c-11ea-876a-0757f433365e.png)

And this is the directory created when version 6.4.2.2 is installing. This version is ok:

![image](https://user-images.githubusercontent.com/35642546/79520506-a1c98680-801c-11ea-9c7e-09a512e0505d.png)

Thank you.

**Comment by NatoBoram** [comment]
Got the same problem.

> ```powershell
> sudo scoop install -g libreoffice-fresh
> WARN  Scoop uses 'aria2c' for multi-connection downloads.
> WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
> Installing 'libreoffice-fresh' (6.4.3.2) [64bit]
> Loading LibreOffice_6.4.3.2_Win_x64.msi from cache.
> Checking hash of LibreOffice_6.4.3.2_Win_x64.msi ... ok.
> Extracting LibreOffice_6.4.3.2_Win_x64.msi ... Exception: C:\Users\natob\scoop\apps\scoop\current\lib\core.ps1:510
> Line |
>  510 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
>      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Could not find 'LibreOffice'! (error 16)
> ```

Right now, the only alternative I see is to use `libreoffice-stable`.

> ```powershell
> scoop search libreoffice
> 'extras' bucket:
>     libreoffice-fresh (6.4.3.2)
>     libreoffice-stable (6.4.2)
> ```

> ```powershell
> Download: Download Results:
> Download: gid   |stat|avg speed  |path/URI
> Download: ======+====+===========+=======================================================
> Download: 7abf21|OK  |   1.2MiB/s|C:/Users/natob/scoop/cache/libreoffice-stable#6.4.2#https_downloadarchive.documentfoun
> dation.org_libreoffice_old_6.4.2.2_portable_LibreOfficePortable_6.4.2_MultilingualStandard.paf.exe_dl.7z
> Download: Status Legend:
> Download: (OK):download completed.
> Checking hash of LibreOfficePortable_6.4.2_MultilingualStandard.paf.exe ... ok.
> Extracting dl.7z ... done.
> Running pre-install script...
> Copying old 'C:\Users\natob\AppData\Roaming\LibreOffice' to 'C:\ProgramData\scoop\persist\libreoffice-stable\Data\settin
> gs'
> Linking C:\ProgramData\scoop\apps\libreoffice-stable\current => C:\ProgramData\scoop\apps\libreoffice-stable\6.4.2
> Creating shortcut for LibreOffice\LibreOffice (LibreOfficePortable.exe)
> Creating shortcut for LibreOffice\LibreOffice Base (LibreOfficeBasePortable.exe)
> Creating shortcut for LibreOffice\LibreOffice Calc (LibreOfficeCalcPortable.exe)
> Creating shortcut for LibreOffice\LibreOffice Draw (LibreOfficeDrawPortable.exe)
> Creating shortcut for LibreOffice\LibreOffice Impress (LibreOfficeImpressPortable.exe)
> Creating shortcut for LibreOffice\LibreOffice Math (LibreOfficeMathPortable.exe)
> Creating shortcut for LibreOffice\LibreOffice Writer (LibreOfficeWriterPortable.exe)
> Persisting Data
> 'libreoffice-stable' (6.4.2) was installed successfully!
> 'libreoffice-stable' suggests installing 'extras/vcredist2015'.
> ```

**Comment by thingumajig** [comment]
![image](https://user-images.githubusercontent.com/8703531/98673436-60a61480-2368-11eb-80ec-688f00aefb75.png)
Again

**Comment by ferxohn** [comment]
![image](https://user-images.githubusercontent.com/35642546/98877115-bc969900-244d-11eb-9fa7-3c0eaa065ce4.png)

Me too :(

**Comment by ferxohn** [comment]
![image](https://user-images.githubusercontent.com/35642546/98877236-fd8ead80-244d-11eb-8d04-662b9559200b.png)

Me too :(

**Comment by jacobblock** [comment]
+1 same issue with 7.0.3.1 release.

**Comment by UmeSiyah** [comment]
+1 
![image](https://user-images.githubusercontent.com/32277675/101289716-8525cd00-37fe-11eb-8831-c23093ff0ba5.png)

**Comment by DutchFlander** [comment]
+1
![image](https://user-images.githubusercontent.com/39187545/103467903-087e0400-4d54-11eb-8a88-0773957b56c4.png)
