### ISSUE TITLE
idea-ultimate@2020.1: hash check failed

### ISSUE THREAD

**Issue by lucasllin** [lukesampson/scoop-extras#3870]
![image](https://user-images.githubusercontent.com/10697191/79526520-0c6bd800-8098-11ea-8b51-dfaedc812c5a.png)

**Comment by yang69** [comment]
The same happened for me. Here are the details:

Checking hash of ideaIU-2020.1.win.zip ... ERROR Hash check failed!
App:         extras/idea-ultimate
URL:         https://download.jetbrains.com/idea/ideaIU-2020.1.win.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    bb51acf686c52860213e2432337fa73fd02f80e7b4b4f186c029bd4c953e742a
Actual:      32ae1cd29795b537521cad8f2596f597c31e7af1a96dd48b840837c911b01739

**Comment by Ash258** [comment]
China specific issue. Use VPN

**Comment by lucasllin** [comment]
> China specific issue. Use VPN

thanks
