### ISSUE TITLE
Rename shortcuts of fscapture, fsresizer, fsviewer

### ISSUE THREAD

**Issue by vuwjzl17985** [lukesampson/scoop-extras#3941]
fscapture, fsresizer, and fsviewer are developed by the same company but the names of their shortcuts are not consistent in this bucket.  Currently, their names of shortcuts are _FSCapture_, _FSViewer_, and _FastStone Photo Resizer_.

1. Is it necessary to rename them for consistency? 
2. If it is, I think it would be better to use the commercial names for shortcuts, e.g. _FastStone Capture_, _FastStone  Photo Resizer_, and _FastStone Viewer_. 

Three manifests are given as follows:
https://github.com/lukesampson/scoop-extras/blob/master/bucket/fsresizer.json
https://github.com/lukesampson/scoop-extras/blob/master/bucket/fscapture.json
https://github.com/lukesampson/scoop-extras/blob/master/bucket/fsviewer.json

**Comment by Ash258** [comment]
Shortcuts are created the same as installers are doing/did when manifest was added.

- FSResizers is the youngest one and their installer now creates start menu shortcut as expected and as seen in manifest.
- Back in the time of fscapture manifest creation the installer created short name

**Comment by vuwjzl17985** [comment]
I install all these three applications and find the shortcuts are _FastStone Capture_, _FastStone Image Viewer_, and _FastStone Photo Resizer_ after normal installation. 

I will change the short names in the manifests via a pull request. Thank you @Ash258 .
