### ISSUE TITLE
grepwin@2.0.0: download via aria2 failed

### ISSUE THREAD

**Issue by fiammanda** [lukesampson/scoop-extras#3947]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/grepwin-install-context.reg
    referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
    dir=D:\Scoop\cache
    out=grepwin#2.0.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_grepwin-install-context.reg
https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/grepwin-uninstall-context.reg
    referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
    dir=D:\Scoop\cache
    out=grepwin#2.0.0#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_grepwin-uninstall-context.reg

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\grepwin.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6324 --continue

**Comment by fiammanda** [comment]
> 
> 
> Cannot reproduce.
> 
> All files could be downloaded without any issue.
> Problems with download could be caused by:
> 
>     * Network error
> 
>     * Site is blocked (Great Firewall of China, Corporate restrictions, ...)
> 
>     * Antivirus settings could block URL or block downloaded file
> 
>     * Proxy configuration

I can install other apps but not this one...

**Comment by Ash258** [comment]
No issue with and without aria2

![image](https://user-images.githubusercontent.com/13260377/80391276-cbe93700-88ad-11ea-9ca9-09322c5d807c.png)

![image](https://user-images.githubusercontent.com/13260377/80391291-d1468180-88ad-11ea-9f7a-5d2746e868f9.png)

Github occasionally have problems under GFW. Try again later or without aria2.
