### ISSUE TITLE
gimp@2.10.18-2 trojan and unwanted software

### ISSUE THREAD

**Issue by kmasuyama** [lukesampson/scoop-extras#3956]
Windows Defender flagged some files from the scoop gimp install. This might be upstream, but I don't have an account on GNOME Gitlab to post there.

The threats detected:
- Trojan:Win32/Conteban.B!ml
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\align-layers\.debug\align-layers.exe,2.debug
- Trojan:Win32/Fuery.C!cl
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\color-enhance\.debug\is-U1QFP.tmp
- Program:Win32/Uwasson.A!ml
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\animation-optimize\.debug\animation-optimize.exe,2.debug
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\blur\.debug\blur.exe,2.debug
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\cartoon\.debug\cartoon.exe,2.debug
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\checkerboard\.debug\checkerboard.exe,2.debug
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\cml-explorer\.debug\cml-explorer.exe,2.debug
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\animation-optimize\.debug\is-A66UU.tmp
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\blur\.debug\is-A91G5.tmp
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\cartoon\.debug\is-12PM3.tmp
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\checkerboard\.debug\is-DLT47.tmp
  - C:\Users\km\scoop\apps\gimp\2.10.18-2\lib\gimp\2.0\plug-ins\cml-explorer\.debug\is-T2TA2.tmp

**Comment by Brassfield** [comment]
I was just about to report the same.

No viruses were detected when installing directly via upstream https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.18-setup-2.exe

but I don't know which mirror I pulled from.

**Comment by Bira-oliverio** [comment]
I've just installed Gimp 2.10.18 using scoop without issues this time. Maybe an update from Microsoft Defender fixed this issue.

**Comment by chhh** [comment]
It's still there, just installed today, got flagged by Win Defender immediately.

**Comment by rnwolf** [comment]
I also got this issue today.
![Annotation 2020-05-15 160231](https://user-images.githubusercontent.com/117415/82065311-dbe28280-96c5-11ea-81c5-09ec2cc7a535.png)

**Comment by sleighsoft** [comment]
Same happens for me.

Also see:
- #3094
- #3386
- #3779 
- #3804

**Comment by rasa** [comment]
This seems to be a spurious issue. VirusTotal reports [0/65](https://www.virustotal.com/gui/file/430b1a709cd89b5cddb857032a7a5b93199d076ff8cd83ebdd0112330b65ba51/detection) for the current version
