### ISSUE TITLE
Automated AppVeyor tests extras bucket

### ISSUE THREAD

**Issue by r15ch13** [lukesampson/scoop-extras#398]
@lukesampson I added more tests to this bucket because it was really messy. 😐 https://github.com/lukesampson/scoop-extras/commit/da5dd74b1ec4a0adaf371b66d8d861c7c5abc829
I wanted to ask if you could setup appveyor to run automated tests on this repo? :smile:

**Comment by lukesampson** [comment]
Thanks! I've added an AppVeyor project [here](https://ci.appveyor.com/project/lukesampson/scoop-extras). Is anything else needed?

**Comment by r15ch13** [comment]
Maybe for the versions bucket. I also added those test there.

**Comment by lukesampson** [comment]
I can't work out how to add scoopinstaller/versions repo to AppVeyor — I only see my GitHub user repos.

**Comment by r15ch13** [comment]
Hm, maybe you have to log in with the organization account?

**Comment by lukesampson** [comment]
@deevus are you able to add AppVeyor projects for scoopinstaller GitHub org, since you set it up?

**Comment by deevus** [comment]
@lukesampson I don't appear to have access. Looks like they're set up under
your account. I think you'll need to invite me to the team?

**Comment by deevus** [comment]
If I authorise GitHub and allow access to scoopinstaller I can see them to create projects, though

**Comment by lukesampson** [comment]
Ah okay thanks. I can see scoopinstaller repos now, not sure how you did that @deevus but thanks. https://ci.appveyor.com/project/lukesampson/versions is set up now @r15ch13.

**Comment by r15ch13** [comment]
Thanks 👍
