### ISSUE TITLE
[Request]Need a persist folder "user-components" for foobar2000-portable.

### ISSUE THREAD

**Issue by AkariiinMKII** [lukesampson/scoop-extras#4044]
Or user components will be lost after updating the application.

**Comment by joegreene** [comment]
Maybe someone with a bit more experience than me in this might know better, but I think this is as simple as adding `user_components` to the `persist` array in `foobar2000-portable.json`. Testing that seemed to make things work locally, so [I made a PR to do this](https://github.com/lukesampson/scoop-extras/pull/4149).
