### ISSUE TITLE
archi@4.6.0: download failed

### ISSUE THREAD

**Issue by webartoli** [lukesampson/scoop-extras#4056]
Trying to install archi

the result is -1 B file

```
scoop install archi
Installing 'archi' (4.6.0) [64bit]
Downloading https://www.archimatetool.com/downloads/4.6.0/Archi-Win64-4.6.0.zip (-1 B)
```

Downloading from website the correct url for this realease seems:
https://www.archimatetool.com/downloads/19ef8fac18b/Archi-Win64-4.6.0.zip

**Comment by webartoli** [comment]
Launching:
`curl -i https://www.archimatetool.com/downloads/4.6.0/Archi-Win64-4.6.0.zip`

Response Headers
``` http
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=iso-8859-1
Content-Length: 246
Connection: keep-alive
Keep-Alive: timeout=15
Date: Wed, 13 May 2020 14:54:40 GMT
Server: Apache
Location: https://www.archimatetool.com/download
```

Body
``` html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.archimatetool.com/download">here</a>.</p>
</body></html>
```

**Comment by Ash258** [comment]
Vendors started again with their temporary token download procedure (#3370), which will make this manifest unusable again after few hours after fix.

I am definitely for removing this manifest.

**Comment by mark05e** [comment]
there is a [download script](https://www.archimatetool.com/wp-content/themes/mytheme/js/download.js) which generates the [download url](https://www.archimatetool.com/downloads/19ef8fac18d/Archi-Win64-4.6.0.zip).

I am not sure how to scrape the contents to build the [autoupdate section](https://github.com/lukesampson/scoop-extras/blob/52c4ead8af38c324e982a8663b848d1fb6be0eeb/bucket/archi.json#L24).
