### ISSUE TITLE
caprine@2.46.0: hash check failed

### ISSUE THREAD

**Issue by slickag** [lukesampson/scoop-extras#4060]
This is the console output:

Download: (OK):download completed.
Checking hash of Caprine-Setup-2.46.0.exe ... ERROR Hash check failed!
App:         extras/caprine
URL:         https://github.com/sindresorhus/caprine/releases/download/v2.46.0/Caprine-Setup-2.46.0.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    301803f5dbf2b967d124bb48bc059076ecd69ebdd2c1ec995e620fcd91f450c4a6074b5b336bcbdbabf0ea44704dc8a6527a9568e255aca44338da999d091e57
Actual:      632c175936ff40cdc4734f48646224b7df308c732c35d580d0a9ed109a02b23ea8e36b4047aeb5385f82857736a5a0a0134fd8ee3064974267b1abecd73f8675

**Comment by mark05e** [comment]
updated PR ref https://github.com/lukesampson/scoop-extras/pull/4061

**Comment by Ash258** [comment]
8f9c3f227edbc539139c4e96b8d7ad4b0de02890
