### ISSUE TITLE
vscode@1.45.1: download via aria2 failed

### ISSUE THREAD

**Issue by Vikiboss** [lukesampson/scoop-extras#4070]
Updating 'vscode' (1.43.0 -> 1.45.1)
Downloading new version
Loading dl.7z from cache.
Starting download with aria2 ...
Download: 05/16 20:33:00 [ERROR] CUID#8 - Download aborted. URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
Download: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:The requested address is not valid in its context.
Download: 05/16 20:33:00 [ERROR] CUID#9 - Download aborted. URI=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-uninstall-context.reg
Download: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:The requested address is not valid in its context.
Download: [DL:0B][#646506 0B/0B][#61d4fd 0B/0B]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 646506|ERR |       0B/s|C:/Users/Viki/scoop/cache/vscode#1.45.1#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-install-context.reg
Download: 61d4fd|ERR |       0B/s|C:/Users/Viki/scoop/cache/vscode#1.45.1#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-uninstall-context.reg
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-install-context.reg
    referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
    dir=C:\Users\Viki\scoop\cache
    out=vscode#1.45.1#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-install-context.reg
https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/vscode-uninstall-context.reg
    referer=https://raw.githubusercontent.com/lukesampson/scoop-extras/master/scripts/
    dir=C:\Users\Viki\scoop\cache
    out=vscode#1.45.1#https_raw.githubusercontent.com_lukesampson_scoop-extras_master_scripts_vscode-uninstall-context.reg

ERROR & 'C:\Users\Viki\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Viki\scoop\cache\vscode.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=2168 --continue

**Comment by Ash258** [comment]
>  Network problem has occurred.
