### ISSUE TITLE
winrar@5.90: hash check failed

### ISSUE THREAD

**Issue by MistyMt** [lukesampson/scoop-extras#4080]
Installing 'winrar' (5.90) [64bit]
winrar-x64-590.exe (3.1 MB) [======>                                                                                                                ]   6%
Checking hash of winrar-x64-590.exe ... ERROR Hash check failed!
App:         extras/winrar
URL:         https://www.rarlab.com/rar/winrar-x64-590.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    f541c80ac787a26931b7b1eba1fefcda56a3a05ca44c1e961efe4a5a480175bf
Actual:      985412825ebf2437a2787ecd8a4cfb31a3ce59938244bab170142e24ebac525f

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=winrar%405.90%3a+hash+check+failed

**Comment by Ash258** [comment]
> ] 6%
