### ISSUE TITLE
flux@4.111: Download failed

### ISSUE THREAD

**Issue by SuJiKiNen** [lukesampson/scoop-extras#4083]
https://justgetflux.b-cdn.net/flux-setup4-111.exe#/dl.7z

the server return 504,the url changeed

**Comment by mark05e** [comment]
have you tried this again? as per the [code](https://github.com/lukesampson/scoop-extras/blob/52c4ead8af38c324e982a8663b848d1fb6be0eeb/bucket/flux.json#L9), the url should be https://justgetflux.com/flux-setup4-111.exe . I just tried to download and it seemed to work.
