### ISSUE TITLE
[Request] Snipaste

### ISSUE THREAD

**Issue by phgmacedo** [lukesampson/scoop-extras#4134]
# Request: 
[Snipaste](https://www.snipaste.com/download.html)

# Description:

Snipaste offers powerful yet easy-to-use snipping, pasting and image annotating functionalities. It is highly customizable to fit all your needs. 

The portable (non Windows Store) version is free, and has all the useful features available.

**Comment by Ash258** [comment]
https://scoop-docs.now.sh/apps/?query=snipaste

https://github.com/lukesampson/scoop-extras/blob/master/bucket/snipaste.json

**Comment by phgmacedo** [comment]
> https://scoop-docs.now.sh/apps/?query=snipaste
> 
> https://github.com/lukesampson/scoop-extras/blob/master/bucket/snipaste.json

Thanks! But the scoop version is outdated. How can I fix it?
