### ISSUE TITLE
Digikam 6.4.0 unable to install without aria2

### ISSUE THREAD

**Issue by iguyking** [lukesampson/scoop-extras#4137]
In trying to install DigiKam, it doesn't work unless aria2 is installed.   

```
Installing 'digikam' (6.4.0) [64bit]
The remote server returned an error: (302) Found.
URL https://download.kde.org/stable/digikam/6.4.0/digiKam-6.4.0-Win64.exe#/dl.7z is not valid
```

Windows 10
Powershell 7.0.1
scoop updated as of 25 May 2020

**Comment by iguyking** [comment]
I'd like to offer a PR, I'm just a little confused on what my method is for being able to contribute and test this?   

Is the flow 
* Fork scoop-extras
* Test directly against master
* Issue PR back to Digikam 

Or is there some method for branch based testing I should be doing? 

Thanks

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop/pull/3902
