### ISSUE TITLE
rescuetime@2.15.0.2: hash check failed

### ISSUE THREAD

**Issue by okerules** [lukesampson/scoop-extras#4167]
scoop update rescuetime                                                                              
rescuetime: 2.15.0.1 -> 2.15.0.2                                                                       
Updating one outdated app:                                                                             
Updating 'rescuetime' (2.15.0.1 -> 2.15.0.2)                                                           
Downloading new version                                                                                
Downloading https://www.rescuetime.com/installers/RescueTimeInstaller_2.15.0.2.exe (-1 B)...           
                                                                                                       
Checking hash of RescueTimeInstaller_2.15.0.2.exe ... ERROR Hash check failed!                         
App:         extras/rescuetime                                                                         
URL:         https://www.rescuetime.com/installers/RescueTimeInstaller_2.15.0.2.exe                    
First bytes: 4D 5A 50 00 02 00 00 00                                                                   
Expected:    0d86cfba1331f67fdb52525ada7d931865c72a8bbdd1c5fca61c3b841a116f87                          
Actual:      4498abb62350eddee5754517a7559007d65e061d2005266d4c434da67d0afe87                          
                                                                                                       
Please try again or create a new issue by using the following link and paste your console output:      
https://github.com/lukesampson/scoop-extras/issues/new?title=rescuetime%402.15.0.2%3a+hash+check+failed

**Comment by mark05e** [comment]
updated PR -- https://github.com/lukesampson/scoop-extras/pull/4168
