### ISSUE TITLE
tableplus@3.5.4.128: hash check failed

### ISSUE THREAD

**Issue by rwarren** [lukesampson/scoop-extras#4170]
Hash check failure:

![image](https://user-images.githubusercontent.com/2751728/83301785-369cd380-a1c8-11ea-8212-95da7d8d7fbc.png)

**Comment by rwarren** [comment]
@Ash258 Still fails.... why was this closed?

**Comment by Ash258** [comment]
...

`scoop update`

**Comment by rwarren** [comment]
<facepalm>

Sorry. I'm just so used to scoop automatically updating before installations.

**Comment by yofriadi** [comment]
mine still fails, want to install it today, has the same version

`Installing 'tableplus' (3.5.4.128) [64bit]
TablePlusSetup.exe (60.6 MB) [================================================================================] 100%
Checking hash of TablePlusSetup.exe ... ERROR Hash check failed!
App:         extras/tableplus
URL:         https://s3.amazonaws.com/tableplus-win-builds/128/TablePlusSetup.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    cce281d64660eb476706085df70739bde0adc818d9b292f5f01ad0d12b9ff217
Actual:      178214d3bad8556046407f458981e8116c605c26d786cf44de0a455829c66e2c`
