### ISSUE TITLE
typora@0.9.89: decompress error

### ISSUE THREAD

**Issue by gundamlh** [lukesampson/scoop-extras#4183]
The following text is copied from my console, Powershell running in Windows Terminal 2,

Thank you in advance!

~ $ scoop install typora
Installing 'typora' (0.9.89) [64bit]
Loading typora-setup-x64.exe from cache
Checking hash of typora-setup-x64.exe ... ok.
Extracting typora-setup-x64.exe ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The argument is null or em
pty. Provide an argument that is not null or empty, and then try the command again.
At D:\apps\Scoop\apps\scoop\current\lib\decompress.ps1:192 char:38
+ ... tus = Invoke-ExternalCommand (Get-HelperPath -Helper Innounp) $ArgLis ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationE
   xception
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from D:\apps\Scoop\apps\typora\0.9.89\typora-setup-x64.exe.
Log file:
  D:\apps\Scoop\apps\typora\0.9.89\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=typora%400.9.89%3a+decompress+error
~ $ scoop update typora
typora: 0.9.89 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
~ $
~ $ scoop uninstall typora
Uninstalling 'typora' (0.9.89).
'typora' was uninstalled.

**Comment by mark05e** [comment]
have you tried it in regular powershell - without wsl2?

**Comment by Ash258** [comment]
`scoop install innounp` and then reinstall
