### ISSUE TITLE
mobaxterm@20.2: download via aria2 failed

### ISSUE THREAD

**Issue by gundamlh** [lukesampson/scoop-extras#4184]
The following text is directly copied from my console, Powershell running on Windows Terminal 2. 

Thank you in advance!

~ $ scoop install mobaxterm
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'mobaxterm' (20.2) [64bit]
Starting download with aria2 ...
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: [#8a6eb0 0B/0B CN:1 DL:0B]
Download: 05/31 11:49:32 [ERROR] CUID#8 - Download aborted. URI=https://download.mobatek.net/2022020030522248/MobaXterm_Portable_v20.2.zip
Download: Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:No connection could be made because the target machine actively refused it.
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 8a6eb0|ERR |       0B/s|D:/apps/Scoop/cache/mobaxterm#20.2#https_download.mobatek.net_2022020030522248_MobaXterm_Portable_v20.2.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://download.mobatek.net/2022020030522248/MobaXterm_Portable_v20.2.zip
    referer=https://download.mobatek.net/2022020030522248/
    dir=D:\apps\Scoop\cache
    out=mobaxterm#20.2#https_download.mobatek.net_2022020030522248_MobaXterm_Portable_v20.2.zip

ERROR & 'D:\apps\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\apps\Scoop\cache\mobaxterm.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=13144 --continue --all-proxy='localhost:7890'

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=mobaxterm%4020.2%3a+download+via+aria2+failed

**Comment by gundamlh** [comment]
> 
> 
> Cannot reproduce.
> 
> All files could be downloaded without any issue.
> Problems with download could be caused by:
> 
>     * Network error
> 
>     * Site is blocked (Great Firewall of China, Corporate restrictions, ...)
> 
>     * Antivirus settings could block URL or block downloaded file
> 
>     * Proxy configuration

Well, i've configured a proxy bypassing the wall, and i can download the same app w/o using aria2 by setting `aria2-enabled` `false`. In all honesty, the error would probably be caused by aria2?

~ $ scoop config aria2-enabled
True
~ $ scoop config aria2-enabled false
'aria2-enabled' has been set to 'false'
~ $ scoop install mobaxterm
ERROR It looks like a previous installation of mobaxterm failed.
Run 'scoop uninstall mobaxterm' before retrying the install.
WARN  'mobaxterm' () is already installed.
Use 'scoop update mobaxterm' to install a new version.
~ $ scoop uninstall mobaxterm
Uninstalling 'mobaxterm' ().
'mobaxterm' was uninstalled.
~ $ scoop install mobaxterm
Installing 'mobaxterm' (20.2) [64bit]
MobaXterm_Portable_v20.2.zip (26.2 MB) [====================================================] 100%
Checking hash of MobaXterm_Portable_v20.2.zip ... ok.
Extracting MobaXterm_Portable_v20.2.zip ... done.
Running pre-install script...
Linking D:\apps\Scoop\apps\mobaxterm\current => D:\apps\Scoop\apps\mobaxterm\20.2
Creating shim for 'MobaXterm'.
Creating shortcut for MobaXterm Personal (MobaXterm.exe)
Persisting MobaXterm.ini
Persisting MobaXterm backup.zip
'mobaxterm' (20.2) was installed successfully!

**Comment by mark05e** [comment]
Have you tried running the aria command alone?

```
'D:\apps\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\apps\Scoop\cache\mobaxterm.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=debug --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=13144 --continue --all-proxy='localhost:7890'
```
Is the proxy config correct? `--all-proxy='localhost:7890'` 
I have updated the command to try `console-log-level=debug` -- might have some additional info.
