### ISSUE TITLE
gcc-arm-none-eabi@9-2020-q2-update: Download failed

### ISSUE THREAD

**Issue by chang196700** [lukesampson/scoop-extras#4189]
```
Installing 'gcc-arm-none-eabi' (9-2020-q2-update) [64bit]
The remote server returned an error: (404) Not Found.
URL https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-win32.zip.bz2 is not valid
```
The correct URL looks like so https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-win32.zip

**Comment by mark05e** [comment]
seems like zip.bz2 version has been removed?

This is valid https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-win32.zip
