### ISSUE TITLE
archi@4.6.0: hash check failed

### ISSUE THREAD

**Issue by merodeandote** [lukesampson/scoop-extras#4211]
ERROR Hash check failed!

![image](https://user-images.githubusercontent.com/47398122/83667797-97dff080-a594-11ea-96f0-f2d51f4293d1.png)

**Comment by Ash258** [comment]
Duplicate of #4056

**Comment by merodeandote** [comment]
> Duplicate of #4056
I don't think so
4056 > downloading problem
4211 > I can donwload it but it is not installing, because hash check failing

**Comment by Ash258** [comment]
The download size is same and the webpage was downloaded....

**Comment by merodeandote** [comment]
I think they change exe file everyday. Today it has other hash code

![image](https://user-images.githubusercontent.com/47398122/83801979-9cc5a280-a66f-11ea-8426-a96cd7092b94.png)
