### ISSUE TITLE
bulk-rename-utility@3.3.2.0: Download failed

### ISSUE THREAD

**Issue by Ezneh** [lukesampson/scoop-extras#4221]
Hello, it seems there is a small problem with the update of the bulk-rename-utility on my side:

```
Updating 'bulk-rename-utility' (3.3.1.0 -> 3.3.2.0)
Downloading new version
OperationStopped: D:\Applications\Scoop\apps\scoop\current\lib\install.ps1:130
Line |
 130 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (302) Found.
```

Hopefully it can be solved.
Regards,
Ezneh.

**Comment by mark05e** [comment]
Related: https://github.com/lukesampson/scoop/pull/3902

Dl url redirects to http location -> http://www.s3.tgrmn.com/bru/BRU_setup_3.3.2.0.exe

Alternative /mirror dl location: https://www.bulkrenameutility.co.uk/swmirror/BRU_setup.exe --redirect--> https://www.bulkrenameutility.co.uk/FileKicker/BRU_setup_3.3.2.0.exe

@Ash258 - how would you propose to proceed on this?

I [tested with the mirror location](https://gist.githubusercontent.com/mark05e/8250ced7ee90cc16cea01a75335b8bd4/raw/51fc5f0930028abfbcd0983127646df8c7b0afd9/bulk-rename-utility.json) with scoop but still get the 302 error. I am not sure if I map the final location in this scenario?

```
scoop install https://gist.githubusercontent.com/mark05e/8250ced7ee90cc16cea01a75335b8bd4/raw/51fc5f0930028abfbcd0983127646df8c7b0afd9/bulk-rename-utility.json

Installing 'bulk-rename-utility' (3.3.2.0) [64bit]
The remote server returned an error: (302) Found.
URL https://www.bulkrenameutility.co.uk/swmirror/BRU_setup.exe is not valid
```

**Comment by Ash258** [comment]
Nothing. Redirect handling is in develop. There is no reason to fix it.
