### ISSUE TITLE
Brave Script Update

### ISSUE THREAD

**Issue by everonline** [lukesampson/scoop-extras#4231]
Hi guys,

Can we please get a script update that use this 2 source links provided by Brave that always contains the latest version:

https://brave-browser-downloads.s3.brave.com/latest/brave_installer-x64.exe
https://brave-browser-downloads.s3.brave.com/latest/brave_installer-ia32.exe

I think it would take just a slight change to the existent script and get us an updated version, right now is sitting on the 1.4.96.

PS: I would offer myself to do it if I had perms and some place to test.

Thanks

**Comment by everonline** [comment]
Ash258 at least explain your disagreement... your thumbs down... is better for scoop users to install and keep an outdated version? Instead of trying to sort the script and get us the latest one?

**Comment by everonline** [comment]
Will create my own app manifest / repo for Brave and share it here since Jakub (aka Ash258) is not keen to follow on the suggestion or present an alternative.

Seems to be working for me using the official sources above:

    Directory: C:\Users\xxxxxxx\scoop\apps\brave\current

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       28/05/2020     09:32                81.1.9.76
d-----       28/05/2020     09:32                Dictionaries
-a----       28/05/2020     09:32        1979048 brave.exe
-a----       28/05/2020     09:32         688808 chrome_proxy.exe

Id        : 10248
Name      : brave
Path      : C:\Users\xxxxxxxxxx\scoop\apps\brave\current\brave.exe
StartTime : 07/06/2020 21:37:52
RunTime   : 00:17:25.4040358
WS        : 54042624
VM        : 2203753074688
Company   : Brave Software, Inc.

**Comment by donlelek** [comment]
Hey @everonline, were you able to make it work with your own manifest? I gave it a try but failed miserably.

**Comment by everonline** [comment]
> Hey @everonline, were you able to make it work with your own manifest? I gave it a try but failed miserably.

Hi Donlelek,

I did it for myself but lacked the time to share it, will try to make it available today and then is just a matter of adding the repo.

I believe this to be better than having no solution at all and relying on outdated software.

**Comment by donlelek** [comment]
That would be awesome!

**Comment by everonline** [comment]
> That would be awesome!

Hi Donlelek,

I keep to promises (core value) even if my time is short.

As mentioned before I did this for my personal use since Ash258 (besides his excellent work - I just adapt his manifest) didn't provide me an alternative, while you can do a hash check against the source of the files mentioned above (for safety) I would recommend you clone my repository and have your own.

That being said this is how you add it:

```
scoop bucket add everonline https://github.com/everonline/brave.git
Checking repo... ok
The everonline bucket was added successfully.
```

```
scoop update
Updating Scoop...
Updating 'everonline' bucket...
 * eebf9f9 Update README.md                                              50 seconds ago
 * 45dcf8a Update README.md                                              87 seconds ago
Updating 'extras' bucket...
Updating 'java' bucket...
Updating 'main' bucket...
Scoop was updated successfully!
```

```
scoop search brave
'everonline' bucket:
    bravecustom (1.10.97)

'extras' bucket:
    brave (1.4.96)
```

```
scoop install bravecustom
Installing 'bravecustom' (1.10.97) [64bit]
brave_installer-x64.exe (62.5 MB) [======================================================================================================] 100%
Checking hash of brave_installer-x64.exe ... ok.
Extracting dl.7z ... done.
Running pre-install script...
Linking ~\scoop\apps\bravecustom\current => ~\scoop\apps\bravecustom\1.10.97
Creating shim for 'brave'.
Creating shortcut for Brave (brave.exe)
'bravecustom' (1.10.97) was installed successfully!
```

I hope this help you to have an updated browser, I will keep updating my repository but as mentioned I recommend you have your own.
