### ISSUE TITLE
[Request] pcem

### ISSUE THREAD

**Issue by gphg** [lukesampson/scoop-extras#4239]
It's a IBM PC emulator software.

Wikipedia page: https://en.wikipedia.org/wiki/PCem
Site: https://pcem-emulator.co.uk/
Repo: https://bitbucket.org/pcem_emulator/pcem/

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop-extras/blob/master/bucket/pcem.json

https://scoop-docs.now.sh/apps/?query=pcem
