### ISSUE TITLE
[Request] Add Notion

### ISSUE THREAD

**Issue by relaxedricky** [lukesampson/scoop-extras#4241]
Notion is a great note-taking app (it is so much more too).

Would it be possible to have Notion added to scoop?

URL: https://www.notion.so/desktop

**Comment by TheRandomLabs** [comment]
I've got a manifest, but I can't get the checkver working. The Notion website retrieves the latest version by sending a POST request to https://www.notion.so/api/v3/getDesktopDownloadUrl with `{"platform":"windows"}`, but this doesn't seem to work with `Invoke-WebRequest`. An alternative could be to retrieve the version from [here](https://chocolatey.org/packages/notion).
<details>
    <summary>notion.json</summary>

```json
{
    "version": "2.0.8",
    "description": "Collaboration application",
    "homepage": "https://www.notion.so/product",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://desktop-release.notion-static.com/Notion%20Setup%202.0.8.exe#/dl.7z",
            "hash": "7032eaaa0fe4dd30c0656965af8c8002ffc1bef34380f91e4e94a411905a4964",
            "pre_install": [
                "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-64.7z\" -DestinationPath \"$dir\"",
                "Remove-Item \"$dir\\`$PLUGINSDIR\", \"$dir\\Uninst*\" -Recurse"
            ]
        }
    },
    "shortcuts": [
        [
            "Notion.exe",
            "Notion"
        ]
    ],
    "checkver": {
        "url": "https://www.notion.so/desktop",
        "regex": "Setup%20([\\d.]+)\\.exe"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://desktop-release.notion-static.com/Notion%20Setup%20$version.exe#/dl.7z"
            }
        }
    }
}
```
</details>

**Comment by Ash258** [comment]
https://github.com/Ash258/Scoop-Ash258/blob/master/bucket/Notion.json

**Comment by relaxedricky** [comment]
Thanks, people!
Any chance this will be added to the official repo?

**Comment by relaxedricky** [comment]
Closing as I am going to create my own bucket. Thanks all.
