### ISSUE TITLE
mp3directcut@2.29: Download failed

### ISSUE THREAD

**Issue by CypherNL** [lukesampson/scoop-extras#4249]
```
λ scoop install mp3directcut
Installing 'mp3directcut' (2.29) [64bit]
Invalid URI: The URI is empty.
URL https://www.fosshub.com/mp3DirectCut.html/mp3DC229.exe is not valid
```
It seems the download link has been changed. Copying the URL from the error line goes to https://www.fosshub.com/mp3DirectCut.html.
The download link seems to be changed to: https://www.fosshub.com/mp3DirectCut.html?dwl=mp3DC229.exe

**Comment by digrouz** [comment]
I still get error, is this supposed to work now without updating the link ?

**Comment by Ash258** [comment]
lukesampson/scoop#4051
