### ISSUE TITLE
DiskGenius language

### ISSUE THREAD

**Issue by aleppos** [lukesampson/scoop-extras#4250]
![diskgenius](https://user-images.githubusercontent.com/3524824/84257243-6f537b80-aaeb-11ea-9447-3bd8c5da00f2.png)

**Comment by Ash258** [comment]
English URLs are used by default now.

![image](https://user-images.githubusercontent.com/13260377/120377073-ee554b80-c31c-11eb-8b35-4b3cbf611d9a.png)

**Comment by pessoalzy** [comment]
The edition with English and the edition with Chinese use different licenses, which means professional license of Chinese edition (for example) won't activate the pro features of English edition. I think we should rename current package to "DiskGenius_en" or something similar.

Also, I hope someone can add Chinese edition considering maybe there are just differences in url and hash. (Links for Chinese x86 and x64 edition are respectively `https://download.eassos.cn/DG5431328_x86.zip` and `https://download.eassos.cn/DG5431328_x64.zip`)
