### ISSUE TITLE
gitextensions: checkver fails, file name format changed

### ISSUE THREAD

**Issue by BlueHeaven1969** [lukesampson/scoop-extras#4299]
gitextensions is failing on checking for updated version as the naming convention has changed.

I changed the checkver section to the following:

>     "checkver": {
>         "github": "https://github.com/gitextensions/gitextensions",
>         "regex": "v(?<version>[\\d.]+)/GitExtensions-Portable-(?<build>.*).zip"
>     },
>

**Comment by quangkieu** [comment]
Sorry but could anyone update for the new v4 version. Sorry I do not familiar with scoop rules, meta file
