### ISSUE TITLE
Atom always fails to install

### ISSUE THREAD

**Issue by simonwjackson** [lukesampson/scoop-extras#432]
```powershell
PS C:\Windows\system32> scoop install atom
Installing 'atom' (1.17.2).
atom-x64-windows.zip (128.5 MB) [=============================================================================] 100%
Checking hash of atom-x64-windows.zip... ok.
Extracting... Unzip failed: Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find a part of the p
ath 'C:\Users\user2435\scoop\apps\atom\1.17.2\_scoop_extract\Atom x64\resources\app\apm\node_modules\npm\node_modul
es\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\i
s-property\is-property.js'."
```

**Comment by lukesampson** [comment]
Does your actual username have 13 or more characters? If so the extracted path would be longer than the maximum of 260 that Windows supports.

If that sounds like it might be the problem, I've just [shortened the extract path](https://github.com/lukesampson/scoop/commit/887f041fc73946a30d3c66c19604275e54ffa9c7) from `_scoop_extract` to `_tmp` to buy 10 more characters. You can try again by running `scoop update;scoop uninstall atom;scoop install atom`.

Please let me know if that doesn't solve the problem.

**Comment by simonwjackson** [comment]
exactly 13 actually. 
This worked for me, Thanks!
