### ISSUE TITLE
gimp@2.10.20-1: decompress error

### ISSUE THREAD

**Issue by g4cm4n** [lukesampson/scoop-extras#4352]
> Download: (OK):download completed.
> Checking hash of gimp-2.10.20-setup-1.exe ... ok.
> Extracting gimp-2.10.20-setup-1.exe ... ERROR Exit code was 1!
> Failed to extract files from C:\Users\gacman\Scoop\apps\gimp\2.10.20-1\gimp-2.10.20-setup-1.exe.
> 
> 
> Log file:
>   ~\Scoop\apps\gimp\2.10.20-1\innounp.log
> 

**~\Scoop\apps\gimp\2.10.20-1\innounp.log**
Signature detected: Inno Setup Setup Data (6.0.0) (u). This is not a supported version.

**Comment by Ash258** [comment]
`scoop update innounp`
