### ISSUE TITLE
typora@0.9.90: hash check failed

### ISSUE THREAD

**Issue by Andor233** [lukesampson/scoop-extras#4406]
ERROR Hash check failed!
App:         extras/typora
URL:         https://typora.io/windows/typora-setup-x64.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    24dc5c112c73b77b52cbd9c1d8ae86abfe6a0749f549348fdecaba23a89b18a5
Actual:      77dfebc90ad8848f1ded01339e3cc30ea71f037241555f7adff515dc523cc90b

**Comment by Ash258** [comment]
8404a43e04e602e12f0f1469dc452f82ff67fcb0
