### ISSUE TITLE
[Request] Android Platform Tools

### ISSUE THREAD

**Issue by helohe** [lukesampson/scoop-extras#4412]
Can someone add the android platform tools (which contain adb and fastboot) from here:
https://developer.android.com/studio/releases/platform-tools

Direct link to download: https://dl.google.com/android/repository/platform-tools-latest-windows.zip

**Comment by kidonng** [comment]
It's in the main bucket (`adb`): https://github.com/ScoopInstaller/Main/blob/master/bucket/adb.json

**Comment by helohe** [comment]
@kidonng great thats works :+1:
