### ISSUE TITLE
Everything settings & db not persisting

### ISSUE THREAD

**Issue by worldadventurer** [lukesampson/scoop-extras#4456]
I've installed Everything ( https://github.com/lukesampson/scoop-extras/blob/master/bucket/everything.json ) and when a new version came out, my settings and database were wiped out. Investigating further, I found that "Everything.db" and "Everything.ini" are updated in the apps directory, and these two files in the persist directory are not touched by the software. I've tried uninstalling (and deleting the persist directory) and reinstalling, but the .db and .ini files in the persist directory are not being used.

The json file does call for them to persist:
    "persist": [
        "Everything.db",
        "Everything.ini"
    ],

Does this mean that Everything doesn't support keeping the .ini and .db files in a different location?

**Comment by kidonng** [comment]
See https://github.com/lukesampson/scoop/pull/2897#issuecomment-447643084
