### ISSUE TITLE
teraterm@4.105: Download failed

### ISSUE THREAD

**Issue by ChiftKey** [lukesampson/scoop-extras#4457]
Hi

I tried to install Tera-term by scoop.
but it didn't succeed. some output like below
```
Installing 'teraterm' (4.105) [64bit]
teraterm-4.105.zip (8.6 MB) [>                                                                                                                                                     ]   1%
The operation has timed out.
URL http://pumath.dl.osdn.jp/ttssh2/72009/teraterm-4.105.zip is not valid
```

I think the official link that scoop managed have some issue.
https://github.com/lukesampson/scoop-extras/blob/9e603e41f6642f77b4c1933aea7392c76a9f0d28/bucket/teraterm.json
```
"url": "http://pumath.dl.osdn.jp/ttssh2/72009/teraterm-4.105.zip",
```

I 've tried to download directly by link, also it failed..

but, I got the file via another way.
https://osdn.net/projects/ttssh2/downloads/72009/teraterm-4.105.zip/

the above link includes another way. (maybe.. mirror site??)
like this
`https://osdn.net/frs/redir.php?m=tuna&f=ttssh2%2F72009%2Fteraterm-4.105.zip`

Could you please check this?

Thanks.

**Comment by cybertim** [comment]
![image](https://user-images.githubusercontent.com/5379564/92211057-d15b1d00-ee5d-11ea-976c-0bb638d30393.png)
I also get a 503 error from scoop, when opening the URL in Edge the above page is shown.
