### ISSUE TITLE
teamviewer@15.8.3: hash check failed

### ISSUE THREAD

**Issue by escape0707** [lukesampson/scoop-extras#4474]
❯ scoop update *
teamviewer: 15.7.7 -> 15.8.3
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Updating one outdated app:
Updating 'teamviewer' (15.7.7 -> 15.8.3)
Downloading new version
Starting download with aria2 ...
Download: [#79494e 0B/0B CN:1 DL:0B]
Download: [#79494e 0B/0B CN:1 DL:0B]
Download: [#79494e 0B/0B CN:1 DL:0B]
Download: [#79494e 0B/0B CN:1 DL:0B]
Download: [#79494e 0B/0B CN:1 DL:0B]
Download: [#79494e 8.3MiB/33MiB(24%) CN:16 DL:10MiB ETA:2s]
Download: [#79494e 19MiB/33MiB(57%) CN:16 DL:11MiB ETA:1s]
Download: [#79494e 29MiB/33MiB(88%) CN:4 DL:10MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 79494e|OK  |   9.2MiB/s|C:/Users/tothe/scoop/cache/teamviewer#15.8.3#https_download.teamviewer.com_download_version_15x_TeamViewerPortable.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of TeamViewerPortable.zip ... ERROR Hash check failed!
App:         extras/teamviewer
URL:         https://download.teamviewer.com/download/version_15x/TeamViewerPortable.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    4fb8a9cfdbe5792fc06ec6a3b49b66bc00e5f9d8bce77d07e0010970f9529d67
Actual:      12427b890a2d4ae4311bafbe1abfa6aaf51235cb702cfd2f2f91d24b79c01ca0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=teamviewer%4015.8.3%3a+hash+check+failed

**Comment by everonline** [comment]
Yeah. confirmed as well.

Checking hash of TeamViewerPortable.zip ... ERROR Hash check failed!
App:         extras/teamviewer
URL:         https://download.teamviewer.com/download/version_15x/TeamViewerPortable.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    4fb8a9cfdbe5792fc06ec6a3b49b66bc00e5f9d8bce77d07e0010970f9529d67
Actual:      12427b890a2d4ae4311bafbe1abfa6aaf51235cb702cfd2f2f91d24b79c01ca0
