### ISSUE TITLE
Auto update of repository stopped working

### ISSUE THREAD

**Issue by alexanderepstein** [lukesampson/scoop-extras#448]
@r15ch13  I have updated my Sandman application but this is the first time this repo hasn't updated itself. Its been about 9 hours since the release so I would have assumed it to have shown up by now. Just letting you know this feature might be broken

**Comment by r15ch13** [comment]
Yeah, I changed the update service recently. Seems there are still some bugs...

**Comment by r15ch13** [comment]
Update service is up and running again 👍
