### ISSUE TITLE
Can't install: Calibre

### ISSUE THREAD

**Issue by cvladan** [lukesampson/scoop-extras#4482]
`calibre` can't be installed

![image](https://user-images.githubusercontent.com/1913156/88864574-d34e1280-d205-11ea-9eab-1151cae980e8.png)

 `calibre-normal` works as expected

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop-extras/issues?q=is%3Aissue+sort%3Aupdated-desc+calibre+too+long+is%3Aclosed
