### ISSUE TITLE
vcredist2015

### ISSUE THREAD

**Issue by mateusz-piotrowski** [lukesampson/scoop-extras#4487]
During installation VC Redist 2015 I received the following error.
Does anyone other had it, too?
![vcredist 2015 issue](https://user-images.githubusercontent.com/7917509/88977751-be818580-d2be-11ea-8666-0c939d37c841.PNG)

**Comment by Ash258** [comment]
https://social.msdn.microsoft.com/Forums/en-US/72457c9e-2d79-4db3-9cf2-73b2e146c0b1/vc11-redistributable-packages-exit-codes?forum=vssetup

> Especially, we are using the following codes from the runtime we previously used (VS2010), and we would like > to know if they have changed:
>  0    : Success, No reboot required
>  3010 : Success, Reboot required
>  5100 : Error, A newer version already installed

![image](https://user-images.githubusercontent.com/13260377/88978160-76af2e00-d2bf-11ea-8ff0-3d6939652092.png)

https://stackoverflow.com/a/52843294/6120775
