### ISSUE TITLE
Hash check failed for filezilla

### ISSUE THREAD

**Issue by GarciaPL** [lukesampson/scoop-extras#449]
> scoop install filezilla
Installing 'filezilla' (3.26.2).
FileZilla_3.26.2_win64.zip (9.7 MB) [=========================================================] 100%
Checking hash of FileZilla_3.26.2_win64.zip... Hash check failed for 'https://sourceforge.net/projects/filezilla/files/F
ileZilla_Client/3.26.2/FileZilla_3.26.2_win64.zip'.
Expected:
    f737b515abe8fe46c47638816caab093f43eb8666a432a2bd399aed7e31f5349
Actual:
    547a591c636e0ffb5a18d1472ccda317faa970cd1c5f2ec96aef5bf45c2e9e32

**Comment by r15ch13** [comment]
Fixed
