### ISSUE TITLE
[Request] Add RSS Guard

### ISSUE THREAD

**Issue by mark05e** [lukesampson/scoop-extras#4514]
|    |   |
| -------- | ----------- |
| Description |  RSS/Atom news feeds reader |
| Homepage | https://github.com/martinrotter/rssguard |
| Checkver | https://github.com/martinrotter/rssguard/releases |
| Portable Binaries |  https://dl.bintray.com/martinrotter/rssguard/ <br> eg: `rssguard-3.7.0-3fc4c12-win64.7z` |
| Filename format  | `<projectname>-<version>-<commit>-<platform>.<fileformat>` ([reference](https://github.com/martinrotter/rssguard/wiki/Download-file-naming)) |
| Shortcuts | `"rssguard.exe", "RSS Guard"` |
| Persistence | `data/` (folder) |
| Suggest | `"vcredist": "extras/vcredist"` |

**Comment by hoilc** [comment]
```
scoop bucket add lemon https://github.com/hoilc/scoop-lemon
scoop install rssguard
```

Move it to `scoop-extras` later.
