### ISSUE TITLE
freac@1.1.2: Download failed

### ISSUE THREAD

**Issue by dem2k** [lukesampson/scoop-extras#4517]
❯ scoop install freac
Installing 'freac' (1.1.2) [64bit]
Servererror: (404) Not found.
URL https://github.com/enzo1982/freac/releases/download/v1.1.2/freac-1.1.2a-windows-x64.zip is not valid

New URL is with 1.1.2b in filename :(

**Comment by adnaanbheda** [comment]
Working on this.
