### ISSUE TITLE
brackets@1.14.2: decompress error

### ISSUE THREAD

**Issue by Noisecommander** [lukesampson/scoop-extras#4520]
When trying to install Brackets from the extras bucket via `scoop install brackets`, I get the following error:

`Extracting Brackets.Release.1.14.2.msi ... ERROR Exit code was 1603!`
`Failed to extract files from C:\Users\<11CharacterName>\scoop\apps\brackets\1.14.2\Brackets.Release.1.14.2.msi.`
`Log file:  ~\scoop\apps\brackets\1.14.2\msi.log`

This is the content of msi.log:

`=== Logging started: 02/08/2020  17:32:52 ===`
`Error 1320. The specified path is too long: C:\Users\<11CharacterName>\scoop\apps\brackets\1.14.2\_tmp\SourceDir\Brackets\www\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan`
`=== Logging stopped: 02/08/2020  17:33:08 ===`

My Windows version is Windows 10 v10.0.19041 x64.
`Enable Win32 long paths` is enabled.

This seems to be the same issue as https://github.com/lukesampson/scoop-extras/issues/4326

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop-extras/issues/3329#issuecomment-599419935

**Comment by Noisecommander** [comment]
I apologise, I should have searched in closed issues.
`scoop config MSIEXTRACT_USE_LESSMSI $true` worked perfectly.
