### ISSUE TITLE
lunacy@6.0.0: hash check failed

### ISSUE THREAD

**Issue by peet** [lukesampson/scoop-extras#4546]
lunacy: 5.9.0 -> 6.0.0
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Updating one outdated app:
Updating 'lunacy' (5.9.0 -> 6.0.0)
Downloading new version
Starting download with aria2 ...
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 0B/0B CN:1 DL:0B]
Download: [#6f4365 7.9MiB/132MiB(5%) CN:5 DL:11MiB ETA:10s]
Download: [#6f4365 20MiB/132MiB(15%) CN:5 DL:12MiB ETA:9s]
Download: [#6f4365 31MiB/132MiB(23%) CN:5 DL:12MiB ETA:8s]
Download: [#6f4365 44MiB/132MiB(33%) CN:5 DL:12MiB ETA:7s]
Download: [#6f4365 56MiB/132MiB(43%) CN:5 DL:12MiB ETA:6s]
Download: [#6f4365 69MiB/132MiB(52%) CN:5 DL:12MiB ETA:5s]
Download: [#6f4365 82MiB/132MiB(62%) CN:5 DL:12MiB ETA:4s]
Download: [#6f4365 95MiB/132MiB(72%) CN:5 DL:12MiB ETA:2s]
Download: [#6f4365 107MiB/132MiB(81%) CN:5 DL:12MiB ETA:1s]
Download: [#6f4365 120MiB/132MiB(91%) CN:5 DL:12MiB]
Download: [#6f4365 130MiB/132MiB(98%) CN:3 DL:12MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 6f4365|OK  |    12MiB/s|C:/Users/Peet/scoop/cache/lunacy#6.0.0#https_desktop.icons8.com_lunacy_LunacySetup_6.0.0.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of LunacySetup_6.0.0.exe ... ERROR Hash check failed!
App:         extras/lunacy
URL:         https://desktop.icons8.com/lunacy/LunacySetup_6.0.0.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    acb938293b27f1f2823ed14fb9249bb0077ff8d047933de9eea0f28ecf43baec
Actual:      090f1ca701dbb6b99a40a5ad0ddc63362f7b3a86e6f5e8415745a2bbf68b4b03

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=lunacy%406.0.0%3a+hash+check+failed

**Comment by Nirose** [comment]
how long does it take for the fix to be merged?

**Comment by Ash258** [comment]
Until next version or until vendors provide reason why the file was changed.

If you believe it was changed intentionally and you believe you will not get infected, install/update with `-s` parameter
