### ISSUE TITLE
Calibre portable cannot run (path too long)

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [lukesampson/scoop-extras#4561]
Calibre (portable) as it is installed now cannot run on my computer, and presumably on any other one. It complains that the path to calibre is too long. This is composed by the way scoop installs it. On my system the path is

c:\Users\juanj\scoop\apps\calibre\current\Calibre Portable\calibre.exe

My user name is pretty short, but the whole path exceeds the 59 bytes limitation imposed by calibre, which is not likely to disappear. This problem is not present in "calibre-normal".

**Comment by Ash258** [comment]
#2535
