### ISSUE TITLE
chromium-portable@84.0.4147.125: Could not find 'ungoogled-chromium-84.0.4147.125-1_windows'! (error 16)

### ISSUE THREAD

**Issue by digitalentiert** [lukesampson/scoop-extras#4568]
Could not find 'ungoogled-chromium-84.0.4147.125-1_windows'! (error 16)
In D:\scoop\apps\scoop\current\lib\core.ps1:510 Zeichen:9
    throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : OperationStopped: (Could not find ...ws'! (error 16):String) [], RuntimeException
    FullyQualifiedErrorId : Could not find 'ungoogled-chromium-84.0.4147.125-1_windows'! (error 16)

**Comment by Ash258** [comment]
There is no `chromium-portable` manifest in Extras

**Comment by shutaozhenzhen** [comment]
> 
> 
> There is no `chromium-portable` manifest in Extras

The `chromium-portable` just means `chromium` manifest in Extras. And there is already a Pull request to solve this by @4571 .
