### ISSUE TITLE
[Request] Add rdpwrap

### ISSUE THREAD

**Issue by 7wells** [lukesampson/scoop-extras#4633]
Hello,

Could you please consider adding rdpwrap?
https://github.com/stascorp/rdpwrap

Optionally with autoupdate:
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

Thank you so much!

**Comment by Ash258** [comment]
Installation has to be done in Program files. Not suitable for official bucket

**Comment by 7wells** [comment]
Oh, sorry.
