### ISSUE TITLE
[Request] Add tcpdump

### ISSUE THREAD

**Issue by 7wells** [lukesampson/scoop-extras#4722]
Hello,

Would you mind adding this? https://github.com/the-tcpdump-group/tcpdump
See also there: https://www.tcpdump.org/
The tcpdump package is included in many Linux distributions.

Thank you so much for your kind consideration.

**Comment by Ash258** [comment]
There is no download for windows binaries

**Comment by 7wells** [comment]
Blimey, I should have checked that first - I am really sorry. :blush:

Would these instead be adequate?
WinPcap: https://www.winpcap.org/install/default.htm
WinDump: https://www.winpcap.org/windump/install/default.htm
