### ISSUE TITLE
[Request] Add PowerShell

### ISSUE THREAD

**Issue by 7wells** [lukesampson/scoop-extras#4733]
Hello,

Would you mind adding this? https://github.com/PowerShell/PowerShell/releases
Please also note that there are pre-releases and latest release (currently, v7.1.0-preview.7, v7.1.0-preview.6, and v7.0.3 Release).

I suggest the v7.0.3 Release:

https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-7.0.3-win-x64.zip
SHA256 hash: FEE749388A399FEFDB746E2B26E7B4E654C3CFEF1C19CCAFD14909AC46E35382

https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-7.0.3-win-x86.zip
SHA256 hash: CBF7A8D46D685A29FA8F05B91F40437A6577682AD3A02AE3CAC20B9A89C901AC

Thank you so much for your kind consideration.

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Main/blob/master/bucket/pwsh.json

**Comment by 7wells** [comment]
Ok, I looked into the 'extras' bucket and searched for 'power' but did not find 'powershell', hence my request. Next time, I will definitely also search in the 'main' bucket - promised! ;)
