### ISSUE TITLE
honeyview@5.35: hash check failed

### ISSUE THREAD

**Issue by Mosney** [lukesampson/scoop-extras#4760]
> Checking hash of HONEYVIEW-SETUP.EXE ... ERROR Hash check failed!
> App:         extras/honeyview
> URL:         https://dl.bandisoft.com/honeyview/HONEYVIEW-SETUP.EXE
> First bytes: 4D 5A 90 00 03 00 00 00
> Expected:    40a98e793d7d24daab38a4252cb0f639d77210a791a6f01e93673c49ba4829d8
> Actual:      c782e99e753d18b9917b556e10991aa237be08ec7447e3619c56c01487bbb22d
> 
> Please try again or create a new issue by using the following link and paste your console output:
> https://github.com/lukesampson/scoop-extras/issues/new?title=honeyview%405.35%3a+hash+check+failed

I try download manually, its SHA256 value is true C782E99E753D18B9917B556E10991AA237BE08EC7447E3619C56C01487BBB22D. May honeyview update their installer?

**Comment by Hisssy** [comment]
>Checking hash of HONEYVIEW-SETUP.EXE ... ERROR Hash check failed!
App:         extras/honeyview
URL:         https://dl.bandisoft.com/honeyview/HONEYVIEW-SETUP.EXE
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    c782e99e753d18b9917b556e10991aa237be08ec7447e3619c56c01487bbb22d
Actual:      b557688d4c6e076f212c7d4dc8b1db005a87c060b1db3f6e36330ce2a9a1d55a

Maybe they change the binary again?

**Comment by Mosney** [comment]
@Hisssy Just creat issue by error log in the scoop, bot will auto check and correct
