### ISSUE TITLE
Fork crashes

### ISSUE THREAD

**Issue by Skyline404** [lukesampson/scoop-extras#4786]
Fork crashes at startup after last update, but launches ok if non-scopp fork installed

**Comment by DanPristupov** [comment]
I just became aware of this. The problem is that scoop removes the git instance in the fork directory.

Fork 1.54 makes some maintenance and doesn't expect that the default installation directory is modified (corrupted?) which leads to the crash.

**Comment by dsbert** [comment]
See https://github.com/ForkIssues/TrackerWin/issues/958

**Comment by oerpli** [comment]
With the recently released version (currently 1.55.2) this issue seems to be fixed.

**Comment by DanPristupov** [comment]
@oerpli yes, I fixed the problem.
