### ISSUE TITLE
Comparing checksums on edge builds will fail

### ISSUE THREAD

**Issue by edmulraney** [lukesampson/scoop-extras#484]
I may be wrong but it looks as if you're trying to validate edge build checksums when downloading:
```
sudo scoop install slack --global
Installing 'slack' (2.6.5).
SlackSetup.exe (73.2 MB) [==============================================================] 100%
Checking hash of SlackSetup.exe... Hash check failed for 'https://downloads.slack-edge.com/release
s_x64/SlackSetup.exe'.
Expected:
    2a1578fa1d519103dd8a8e0032a45633de0458745cd6ce850e4a345711e6a85f
Actual:
    ca066f549428c15b307aba81f9018747d22ed662e17ee6cce36b601dff323d47
```

If it's not a fixed version it's expected to change checksum often.

**Comment by r15ch13** [comment]
It works when they update the files before changing the version on the website.
Only the 32bit version got the updated hash:
https://github.com/lukesampson/scoop-extras/commit/b2ea084517d385d5a7ea798fa98f59a96f185cb3

**Comment by edmulraney** [comment]
How do I get slack to install? Can I manually fudge the checksum somewhere? Only started using scoop yesterday,

**Comment by r15ch13** [comment]
`scoop update` and `scoop install slack` should work now.
