### ISSUE TITLE
calibre-normal@5.0.1: download via aria2 failed

### ISSUE THREAD

**Issue by mperin** [lukesampson/scoop-extras#4848]
Version 5.0.1 binaries aren't any more available, it has been replaced by 5.1.0.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/kovidgoyal/calibre/releases/download/v5.0.1/calibre-64bit-5.0.1.msi
    referer=https://github.com/kovidgoyal/calibre/releases/download/v5.0.1/
    dir=C:\Users\mperin\scoop\cache
    out=calibre-normal#5.0.1#https_github.com_kovidgoyal_calibre_releases_download_v5.0.1_calibre-64bit-5.0.1.msi

ERROR & 'C:\Users\mperin\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\mperin\scoop\cache\calibre-normal.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.0 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=10340 --continue

**Comment by Ash258** [comment]
c50d43925755173440bacb121c59eb557ea39b52, c8ee5ba924748d5bc26d1035f4fe45f32c80c22c
