### ISSUE TITLE
Cloud Foundry CLI version 6 is broken

### ISSUE THREAD

**Issue by akelsch** [lukesampson/scoop-extras#4851]
The binary of app cloudfoundry-cli was changed from `cf.exe` to `cf7.exe` in #4353 but it does not exist in version 6 making versions prior to 7 unable to install:

```
> scoop install cloudfoundry-cli
Installing 'cloudfoundry-cli' (6.53.0) [64bit]
Loading dl.7z from cache
Checking hash of dl.7z ... ok.
Extracting dl.7z ... done.
Linking ~\scoop\apps\cloudfoundry-cli\current => ~\scoop\apps\cloudfoundry-cli\6.53.0
Creating shim for 'cf7'.
Can't shim 'cf7.exe': File doesn't exist.

> scoop status
Scoop is up to date.
These app manifests have been removed:
    cloudfoundry-cli
These apps failed to install:
    cloudfoundry-cli
```

What's even worse is that you can install 6 after 7 but trying to use 6 will essentially create a fork bomb.

![Screenshot 2020-10-02 141641](https://user-images.githubusercontent.com/28652314/94922262-2ec4a700-04ba-11eb-8690-da094990e8e9.png)

CF [7.0.0](https://github.com/cloudfoundry/cli/releases/tag/v7.0.0) and [7.0.1](https://github.com/cloudfoundry/cli/releases/tag/v7.0.1) Windows binaries did not include a `cf.exe` which was the reason for the change (see the Known Issues sections). Starting with 7.0.2, `cf.exe` is included again, being a 1:1 copy of `cf7.exe`. Can we change the binary back to `cf.exe`? Or perhaps a dedicated manifest for version 7 would be better, I am not sure.

**Comment by akelsch** [comment]
@Ash258 @r15ch13 do you have any opinion on this? Unfortunately, the package is still broken.

I can help in creating a PR but I am not sure which solution would be the best. Chocolatey is using the same package for version 6 and 7.

**Comment by dnperfors** [comment]
I just installed the cli and hit the same issue. If CF 7 now also includes `cf.exe`, I think it would be best to always use that, since that is backwards compatible with older versions.

**Comment by dwettstein** [comment]
Same issue with version 8 again, see https://github.com/lukesampson/scoop-extras/issues/6946.
