### ISSUE TITLE
Merge Inkscape versions

### ISSUE THREAD

**Issue by rasa** [lukesampson/scoop-extras#486]
Merge
https://github.com/lukesampson/scoop-extras/blob/master/inkscape.json
and
https://github.com/lukesampson/scoop-extras/blob/master/inkscape32bit.json
as they appear to be the same.

**Comment by r15ch13** [comment]
It's not possible to merge them, because of the random value in each download URL:

httpx://inkscape.org/gallery/item/**10686**/Inkscape-0.92.1.7z
httpx://inkscape.org/gallery/item/**10687**/Inkscape-0.92.1-x64.7z

**Comment by rasa** [comment]
Gotcha. I didn't see that.

**Comment by rasa** [comment]
This could be addressed by supporting checkver under autoupdate/architecture. Is it worth the effort?

**Comment by r15ch13** [comment]
Apparently, I had this in mind a while back when I worked on the [schema.json#L78](https://github.com/lukesampson/scoop/blob/master/schema.json#L78), but it's not implemented yet. :smile:
Also, I can't remember which program had the same problem, I am sure there is another one...
