### ISSUE TITLE
[Request] Update webpage for ffmpeg, ffmpeg-nightly and ffmpeg-shared

### ISSUE THREAD

**Issue by minhngoc25a** [lukesampson/scoop-extras#4876]
Zeranoe [had announced](https://twitter.com/Zeranoe/status/1300596971934224385) that he would close his website for ffmpeg builds. Can you update the links to install ffmpeg? Two devs are willing to compile ffmpeg and provide builds. 

Link to the websites: https://ffmpeg.org/download.html

**Comment by Ash258** [comment]
Wrong repo

There are already lots of issues about this in Main
