### ISSUE TITLE
please update android-studio info

### ISSUE THREAD

**Issue by OCD0711** [lukesampson/scoop-extras#4903]
new version is 4.0.2

**Comment by chengxuncc** [comment]
[Android Studio 4.1.0.19](https://redirector.gvt1.com/edgedl/android/studio/install/4.1.0.19/android-studio-ide-201.6858069-windows.exe) now.

**Comment by chengxuncc** [comment]
Android Studio doesn't support 32 bit version anymore, update checker failed.
