### ISSUE TITLE
xnviewmp@0.97.0: hash check failed

### ISSUE THREAD

**Issue by jeham** [lukesampson/scoop-extras#4911]
xnviewmp: 0.96.5 -> 0.97.0
Updating one outdated app:
Updating 'xnviewmp' (0.96.5 -> 0.97.0)
Downloading new version
XnViewMP-win-x64.zip (97,7 MB) [=======================================================================================================================================================================] 100%
Checking hash of XnViewMP-win-x64.zip ... ERROR Hash check failed!
App:         extras/xnviewmp
URL:         https://download.xnview.com/XnViewMP-win-x64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    146fa8d3ef519ecc49463e1e6573eb35fcbf9f692c44f487408a25fcf7f74781
Actual:      f29791514ebde0f589d69227511909dc01aecc8d3ace923eba73479c22f00b39

**Comment by Ash258** [comment]
9e3dbd55a7220382589b4e85e1da3f466765d493
