### ISSUE TITLE
mplayer sha256 hash is incorrect. 

### ISSUE THREAD

**Issue by lechanhtin2000** [lukesampson/scoop-extras#492]
Checking hash of mplayer-svn-37946-5-x86_64.7z... Hash check failed for 'https://sourceforge.net/projects/mplayerwin/files/MPlayer-MEncoder/r37946-5/mplayer-svn-37946-5-x86_64.7z'.
Expected:
    138bafb2eca25a7c1e4945476f9144e2a2243d3bb8687470cc2578da90280bf5
Actual:
    438d4cb917d93d4dde8ffdc88061c87a624fe06f796f8e0a180fe307270f6e0b

**Comment by r15ch13** [comment]
Fixed
