### ISSUE TITLE
slack.json doesn't have the right hash

### ISSUE THREAD

**Issue by mundusnine** [lukesampson/scoop-extras#494]
Installing 'slack' (2.6.5).
SlackSetup.exe (69.9 MB) [============================================] 100%
Checking hash of SlackSetup.exe... Hash check failed for 'https://downloads.slack-edge.com/releases_x64/SlackSetup.exe'.
Expected:
    ca066f549428c15b307aba81f9018747d22ed662e17ee6cce36b601dff323d47
Actual:
    c3e9385e3099b27fa62beac2d2d41064d939b39b6853e3c71c5b3c9f757dcc1d

**Comment by r15ch13** [comment]
Please run `scoop update` and try again. ca066f54 is the hash of the old version 2.6.5.
