### ISSUE TITLE
vlc - impossible to install

### ISSUE THREAD

**Issue by 4ureli1** [lukesampson/scoop-extras#4940]
Hello,

I try to install vlc but an error occur:
`URL https://download.videolan.org/pub/vlc/3.0.8/win64/vlc-3.0.8-win64.7z is not valid`

my computer: windows 10 (64bits), powershell

**Comment by Boscop** [comment]
The issue is back again:

Whenever I start vlc, I get an additional empty console window like this:

![image](https://user-images.githubusercontent.com/535593/213872599-548b59d3-4e5b-4d3e-a644-eef3dfb0da8e.png)

And when I close it, VLC is also terminated :(

How can I fix this? :)

**Comment by Boscop** [comment]
Any idea how to fix this? It's still happening with a scoop-installed VLC.

**Comment by HUMORCE** [comment]
> Any idea how to fix this? It's still happening with a scoop-installed VLC.

According to your screenshot, vlc's shim has been assigned to media files.

Cannot reproduct when actual vlc.exe assigned:

![Screenshot_230825091623](https://github.com/ScoopInstaller/Extras/assets/4353480/3766e297-070b-45d7-bba6-98deabff84f0)

Reproduction:

![Screenshot_230825092333](https://github.com/ScoopInstaller/Extras/assets/4353480/9a5b55c8-47dd-4617-a3de-599004ea35e1)

1. install vlc
2. Assigning vlc's shim(\<SCOOP>\shims\vlc.exe) to mp4 file
3. click the mp4 file
4. re-assigning the actual vlc.exe(\<SCOOP>\apps\vlc\current\vlc.exe) via the context menu, but path of vlc.exe on resigitry seems not updated. (This may a Windows OS bug

Solution:

![Screenshot_230825093745](https://github.com/ScoopInstaller/Extras/assets/4353480/8b37e61f-e559-41d5-b3a9-ecf631b13f03)

1. open registry editor, locate to `Computer\HKEY_CLASSES_ROOT\Applications\vlc.exe`, delete it. OR `Remove-Item registry::HKEY_CLASSES_ROOT\Applications\vlc.exe`
2. re-assigning the actual vlc.exe(\<SCOOP>\apps\vlc\current\vlc.exe) for media files
