### ISSUE TITLE
VSCode provide 64 bits for Windows from 1.15.0

### ISSUE THREAD

**Issue by liaoya** [lukesampson/scoop-extras#495]
From 1.15.0, VSCode provide 64 bits version form WIndows. Would you please update its definition. 

The 64 bits download url is <https://vscode-update.azurewebsites.net/1.15.0/win32-x64-archive/stable> for version 1.15.0, the sha256 value for version 1.15.0 is `1ed7ef52eab2b5fbb2b7a28e83cc07b69da2f223e49222cac67372005a467b81`.

**Comment by liaoya** [comment]
The following is my vscode.json for 1.15.0

   {
       "homepage": "https://code.visualstudio.com/",
       "version": "1.15.0",
       "license": "https://code.visualstudio.com/License/",
       "notes": "Want to add vscode as a context menu option in explorer? See this guide: http://thisdavej.com/right-click-on-windows-folder-and-open-with-visual-studio-code/",
       "architecture": {
           "64bit": {
               "url": "https://vscode-update.azurewebsites.net/1.15.0/win32-x64-archive/stable#/dl.7z",
               "hash": "1ed7ef52eab2b5fbb2b7a28e83cc07b69da2f223e49222cac67372005a467b81"
           },
           "32bit": {
               "url": "https://vscode-update.azurewebsites.net/1.15.0/win32-archive/stable#/dl.7z",
               "hash": "cab65c12e6cb8b7e3dcd58c3f2d779d00204a3436e3afe59da05c5f9a7c1f0a3"
           }
       },
       "bin": [
           [
               "bin\\code.cmd",
               "code"
           ]
       ],
       "shortcuts": [
           [
               "code.exe",
               "Visual Studio Code"
           ]
       ],
       "checkver": {
           "url": "https://vscode-update.azurewebsites.net/api/releases/stable/win32",
           "jp": "$.[0]"
       },
       "autoupdate": {
           "url": "https://vscode-update.azurewebsites.net/$version/win32-archive/stable#/dl.7z"
       }
   }

**Comment by r15ch13** [comment]
Added with #496 👍
