### ISSUE TITLE
q-dir@8.97: hash check failed

### ISSUE THREAD

**Issue by yuhlzu** [lukesampson/scoop-extras#5007]
Checking hash of Q-Dir_Portable_x64.zip ... ERROR Hash check failed!
App:         extras/q-dir
URL:         https://www.softwareok.com/Download/Q-Dir_Portable_x64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    2b545a2eeb376731db8798909f782280f3eb33ec5bf826c8d0901d82b60011a3
Actual:      c050324775faf02c05cd3a1690e82f509c2ef4aacc9109ae5b9b6d44074a21e0

**Comment by Ash258** [comment]
382a8c4af1ef3f4f0ad40cd5a64f3078bfcd05c0
