### ISSUE TITLE
x64dbg@2020-11-05_02-49: download via aria2 failed

### ISSUE THREAD

**Issue by oceanborn2** [lukesampson/scoop-extras#5062]
It seems version "snapshot_2020-11-05_02-49" is not available anymore.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2020-11-05_02-49.zip
    referer=https://github.com/x64dbg/x64dbg/releases/download/snapshot/
    dir=C:\software\scoop\cache
    out=x64dbg#2020-11-05_02-49#https_github.com_x64dbg_x64dbg_releases_download_snapshot_snapshot_2020-11-05_02-49.zip

ERROR & 'C:\software\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\software\scoop\cache\x64dbg.txt' --user-agent='Scoop/1.0
(+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry
-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --f
ollow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=12348 --continue --summary-int
erval 0

**Comment by Ash258** [comment]
66acdd321b958c3d1501d94e25896c8aeca25b32
