### ISSUE TITLE
emacs@27.1: hash check failed

### ISSUE THREAD

**Issue by nhkim61** [lukesampson/scoop-extras#5067]
emacs-27.1-x86_64.zip (102.6 MB) [======>                                             ]  13%
App:         extras/emacs
URL:         https://ftpmirror.gnu.org/gnu/emacs/windows/emacs-27/emacs-27.1-x86_64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    65f1b01bcd14e59d7da0ebad3979c5df9f9bd8d24b2ff2e32a5af3aacb226229
Actual:      3562a8eed72930aac9deee4a10244706d138f084660c198c11158ac90c5ceeb8

try again   .//  same

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/98439214-a062c700-20f0-11eb-9ba5-27d575298308.png)
