### ISSUE TITLE
[Request] Add czkawka

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [lukesampson/scoop-extras#5141]
An awesome, fast deduplicator: https://github.com/qarmin/czkawka/releases

**Comment by earnestma** [comment]
There is both a cli and gui. I don't think the gui depends on the cli, however any thoughts on how they should be packaged?

Also, launching the gui brings up a console window - any way to avoid that?

**Comment by qarmin** [comment]
I removed console window in gui in this commit - https://github.com/qarmin/czkawka/pull/116

**Comment by earnestma** [comment]
@qarmin that's great!

Should the cli be placed in the [Main bucket](https://github.com/ScoopInstaller/Main) and gui here in Extras?

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Main/blob/master/bucket/czkawka.json

**Comment by camjac251** [comment]
Could this be reopened for the GUI? I could try and make a manifest file for it
