### ISSUE TITLE
conemu@20.11.23: download via aria2 failed

### ISSUE THREAD

**Issue by patevs** [lukesampson/scoop-extras#5169]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/Maximus5/ConEmu/releases/download/v20.11.23/ConEmuPack.201123.7z
    referer=https://github.com/Maximus5/ConEmu/releases/download/v20.11.23/
    dir=C:\Users\User\scoop\cache
    out=conemu#20.11.23#https_github.com_Maximus5_ConEmu_releases_download_v20.11.23_ConEmuPack.201123.7z

**Comment by b-palaniappan** [comment]
correct download location is [https://github.com/Maximus5/ConEmu/releases/download/v20.11.23a/ConEmuPack.201123a.7z](https://github.com/Maximus5/ConEmu/releases/download/v20.11.23a/ConEmuPack.201123a.7z)

**Comment by umbellipher** [comment]
I don't know whether this is a related 404 error, but I get:

Updating 'conemu' (20.11.22 -> 20.11.23)
Downloading new version
OperationStopped: C:\Users\xxxx\scoop\apps\scoop\current\lib\install.ps1:130
Line |
 130 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.

**Comment by Ash258** [comment]
5172b4a5b4ef8e8726fa44a572200021555889a3
