### ISSUE TITLE
furmark@1.23.0.0: decompress error

### ISSUE THREAD

**Issue by PorridgePi** [lukesampson/scoop-extras#5213]
I have previously created issue #5191 which is about hash check failed and there is already a pull request #5188 to fix it.

Then, I tried to install it with the hash check skipped, but I recieved decompress error instead.
I checked the innounp log and it seems like the Inno Setup Unpacker does not yet support the new Inno Setup 6.1.0. This is already raised at [Inno Setup Unpackers's SourceForge Discussion](https://sourceforge.net/p/innounp/discussion/353235/thread/23cf78c92c/).

Thus, I think this is not a scoop issue, and is probably why the pull request has not been merged yet.

I guess this also answers @magneticflux-'s question in https://github.com/lukesampson/scoop-extras/issues/5188#issuecomment-735298085.

This issue probably is not related but I just want to point out what is happening.

innounp.log:
```
Signature detected: Inno Setup Setup Data (6.1.0) (u)
This is not directly supported, but i'll try to unpack it as version 6000
; Version detected: 6100 (Unicode)
Unpacking failed. This version is not supported.                                                                                                                             
```

scoop log:
```
>>> scoop install furmark -s
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'furmark' (1.23.0.0) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 8d8d60|OK  |   1.0MiB/s|D:/AppData/scoop//cache/furmark#1.23.0.0#https_www.geeks3d.com_downloads_2020p_FurMark_1.23.0.0_Setup.exe
Download: Status Legend:
Download: (OK):download completed.
Extracting FurMark_1.23.0.0_Setup.exe ... ERROR Exit code was 1!
Failed to extract files from D:\AppData\scoop\apps\furmark\1.23.0.0\FurMark_1.23.0.0_Setup.exe.
Log file:
  D:\AppData\scoop\apps\furmark\1.23.0.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=furmark%401.23.0.0%3a+decompress+error
```

**Comment by magneticflux-** [comment]
It seems like the issue was also raised last month on the Inno Setup Unpacker Sourceforge page [here](https://sourceforge.net/p/innounp/discussion/353235/thread/4a7e2b1f19/?limit=25#6f3b).

**Comment by magneticflux-** [comment]
It looks like it's just an issue with header fields being changed between `6.0.5` and `6.1.x`. Inno Setup Unpacker doesn't have a source code repository so I can't easily contribute a fix, but it should be as simple as creating a new `StructXXXXu.pas` with the contents of the current `Struct.pas` from Inno Setup itself: https://github.com/jrsoftware/issrc/blob/main/Projects/Struct.pas

**Comment by PorridgePi** [comment]
The source code of Inno Setup Unpacker is available [here](https://sourceforge.net/projects/innounp/files/innounp/innounp%200.49/innounp049src.rar). Like you said, I think just creating a new `StructXXXXu.pas` may fix it. 

I have tried to compile it but my computer is running out of space to install the whole Delphi Community Edition so I can't compile it. 

Is it possible for you to help compile a new Unpacker with the changes made to see if it fixes the problem? Thanks!

**Comment by magneticflux-** [comment]
Sorry! I'm honestly not invested enough to download an entire (from what I can tell, extremely jank) toolchain and learn Pascal/Delphi/Object Pascal/whatever it's called.

**Comment by PorridgePi** [comment]
Haha, it's alright. Neither did I want to install it at first, but I still tried. And it ended up taking all the remaining space in my C drive, leaving 0kb available. Indeed a piece of junk.

If only it was available on scoop.

Thanks still! Hopefully someone would fix it soon.
