### ISSUE TITLE
kitty@0.74.3.3: Download failed

### ISSUE THREAD

**Issue by aleppos** [lukesampson/scoop-extras#5230]
kitty: 0.74.3.1 -> 0.74.3.3
Updating one outdated app:
Updating 'kitty' (0.74.3.1 -> 0.74.3.3)
Downloading new version
OperationStopped: C:\Users\emada\scoop\apps\scoop\current\lib\install.ps1:130
Line |
 130 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.

**Comment by Ash258** [comment]
59e4fa6bc57695073213ce8a17a89bb7c689ad30
