### ISSUE TITLE
[Request] Amulet Editor

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop-extras#5281]
> # [Amulet Map Editor](https://github.com/Amulet-Team/Amulet-Map-Editor)
>
> ![Build](https://github.com/Amulet-Team/Amulet-Map-Editor/workflows/Build/badge.svg) ![Unittests](https://github.com/Amulet-Team/Amulet-Map-Editor/workflows/Unittests/badge.svg?event=push) ![Stylecheck](https://github.com/Amulet-Team/Amulet-Map-Editor/workflows/Stylecheck/badge.svg?event=push) [![Documentation Status](https://readthedocs.org/projects/amulet-map-editor/badge)](https://amulet-map-editor.readthedocs.io)
>
> A new Minecraft world editor and converter that supports all versions since Java 1.12 and Bedrock 1.7.
>
> ![edit](https://raw.githubusercontent.com/Amulet-Team/Amulet-Map-Editor/master/resource/img/edit.jpg)
>
> ## Running compiled builds
>
> Download the zip file for your operating system from the list of [compiled builds](https://github.com/Amulet-Team/Amulet-Map-Editor/releases). (Currently Windows only)
>
> Extract the contained folder to a location on your computer and run the executable.

**Comment by earnestma** [comment]
@NatoBoram https://github.com/Calinou/scoop-games/pull/176 has been merged into the games bucket! If you haven't added it, `scoop bucket add games` then `scoop install amulet-map-editor`.

**Comment by NatoBoram** [comment]
Thanks!
