### ISSUE TITLE
keepass@2.46: download via aria2 failed

### ISSUE THREAD

**Issue by CodeNovice2017** [lukesampson/scoop-extras#5294]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://downloads.sourceforge.net/project/keepass/KeePass%202.x/2.46/KeePass-2.46.zip
    dir=C:\Users\Veigar\scoop\cache
    out=keepass#2.46#https_downloads.sourceforge.net_project_keepass_KeePass_202.x_2.46_KeePass-2.46.zip

ERROR & 'C:\Users\Veigar\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Veigar\scoop\cache\keepass.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=22436 --continue --summary-interval 0 --all-proxy='127.0.0.1:7890'

**Comment by rasa** [comment]
Worked for me, please try again. If this is still an issue, please reopen this. Thanks!
