### ISSUE TITLE
cpu-z 

### ISSUE THREAD

**Issue by mriehema** [lukesampson/scoop-extras#530]
I got an hash error:

λ scoop install cpu-z
Installing 'cpu-z' (1.80).
cpu-z_1.80-en.zip (2,5 MB) [=======================] 100%
Checking hash of cpu-z_1.80-en.zip... Hash check failed for 'http://download.cpuid.com/cpu-z/cpu-z_1.80-en.zip'.
Expected:
    5644b3beb34d7ec2a2650fe2ba0d3496d19632c3301819907f2248b9819d8ef5
Actual:
    3c2fdb6f79cb2f1a2dac9ace906956b4b9f6f0ff6bb0d5f98ab15f335c0b73ad

**Comment by r15ch13** [comment]
Fixed, please run `scoop update` and try again 👍

**Comment by mriehema** [comment]
wow, awesome. that was fast. love it.
