### ISSUE TITLE
gcc-arm-none-eabi@10-2020-q4-major: Path to binaries is wrong

### ISSUE THREAD

**Issue by Tiwalun** [lukesampson/scoop-extras#5311]
The newest version of gcc-arm-none-eabi contains an additional folder level in the zip file, which means that the binaries are not accessible anymore.

In version 9-2020-q2-update, the path to the folder with the binaries looked like this, relative to the zip file:

    bin\

but in the newest version it looks like this:

    gcc-arm-none-eabi-10-2020-q4-major\bin\

**Comment by jhillyerd** [comment]
TL_PATH environment variable is also set to a directory that does not exist.

**Comment by jhillyerd** [comment]
cc @r15ch13
