### ISSUE TITLE
Can't install Libreoffice 7.0.4.2 

### ISSUE THREAD

**Issue by wicast** [lukesampson/scoop-extras#5327]
![屏幕截图 2020-12-18 135710](https://user-images.githubusercontent.com/2603937/102581357-5cc19b00-413b-11eb-94e3-a2c5f40b0aa5.jpg)

I've tried several times but still the same result.

**Comment by b-reich** [comment]
I have the same problem
```
PS C:\Users\benja> scoop install libreoffice-fresh
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'libreoffice-fresh' (7.0.4.2) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 9341a0|OK  |   550KiB/s|C:/Users/benja/scoop/cache/libreoffice-fresh#7.0.4.2#https_downloadarchive.documentfoundation.org_libreoffice_old_7.0.4.2_win_x86_64_LibreOffice_7.0.4.2_Win_x64.msi
Download: 9332d5|OK  |    45MiB/s|C:/Users/benja/scoop/cache/LibreOffice_7.0.4.2_Win_x64.msi
Download: Status Legend:
Download: (OK):download completed.
Checking hash of LibreOffice_7.0.4.2_Win_x64.msi ... ok.
Extracting LibreOffice_7.0.4.2_Win_x64.msi ... Could not find 'LibreOffice'! (error 16)
In C:\Users\benja\scoop\apps\scoop\current\lib\core.ps1:510 Zeichen:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'LibreOffice'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'LibreOffice'! (error 16)
```

**Comment by StarsbySea** [comment]
Temporary solution: Find the file libreoffice-fresh.json on your computer. Delete the line "extract_dir": "LibreOffice", and install it again.

**Comment by SharakPL** [comment]
Just tried installing new version 7.1.0.3 with scoop but it's all the same again 😞 

> Extracting LibreOffice_7.1.0.3_Win_x64.msi ... Could not find 'LibreOffice'! (error 16)

Could this be the problem?

![obraz](https://user-images.githubusercontent.com/5007456/107102598-44a4f880-681b-11eb-9165-1ca94a732269.png)

What is `innounp` and `dark` for and why doesn't Scoop install it automatically as a dependency if it's required for Scoop to work properly? Or is it just for unpacking specific types of packages? Installed Scoop on a lot of devices and never noticed documentation to mention such requirements.

**Comment by SharakPL** [comment]
Still not fixed. It's all the same with `Could not find 'LibreOffice`!` error 😞

**Comment by wicast** [comment]
Same here.
