### ISSUE TITLE
Onlyoffice not updating to 6.1.0

### ISSUE THREAD

**Issue by pigsflew** [lukesampson/scoop-extras#5355]
It looks like they tagged version 6.1.0 differently (the tag name is `v6.1.0` not `ONLYOFFICE-DesktopEditors-6.1.0` like the regex is expecting.

**Comment by pigsflew** [comment]
yeah, it looks like:

- the release tag name is now [just the version](https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/v6.1.0)
- The exe filenames now include a build number and the prefix `ONLYOFFICE`.

Old: 
`https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/ONLYOFFICE-DesktopEditors-6.0.2`
`https://github.com/ONLYOFFICE/DesktopEditors/releases/download/ONLYOFFICE-DesktopEditors-6.0.2/DesktopEditors_x64.exe`
New:
`https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/v6.1.0`
`https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v6.1.0/ONLYOFFICE_DesktopEditors_6.1.0.90_x64.exe`

idk where to get that ".90" from...

**Comment by linsui** [comment]
Change the regex to match `ONLYOFFICE_DesktopEditors_6.1.0.90_x64.exe`, i.e., `ONLYOFFICE_DesktopEditors_([\\d.]+)_x64\.exe`.
