### ISSUE TITLE
add hash to vscode.json autoupdate

### ISSUE THREAD

**Issue by h404bi** [lukesampson/scoop-extras#537]
Found vscode sha api. whether someone know how to handle it. 
```
https://code.visualstudio.com/sha?build=stable
```

**Comment by r15ch13** [comment]
Thanks! This lead me to implement querying JSON with JSONPath using `Newtonsoft.Json` instead of our self-made function 😁👍

https://github.com/lukesampson/scoop/commit/82ec0fe7a11c1fc0db39cb51b671a5650c1252c8

**Comment by h404bi** [comment]
awesome! I should learn how to use that JSONPath querying stuff.
