### ISSUE TITLE
[Request] Add Sumatra PDF

### ISSUE THREAD

**Issue by zzfnohell** [lukesampson/scoop-extras#5384]
Sumatra PDF is a free PDF, eBook (ePub, Mobi), XPS, DjVu, CHM, Comic Book (CBZ and CBR) reader for Windows.

https://www.sumatrapdfreader.org/free-pdf-reader.html

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/103267179-78d20180-49b1-11eb-83f4-5527dc4023f1.png)
