### ISSUE TITLE
mkvtoolnix@51.0.0: mkvtoolnix-gui.ini copied not hardlinked

### ISSUE THREAD

**Issue by redactedscribe** [lukesampson/scoop-extras#5386]
If `mkvtoolnix-gui.ini` is present in the `persist` directory, scoop sees this when installing the app and copies the ini to the relevant `apps` dir. If there is no ini in the `persist` dir, scoop creates one in the relevant `apps` dir.

That's the problem: scoop copies the present file rather than hardlinks it. On uninstallation of the app, the ini is again copied but now to the relevant `persist` dir. This means the `persist` dir ini is only ever up-to-date when the app is installed or uninstalled. This isn't ideal when backing-up the `persist` dir to the cloud.

```
PS C:\Users\x> scoop install mkvtoolnix
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'mkvtoolnix' (51.0.0) [64bit]
Loading mkvtoolnix-64-bit-51.0.0.7z from cache.
Checking hash of mkvtoolnix-64-bit-51.0.0.7z ... ok.
Extracting mkvtoolnix-64-bit-51.0.0.7z ... done.
Running pre-install script...
Linking ~\scoop\apps\mkvtoolnix\current => ~\scoop\apps\mkvtoolnix\51.0.0
Creating shim for 'mkvextract'.
Creating shim for 'mkvinfo'.
Creating shim for 'mkvmerge'.
Creating shim for 'mkvpropedit'.
Creating shim for 'mkvtoolnix-gui'.
Creating shortcut for MKVToolNix GUI (mkvtoolnix-gui.exe)
Persisting cache
Persisting jobQueue
'mkvtoolnix' (51.0.0) was installed successfully!
```

There is no output mentioning persisting `mkvtoolnix-gui.ini`.

```
PS C:\Users\x> scoop uninstall mkvtoolnix
Uninstalling 'mkvtoolnix' (51.0.0).
Running uninstaller script...
Removing shim for 'mkvextract'.
Removing shim for 'mkvinfo'.
Removing shim for 'mkvmerge'.
Removing shim for 'mkvpropedit'.
Removing shim for 'mkvtoolnix-gui'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\MKVToolNix GUI.lnk
Unlinking ~\scoop\apps\mkvtoolnix\current
'mkvtoolnix' was uninstalled.
```

`mkvtoolnix-gui.ini` is copied to the relevant `persist` dir.

Thanks.

**Comment by Ash258** [comment]
Intentional.

Mkvtoolnix is using atomic saving, so on every save it remove the file (breaking the link) and then recreating it with new content
