### ISSUE TITLE
Hash issue for cpu-z

### ISSUE THREAD

**Issue by thatchrisblack** [lukesampson/scoop-extras#539]
#530 was closed and that hash is showing as the expected hash, but I'm getting a different hash when trying to install cpu-z

PS C:\Users\staked> scoop install cpu-z
Installing 'cpu-z' (1.80).
cpu-z_1.80-en.zip (2.5 MB) [==================================================================================] 100%
Checking hash of cpu-z_1.80-en.zip... Hash check failed for 'http://download.cpuid.com/cpu-z/cpu-z_1.80-en.zip'.
Expected:
    3c2fdb6f79cb2f1a2dac9ace906956b4b9f6f0ff6bb0d5f98ab15f335c0b73ad
Actual:
    f92fb1c1fa2c2d8dd581b77d28d8cb53538014eca1e426eb243a63a6fee6619e
PS C:\Users\staked>

**Comment by r15ch13** [comment]
Strange, they have already changed it [3 days ago](https://github.com/lukesampson/scoop-extras/commit/8b886556610531a8ac023ea347f39b2c9db80372). 😕 
Fixed 👍
