### ISSUE TITLE
msiafterburner requires Visual C++ 2008

### ISSUE THREAD

**Issue by aaronkjones** [lukesampson/scoop-extras#5403]
Without `vcredist2008` MSI Afterburner fails to start with error:

    This application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

After installing Visual C++ Redistributable 2008 via `scoop install vcredist2008` it launches.

**Comment by Ash258** [comment]
As specified in susggests

https://github.com/lukesampson/scoop-extras/blob/8a72acdabec68aa217cce0a5efb1272264bc0c25/bucket/msiafterburner.json#L14-L15
