### ISSUE TITLE
emacs@27.1: decompress error

### ISSUE THREAD

**Issue by bhalapatil** [lukesampson/scoop-extras#5542]
Hello,

I am facing the below issue while installing emacs. Any help would be highly appreciated.

Installing 'emacs' (27.1) [64bit]
Loading emacs-27.1-x86_64.zip from cache
Checking hash of emacs-27.1-x86_64.zip ... ok.
Extracting emacs-27.1-x86_64.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\brpatil\scoop\apps\emacs\27.1\emacs-27.1-x86_64.zip.
Log file:
  ~\scoop\apps\emacs\27.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=emacs%4027.1%3a+decompress+error[](url)

-------------------------
Content of the log

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 107543748 bytes (103 MiB)

Extracting archive: C:\Users\brpatil\scoop\apps\emacs\27.1\emacs-27.1-x86_64.zip
--
Path = C:\Users\brpatil\scoop\apps\emacs\27.1\emacs-27.1-x86_64.zip
Type = zip
Physical Size = 107543748

Sub items Errors: 17

Archives with Errors: 1

Sub items Errors: 17

Thanks,
Bhalachandra

**Comment by Ash258** [comment]
Your 7zip is broken

![image](https://user-images.githubusercontent.com/13260377/105571932-343d4a00-5d54-11eb-91f6-0e248ab5e825.png)
