### ISSUE TITLE
Zettlr Autoupdate Error

### ISSUE THREAD

**Issue by abhirupdutta0** [lukesampson/scoop-extras#5543]
The Zettlr manifest isn't able to autoupdate using checkver.ps1 because it fails to find the hash values.
[https://github.com/lukesampson/scoop-extras/blob/master/bucket/zettlr.json](url)
![Zettlr Autoupdate error](https://user-images.githubusercontent.com/31652124/105598454-418d1f80-5dba-11eb-9a7b-6c77ecd8c2f4.png)

**Comment by Ash258** [comment]
Duplicate of #2308

**Comment by abhirupdutta0** [comment]
@Ash258 I have the updated manifest and checkver.ps1 still fails to auto update and the manifest on the repo is outdated.
