### ISSUE TITLE
joplin@1.7.11: decompress error

### ISSUE THREAD

**Issue by scythk** [lukesampson/scoop-extras#5632]
ERROR Exit code was 2!
Failed to extract files from C:\Users\john\scoop\apps\joplin\1.7.11\$PLUGINSDIR\app-64.7z.
Log file:
  ~\scoop\apps\joplin\1.7.11\$PLUGINSDIR\7zip.log

========================================
7zip.log

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 82987354 bytes (80 MiB)

Extracting archive: C:\Users\john\scoop\apps\joplin\1.7.11\$PLUGINSDIR\app-64.7z
--
Path = C:\Users\john\scoop\apps\joplin\1.7.11\$PLUGINSDIR\app-64.7z
Type = 7z
Physical Size = 82987354
Headers Size = 2243
Method = LZMA2:26 LZMA:20 BCJ2
Solid = +
Blocks = 2

Sub items Errors: 4

Archives with Errors: 1

Sub items Errors: 4

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/107551069-171cce00-6bd2-11eb-9fa9-f60c5bfa572f.png)
