### ISSUE TITLE
[Request] Add VeraCrypt

### ISSUE THREAD

**Issue by devhawk** [lukesampson/scoop-extras#5659]
I'd open a PR, but I'm not sure how to build the right manifest for VeraCrypt. https://www.veracrypt.fr/en/Downloads.html includes a "Portable" version for windows, but the portable version is distributed as a self-extracting exe (more details: https://www.veracrypt.fr/code/VeraCrypt/plain/doc/html/Portable%20Mode.html)

**Comment by Ash258** [comment]
Duplicate of #2381
