### ISSUE TITLE
LibreOffice still can't be installed

### ISSUE THREAD

**Issue by SharakPL** [lukesampson/scoop-extras#5661]
All recent issues related have been closed by b6f4ca4 even though it didn't fix anything. It's still the same problem:

![obraz](https://user-images.githubusercontent.com/5007456/107578878-9b804880-6bf4-11eb-8db4-6265d1f8a3ae.png)

If it's so problematic (the same error showing up and being fixed again and again and again 😫 and now it even requires additional software like lessmsi), then allow installing Libreoffice differently. Maybe like Git does with their windows installation: simply downloads the installer and runs it. Let the user handle installation process. 

![obraz](https://user-images.githubusercontent.com/5007456/107579867-1007b700-6bf6-11eb-9a1d-a9ab965360c8.png)

After that you could simply uninstall LibreOffice from Scoop apps (installer only), just like it's already done with `vcredist` packages.

**Comment by Ash258** [comment]
As commented in the commit description it works for both msiexec and lessmsi.

![A](https://i.imgur.com/pWhNFei.png)

![b](https://i.imgur.com/76DRkas.png)

**Comment by SharakPL** [comment]
I've just shown you it DOESN'T WORK and other users confirm that

**Comment by equinox** [comment]
I'm seeing the same behaviour as @SharakPL and others reported (on the other issue linked in the OP).

<details>
<summary>Details</summary>

```
$ scoop install libreoffice-fresh
Installing 'libreoffice-fresh' (7.1.0.3) [64bit]
LibreOffice_7.1.0.3_Win_x64.msi (313.2 MB) [===========================================================================================================================================================] 100%
Checking hash of LibreOffice_7.1.0.3_Win_x64.msi ... ok.
Running pre-install script...
Exception: C:\Users\User\scoop\apps\scoop\current\lib\core.ps1:510
Line |
 510 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'LibreOffice'! (error 16)
```
</details>

**Comment by SharakPL** [comment]
@equinox @pensive-fuzz I've just installed this (v.7.1.2.2) with no problems, but with this command:

    scoop install -i libreoffice-fresh

> -i, --independent         Don't install dependencies automatically

I'm geussing this avoids using _lessmsi_
