### ISSUE TITLE
idea command points to wrong executable

### ISSUE THREAD

**Issue by dsbert** [lukesampson/scoop-extras#570]
After installing idea, running `idea` does nothing, as it points to `idea.exe`. I'm assuming this is crashing when I type it. Should be using `idea.bat` instead to set up the environment properly.

```
PS C:\Users\dan> scoop which idea
Not a scoop shim.
C:\Users\dan\scoop\apps\idea\current\bin\idea.exe

PS C:\Users\dan> scoop which idea.bat
Not a scoop shim.
C:\Users\dan\scoop\apps\idea\current\bin\idea.bat

PS C:\Users\dan> scoop which idea.cmd
Not a scoop shim.
C:\Users\dan\scoop\shims\idea.cmd
```

**Comment by r15ch13** [comment]
Restarting powershell works for me. Will add a note to the manifest.
