### ISSUE TITLE
gpu-z@2.37.0: Download failed

### ISSUE THREAD

**Issue by yuuki76** [lukesampson/scoop-extras#5741]
The remote server returned an error: (404) Not Found.

**Comment by x-magic** [comment]
Seems broken in a recent commit for new version: r15ch13@43fc53675e3f7bd6516e08697da0128d0d297529

For some reason the nl1 mirror is not in the list. Probably the vendor offline that server? 
![image](https://user-images.githubusercontent.com/3180639/108731742-f6b12400-7580-11eb-830e-b190826971d9.png)

Currently available mirrors: 
http://us2-dl.techpowerup.com/files/GPU-Z.2.37.0.exe
http://us4-dl.techpowerup.com/files/GPU-Z.2.37.0.exe
http://us5-dl.techpowerup.com/files/GPU-Z.2.37.0.exe
http://us6-dl.techpowerup.com/files/GPU-Z.2.37.0.exe
http://uk1-dl.techpowerup.com/files/GPU-Z.2.37.0.exe
http://de1-dl.techpowerup.com/files/GPU-Z.2.37.0.exe
