### ISSUE TITLE
cheat-engine@7.2-2020-11-04T09: download via aria2 failed

### ISSUE THREAD

**Issue by mo-san** [lukesampson/scoop-extras#5769]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/cheat-engine/cheat-engine/releases/download/7.2/CheatEngine72.exe
    referer=https://github.com/cheat-engine/cheat-engine/releases/download/7.2/
    dir=C:\Users\Me\Scoop\cache
    out=cheat-engine#7.2-2020-11-04T09#https_github.com_cheat-engine_cheat-engine_releases_download_7.2_CheatEngine72.exe

**Comment by MunsterPlop** [comment]
At this time, it seems the cheat-engine repo doesn't have a binary for the latest release.
