### ISSUE TITLE
[Request] Autoruns

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop-extras#5830]
https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns

> This utility, which has the most comprehensive knowledge of auto-starting locations of any startup monitor, shows you what programs are configured to run during system bootup or login, and when you start various built-in Windows applications like Internet Explorer, Explorer and media players. These programs and drivers include ones in your startup folder, Run, RunOnce, and other Registry keys. Autoruns reports Explorer shell extensions, toolbars, browser helper objects, Winlogon notifications, auto-start services, and much more. Autoruns goes way beyond other autostart utilities.

It's basically a .zip file with executables in it. I couldn't find a repo.

**Comment by NatoBoram** [comment]
Apparently there's a lot of discussions about SysInternals (#1859, #2227, #2614, ScoopInstaller/Main#273) and the consensus is that they're better off in another bucket. Sorry about that!

```powershell
scoop bucket add Sysinternals 'https://github.com/Ash258/Scoop-Sysinternals.git'
sudo scoop install -g autoruns
```

**Comment by rasa** [comment]
Autoruns and Autorunsc are available in the sysinternals package [here](https://github.com/lukesampson/scoop-extras/blob/a8043dc878c841d87cceb37617be7df16d2fcddd/bucket/sysinternals.json#L32).

**Comment by NatoBoram** [comment]
The issue with that hack is that no one wants to download, extract and install the whole SysInternals suite just for one tool they're probably going to uninstall in a few minutes. That package goes against a third of scoop Scoop's goals.

> ~~Path~~ Pollution from installing lots of programs
> Unexpected side-effects from installing and uninstalling programs

It's okay if the bucket's maintainers don't want SysInternal's tools, the choice is theirs, but hey shouldn't justify it with something so invalid.

**Comment by rasa** [comment]
Another goal is to keep each bucket under 1,000 packages, due to GitHub's display limit, and to distribute the maintenance of apps & buckets across multiple maintainers.
