### ISSUE TITLE
x64dbg@2021-03-19_16-57: Download failed

### ISSUE THREAD

**Issue by littleli** [lukesampson/scoop-extras#5878]
During the update I spotted out x64dbg got broken

```sh
~ $ scoop install x64dbg
Installing 'x64dbg' (2021-03-19_16-57) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2021-03-19_16-57.zip is not valid
```

I checked the manifest and `url` and `hash` are not updated properly from Github release page.
Also it seems that artifacts with previous version got deleted or something. I don't know exactly what went wrong.

New `hash` is `2d434a4f5b5eb3a680d5d5abd7771fa2a5472a5e65365a0ec2b752f6028d47ce` and `url` is `https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2021-03-20_10-33.zip`

**Comment by Ash258** [comment]
92f10235466dcac33866ae84044c4d6fedf4fd2a
