### ISSUE TITLE
Git-flow setup: Getopt dependency

### ISSUE THREAD

**Issue by tmagnusson** [lukesampson/scoop-extras#59]
the git-flow setup is missing a dependency, just typing git flow [command] gives the message flags:FATAL unable to determine getopt version. Now I know technically you can go install Cygwin and util-linux-ng, and get getopt that way, but with how close you are to a working workaround for Windows to NOT have to rely on cygwin and actually have options, I think its worth mentioning.
![2015-01-12 08_22_24-administrator_ windows powershell](https://cloud.githubusercontent.com/assets/10403802/5704159/46279d9a-9a34-11e4-9fbc-bc5b6678cbfb.png)

**Comment by deevus** [comment]
@tmagnusson This should be working. 

If you're still having problems try `scoop reset util-linux-ng`
