### ISSUE TITLE
nim installer fails when compiler absent

### ISSUE THREAD

**Issue by trurebel** [lukesampson/scoop-extras#5965]
scoop install nim
Installing 'gcc' (9.3.0-2) [64bit]
Loading mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz ... ok.
Loading mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz ... ok.
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid

**Comment by Ash258** [comment]
There is no nim manifest in Extras
