### ISSUE TITLE
dosbox-x@0.83.12: hash check failed

### ISSUE THREAD

**Issue by platykurticsg** [lukesampson/scoop-extras#6007]
Installing 'dosbox-x' (0.83.12) [64bit]
dosbox-x-vsbuild-win-20210401015807.zip (55.9 MB) [===========================================================] 100%
Checking hash of dosbox-x-vsbuild-win-20210401015807.zip ... ERROR Hash check failed!
App:         extras/dosbox-x
URL:         https://github.com/joncampbell123/dosbox-x/releases/download/dosbox-x-v0.83.12/dosbox-x-vsbuild-win-20210401015807.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    32dba23140b7493d4a5c2e76550f6085c477a8cdbf13441218a88ac3b1abeba1
Actual:      a4f67b5d86a8d1e7bb967d32c754af3d9dd8183b68d237a7e7de653973e25d86

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=dosbox-x%400.83.12%3a+hash+check+failed

This was after the recent hash update. Many thanks!

**Comment by Ash258** [comment]
4e69f757233646a8e7bb5fea0865d242186db0fa
