### ISSUE TITLE
copyq@4.0.0: Decompress Error

### ISSUE THREAD

**Issue by s-a-c** [lukesampson/scoop-extras#6035]
Could not find 'copyq-v4.0.0 in C:\LocalData\scoop\global\apps\copyq\4.0.0'! (error 16)
>>>
 ❯  scoop install --global copyq
Installing 'copyq' (4.0.0) [64bit] [extras]
WARN  By installing you accept following license: GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later.html)
Loading copyq-v4.0.0.zip from cache.
Checking hash of copyq-v4.0.0.zip ... ok.
Extracting copyq-v4.0.0.zip ... ERROR Could not find 'copyq-v4.0.0 in C:\LocalData\scoop\global\apps\copyq\4.0.0'! (error 16)

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=copyq%404.0.0%3a+Decompress+Error&body=Could+not+find+%27copyq-v4.0.0+in+C%3a%5cLocalData%5cscoop%5cglobal%5capps%5ccopyq%5c4.0.0%27!+(error+16)
 ❯
>>>

**Comment by Ash258** [comment]
489120933f10b9eb52d4fb9ab3e455094c0c4d6c
