### ISSUE TITLE
Windows Terminal crashes on startup 1.7.1033.0

### ISSUE THREAD

**Issue by 1hiking** [lukesampson/scoop-extras#6043]
microsoft/terminal#9821

Original issue:

After last update, when trying to open the Terminal it shows a white screen and then it shuts down... Am I the only one with this problem?

![image](https://user-images.githubusercontent.com/73438877/114897307-a0ce5f00-9e00-11eb-8344-ba0d4896de79.png)

**Comment by jadeker** [comment]
You're not the only one.  The crash is likely due to the major change in the new Windows Terminal integrated Settings interface.  I don't have any proof, but I highly suspect the significant inclusion of the new settings interface is the cause.

**Comment by igitur** [comment]
> You're not the only one. The crash is likely due to the major change in the new Windows Terminal integrated Settings interface. I don't have any proof, but I highly suspect the significant inclusion of the new settings interface is the cause.

Not it. Read the linked issue.

**Comment by weizhiwen** [comment]
Have you found a solution?

**Comment by Rockcookies** [comment]
How to fix it?

**Comment by 1hiking** [comment]
Looks like the current method as of right now is using the latest pre-release: https://github.com/microsoft/terminal/releases/tag/v1.8.1092.0

**Comment by Ash258** [comment]
02007b375120df56108920d6d79f5369067c14a3
