### ISSUE TITLE
pdf-xchange-editor@9.0.353.0: hash check failed

### ISSUE THREAD

**Issue by Priddles** [lukesampson/scoop-extras#6096]
**App:** extras/pdf-xchange-editor
**URL:** http://downloads.pdf-xchange.com/PDFXEdit9_Portable.zip
**First bytes:** `50 4B 03 04 14 00 00 00`
**Expected:** `12c34ef01579242ee1a3cfba79b54ace68e379cb52f77580b39b53e6429c1591`
**Actual:** `f7727831c162152c5dfdce529e09db9b1946ae6faffc947191b1aad8c72dcb55`

**Comment by Ash258** [comment]
ed71bec3827d73ddcf48ea03a1363924c6a3493a
