### ISSUE TITLE
KeepassXC persist not working

### ISSUE THREAD

**Issue by dsbert** [lukesampson/scoop-extras#614]
KeepassXC has `keepassxc.ini` set as a persisted file. However, when upgrading, the file is replaced with the new version and all settings are back to default.

**Comment by r15ch13** [comment]
From which version did you upgrade?
I upgraded just now from version 2.2.1 to 2.2.2 and it worked like it should.

**Comment by dsbert** [comment]
I upgraded the same version. The same thing happened the last time I upgraded, although I'm not sure when the persist was added in relation to the last release.

While attempting to recreate this issue, I've run into some new problems that may or may not be related.

I just tried uninstalling keepassxc and deleting the `persist/keepassxc` directory. After installing keepassxc again, I now see a directory under `persist` called `keepass.ini' with nothing in it, instead of the actual `keepassxc.ini` file. I also see a linked directory in the actual current `keepassxc` directory with the same name. It looks like keepassxc does not create the configuration file until after the first run. When I launch the program I see `error accessing config file`. After deleting `current\keepass.ini\` and launching the program again, the `keepass.ini` file is created.

So it looks like if the persisted file is not found at install time, scoop is actually creating a directory with the same name.

I'm using the latest version of scoop.

**Comment by r15ch13** [comment]
I hope this fixes the problem: https://github.com/lukesampson/scoop/commit/c15d8e2393112ed595c250bda04b9fc16b1b9970
Scoop now tries to detect if it's a file or a directory before just creating a new empty directory.

**Comment by dsbert** [comment]
I tried uninstall and installing again - this time I received the following message. This was with nothing in the persist directory.

```
Persisting keepassxc.ini
The system cannot find the file specified.
```

The second test I attempted was to uninstall, manually edit the current version to a lower number then install again. I received the same message as above. I then manually copied over `keepassxc.ini` to the current folder, updated the current version and ran `scoop update keepassxc`. This resulted in the same error again. The `persist/keepassxc` directory is still empty and the `keepassxc/current` directory does not contain `keepassxc.ini` although I can still see it in the previous version folder.

So it looks like your update prevented a bad file from being created. However, it did not correct the issue where files not created until first launch are not being persisted.

It looks like scoop runs the persist operation at install time but does not check again at update or uninstall time when the file is actually needed.

**Comment by r15ch13** [comment]
Do you mean you lowered the version by changing the directory name? If so, this will break the symlink to the `current` directory and scoop is unable to find the file.

There is no real way to downgrade a version.
But for you could try to replicate the update behavior like so:

- `scoop uninstall keepassxc`
- delete keepassxc.ini from perist directory
- `scoop install keepassxc@2.2.1`
- change the content of the ini file
- `scoop install keepassxc@2.2.2`
- validate the content of the ini file

This keepassxc installation can not be updated with `scoop update keepassxc`, so you have to reinstall it normally again.

The logic for persistence can be found in the [persist_data()](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L971) function.

**Comment by dsbert** [comment]
No,

I lowered the version by editing the `keepassxc.json` file in `scoop/buckets/extras` and doing a `scoop install`. Then I reverted the manifest back to the current version and did a `scoop update`.

**Comment by r15ch13** [comment]
The ini file is missing in the 2.2.2 release: https://github.com/keepassxreboot/keepassxc/issues/1134

**Comment by r15ch13** [comment]
It should now work as intended.
