### ISSUE TITLE
retroarch@1.9.2: hash check failed

### ISSUE THREAD

**Issue by AJigsawnHalo** [lukesampson/scoop-extras#6161]
Checking hash of RetroArch.7z ... ERROR Hash check failed!
App:         extras/retroarch
URL:         https://buildbot.libretro.com/stable/1.9.2/windows/x86_64/RetroArch.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    43295d3c71580a4bac1370cd19e5927a63577850348dab29d258b0ca36cbbfd2
Actual:      86e8a4777cbe95f93d881568f5d13e9ff3bb3038a82cf7fc88937eebfabcb421

**Comment by Ash258** [comment]
a503abe51d699e19f7f37c95f4322be44c6af311
