### ISSUE TITLE
paint.net@4.2.15: hash check failed

### ISSUE THREAD

**Issue by hitoribocchi** [lukesampson/scoop-extras#6185]
An issue with one of the programs are as shown:

`Installing 'paint.net' (4.2.15) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 0ec4f5|OK  |   458KiB/s|C:/Users/admin/scoop/cache/paint.net#4.2.15#https_www.dotpdn.com_files_paint.net.4.2.15.install.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of paint.net.4.2.15.install.zip ... ERROR Hash check failed!
App:         extras/paint.net
URL:         https://www.dotpdn.com/files/paint.net.4.2.15.install.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    7d1b3b9b7e4bbb226da91e1c635c5fb8c7388d1337a48095348a102482bb30f3
Actual:      fe70191873a1f3b26d01d35dee60a364a0a7da4e69ac70f7495ef8666c32e8e5`

**Comment by Ash258** [comment]
b06b62cc14129519bdf0a5d27a74b84c20c95e27
