### ISSUE TITLE
msiafterburner@4.6.3: hash check failed

### ISSUE THREAD

**Issue by EnKrypt** [lukesampson/scoop-extras#6224]
```
Installing 'msiafterburner' (4.6.3) [64bit]
MSIAfterburnerSetup.zip (51.7 MB) [================================================================================] 100%
Checking hash of MSIAfterburnerSetup.zip ... ERROR Hash check failed!
App:         extras/msiafterburner
URL:         https://download.msi.com/uti_exe/vga/MSIAfterburnerSetup.zip?__token__=exp=zzzz~acl=/*~zzzzzzzz#/dl.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    57af22b6a030c5872a324f12c06600dcd0805df4ae127de4a4baef5dbcbe8ed8
Actual:      e71a5b2dd4bf010c6742f8138ba3f6500082c46baf940ba950fe50213d9579e8
```

**Comment by thomasmoors** [comment]
It might have something to do with: https://screenrant.com/msi-afterburner-fake-website-malware-explained/

**Comment by EnKrypt** [comment]
@thomasmoors MSI is notorious for updating release artifacts after the release is done instead of making a new release. Check the issues page to see how many other times users had reported a hash check failure for afterburner,

While I'm sure the fake website problem might also be responsible, the download link is from https://download.msi.com so it is definitely a first party issue.

**Comment by RavenMacDaddy** [comment]
When correcting the hash in my own repo I got a decompress error; 

"ERROR Could not find '4.6.3 in C:\users\amand\Scoop\apps\msiafterburner\4.6.3'! (error 16)"
