### ISSUE TITLE
amazon-workspaces@3.1.7.2102: hash check failed

### ISSUE THREAD

**Issue by davidlday** [lukesampson/scoop-extras#6247]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'amazon-workspaces' (3.1.7.2102) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 4b10f6|OK  |   5.8MiB/s|C:/Users/dayd3/scoop/cache/amazon-workspaces#3.1.7.2102#https_d2td7dqidlhjx7.cloudfront.net_prod_global_windows_Amazon_WorkSpaces.msi
Download: Status Legend:
Download: (OK):download completed.
Checking hash of Amazon+WorkSpaces.msi ... ERROR Hash check failed!
App:         extras/amazon-workspaces
URL:         https://d2td7dqidlhjx7.cloudfront.net/prod/global/windows/Amazon+WorkSpaces.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    163fa99b95bf986a101743650c313e5afb895bbd019d12a0c5610c1032511b47
Actual:      864a53515eaf1cca72bfc9693bf954b67d9a2b39fd66f96327bf78ee7fe94a25

**Comment by Ash258** [comment]
b3bac9815e9f39b55cfe11180e18df9a79777f85
