### ISSUE TITLE
crow-translate@2.8.3: hash check failed

### ISSUE THREAD

**Issue by lihaokun** [lukesampson/scoop-extras#6277]
crow-translate: 2.8.2 -> 2.8.3
Updating one outdated app:
Updating 'crow-translate' (2.8.2 -> 2.8.3)
Downloading new version
crow-translate-2.8.3-win64.exe (21.8 MB) [====================================================================] 100%
Checking hash of crow-translate-2.8.3-win64.exe ... ERROR Hash check failed!
App:         extras/crow-translate
URL:         https://github.com/crow-translate/crow-translate/releases/download/2.8.3/crow-translate-2.8.3-win64.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    5372e530beef38d643ec6d5044446923dcd0139f00bd9241dce474af042a7bd1
Actual:      b24c79d4a81f17335364bcb701f0503438ae8390f1ed691faf3e7351309a8065

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=crow-translate%402.8.3%3a+hash+check+failed

**Comment by Ash258** [comment]
cc7d1a9d814512cf4f4eb7df4064c680f6a6c458
