### ISSUE TITLE
Update PowerToys

### ISSUE THREAD

**Issue by Sei-lus** [lukesampson/scoop-extras#6281]
PowerToys is at version 0.22 on the repo. Current version is at 0.37.2.
https://github.com/lukesampson/scoop-extras/blob/master/bucket/powertoys.json
https://github.com/microsoft/PowerToys/releases

**Comment by Ash258** [comment]
Duplicate of #5084

**Comment by Sei-lus** [comment]
I'm sorry for the duplicate. Was going to try and make the update myself, thanks for linking me to the other issue. Will look harder next time.
