### ISSUE TITLE
[Request] Add Joplin Portable

### ISSUE THREAD

**Issue by ClarkeCheng** [lukesampson/scoop-extras#6292]
[https://github.com/laurent22/joplin/releases](https://github.com/laurent22/joplin/releases)

The data of joplin can be persisted.

![image](https://user-images.githubusercontent.com/17330505/120415400-0dd88c80-c38e-11eb-968e-976b0bcb0abc.png)

**Comment by Ash258** [comment]
No they cannot. Electron portable mode does not work as expected and flood appdata on every run.
