### ISSUE TITLE
Hash incorrect for "slack".

### ISSUE THREAD

**Issue by mborman** [lukesampson/scoop-extras#630]
I tried to install slack using `scoop install slack` and got an error about hash check failing. I tried a couple older versions (2.8.1, 2.8.0). same issue.  I have installed other apps with no issue. I am on windows 10.

```
Checking hash of slack-2.8.2-full.nupkg... Hash check failed for 'https://downloads.slack-edge.com/releases_x64/slack-2.
8.2-full.nupkg#/dl.7z'.
Expected:
    3CC2F952D9D1EA6D7CA05B8CCEBA8918D5C81103
Actual:
    c85b1ba05158873de37fee38a61cc0fdd8b63af5
```

**Comment by r15ch13** [comment]
Fixed. They updated the package without changing the version.

**Comment by mborman** [comment]
Installed successfully! Thanks for the quick response!
