### ISSUE TITLE
honeyview@5.38: hash check failed

### ISSUE THREAD

**Issue by xlui** [lukesampson/scoop-extras#6307]
$ scoop install honeyview
Installing 'honeyview' (5.38) [64bit]
HONEYVIEW-SETUP.EXE (7.7 MB) [============================================================] 100%
Checking hash of HONEYVIEW-SETUP.EXE ... ERROR Hash check failed!
App:         extras/honeyview
URL:         https://dl.bandisoft.com/honeyview/HONEYVIEW-SETUP.EXE
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d664d1dabbc2137d44c2631b89d483d9cb5b34c6d3cf01a3e18978bf1b5820fc
Actual:      be25f887ab07f2a98a77977eb75d51a322add39dfca845b08431b75039d9e95e

**Comment by Ash258** [comment]
f81c16bc82d6ba2a52ec317687103571315f97f8
