### ISSUE TITLE
idea-ultimate@2021.1.2: decompress error

### ISSUE THREAD

**Issue by daggerok** [lukesampson/scoop-extras#6312]
Cannot install IntelliJ IDEA Ultimate
![image](https://user-images.githubusercontent.com/2445604/121039825-167bf900-c7ba-11eb-968b-1822d4fdfe12.png)

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/123133494-133a6b80-d450-11eb-843e-4d28f40676d0.png)
