### ISSUE TITLE
Slack won't load (Error: Can not find Squirrel)

### ISSUE THREAD

**Issue by NemoStein** [lukesampson/scoop-extras#632]
I've tried to install Slack yesterday but the hashes didn't match.
Today it was fixed and I've managed to install it, but it won't start.
After running `$ slack -l c:/` the `c:/browser.log` file revealed why: `Error: Can not find Squirrel`

In a quick search in the repo I found a commit (5d8c084: `Improve manifests of Electron Apps that are using the Squirrel installer`) that I think may be the culprit.

Any possible workaround?

**Comment by r15ch13** [comment]
Does this fix it? 😄

**Comment by NemoStein** [comment]
Like a charm! <3
