### ISSUE TITLE
[Request] Update Krita to 4.4.5

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [lukesampson/scoop-extras#6332]
https://krita.org/en/download/krita-desktop/

**Comment by KnotUntied** [comment]
Worth noting that Krita devs [won't release](https://krita.org/en/item/krita-4-4-5-released/) 32-bit builds starting on version 4.4.5.

**Comment by Ash258** [comment]
ae9b60f39033f0a7dd9e851a3120fe54f085c52d
