### ISSUE TITLE
wiztree@4.00: download via aria2 failed

### ISSUE THREAD

**Issue by sum-elier** [lukesampson/scoop-extras#6355]
scoop install wiztree

> WARN  Scoop uses 'aria2c' for multi-connection downloads.
> WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
> Installing 'wiztree' (4.00) [64bit]
> Starting download with aria2 ...
> Download: Download Results:                                                                                             zip
> Download: gid   |stat|avg speed  |path/URI
> Download: ======+====+===========+=======================================================
> Download: 80cbd7|ERR |       0B/s|C:/Users/User/scoop/cache/wiztree#4.00#https_wiztreefree.com_files_wiztree_4_00_portable.zip
> Download: Status Legend:
> Download: (ERR):error occurred.
> Download: aria2 will resume download if the transfer is restarted.
> Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
> 
> ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
> ERROR https://wiztreefree.com/files/wiztree_4_00_portable.zip
>     referer=https://wiztreefree.com/files/
>     dir=C:\Users\User\scoop\cache
>     out=wiztree#4.00#https_wiztreefree.com_files_wiztree_4_00_portable.zip
> 
> ERROR & 'C:\Users\User\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\User\scoop\cache\wiztree.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3036 --continue --summary-interval 0

**Comment by 0cool-f** [comment]
domain wiztreefree.com redirect to diskanalyzer.com, so I did this change in my wiztree.json and it worked as expected
