### ISSUE TITLE
Suggest support for JDK 9

### ISSUE THREAD

**Issue by winteryoung** [lukesampson/scoop-extras#636]
http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html

**Comment by brandon93s** [comment]
Really [oraclejdk](https://github.com/lukesampson/scoop-extras/blob/master/oraclejdk.json) should just be updated to point to 9.

JDK 8 could be added to [scoopinstaller/versions](https://github.com/scoopinstaller/versions) for continued support. [oraclejdk7](https://github.com/lukesampson/scoop-extras/blob/master/oraclejdk7.json) also belongs in the versions bucket.
