### ISSUE TITLE
[Request] add wsl-ssh-agent

### ISSUE THREAD

**Issue by 0cool-f** [lukesampson/scoop-extras#6427]
https://github.com/rupor-github/wsl-ssh-agent

Author archived the ssh-agent-wsl repo and suggests to use the new one, you might want to decide if it's better to keep both or replace the old one

**Comment by rasa** [comment]
It's available via:

```
scoop install https://raw.githubusercontent.com/hoilc/scoop-lemon/master/bucket/wsl-ssh-agent.json
```

or
```
scoop bucket add lemon https://github.com/hoilc/scoop-lemon
scoop install wsl-ssh-agent
```
