### ISSUE TITLE
Shortcuts for IDEA

### ISSUE THREAD

**Issue by gitolicious** [lukesampson/scoop-extras#645]
I wanted to add shortcuts for IntelliJ IDEA when I stumbled upon some problems with the [`idea.bat`](https://github.com/lukesampson/scoop-extras/edit/master/idea.json#L6) file currently executed: It opens up a Windows command line which shows Java debug info of IntelliJ and can't be closed without killing IntelliJ with it.

Two solutions are possible and I wanted to get your feedback on which one to implement.

**Option 1:** Use `idea.exe` instead of `idea.bat`
This approach directly calls the correct exe file circumventing all the other "magic" in the `.bat` file.

```
    "architecture": {
        "64bit": {
            "bin": "bin\\idea64.exe",
            "shortcuts": [
                [
                    "bin/idea64.exe",
                    "IntelliJ IDEA Ultimate"
                ]
            ]
        },
        "32bit": {
            "bin": "bin\\idea.exe",
            "shortcuts": [
                [
                    "bin/idea.exe",
                    "IntelliJ IDEA Ultimate"
                ]
            ]
        }
    },
```

**Option 2:** Using `javaw.exe` instead of `java.exe` in the `.bat` file
This opens a silent command line window which can be closed without killing IntelliJ.

```
    "shortcuts": [
        [
            "bin/idea.bat",
            "IntelliJ IDEA Ultimate"
        ]
    ],
    "post_install": "(Get-Content $dir\\bin\\idea.bat).replace('java.exe', 'javaw.exe') | Set-Content $dir\\bin\\idea.bat",
```

What do you think?

**Comment by yeikel** [comment]
Is there any reason to call the bat file instead of the original executable?
