### ISSUE TITLE
php72 (404) not found (releases vs archives folder)

### ISSUE THREAD

**Issue by rdsignr** [lukesampson/scoop-extras#6490]
CLI:
> mcd-rsc-master> scoop install php72
> Installing 'php72' (7.2.34) [64bit]
> The remote server returned an error: (404) Not Found.
> URL https://windows.php.net/downloads/releases/php-7.2.34-Win32-VC15-x64.zip is not valid

The correct URL is:
https://windows.php.net/downloads/releases/archives/php-7.2.34-Win32-VC15-x64.zip

**Comment by Ash258** [comment]
There is no php manifest in extras
