### ISSUE TITLE
Add meld app

### ISSUE THREAD

**Issue by hukacode** [lukesampson/scoop-extras#651]
Hello,
Can I suggest few software?
- https://www.clementine-player.org/
- https://doublecmd.sourceforge.io/
- https://www.cockos.com/licecap/

Regards,
Huka

**Comment by r15ch13** [comment]
Added with https://github.com/lukesampson/scoop-extras/compare/df939a78b14e702e897f05ff97d6c9597c83fc85...b71631084b0767ed14d2b32df4dc725b644850aa
As an alternative to LICEcap I can recommend [ScreenToGif](https://github.com/lukesampson/scoop-extras/blob/master/screentogif.json)

**Comment by hukacode** [comment]
Hello, @r15ch13 

Thank you for your supporting, I really appreciate it.

Best regards,
Huka

**Comment by hukacode** [comment]
Hi, @r15ch13 
Can I open this issue for new software?

https://gohugo.io/

Regards,
Huka.

**Comment by r15ch13** [comment]
Hugo is available in the main bucket. 😉

**Comment by hukacode** [comment]
I am sorry about that, I just searched in scoop-extras.
How about Meld (http://meldmerge.org/)? I tried to install so I am sure it is not existed.
Thank you for your efforts, it helped me a lot.

**Comment by equinox** [comment]
Meld got added in this [commit](https://github.com/lukesampson/scoop-extras/commit/092b74ea8c63739352d2e978156e8af28d0b564a#diff-9e16cf5ce421e558df60aaab465833bb).
