### ISSUE TITLE
Android SDK is not found

### ISSUE THREAD

**Issue by hukacode** [lukesampson/scoop-extras#653]
Hi,

When I installed Android Studio, I saw a suggest android-sdk, but it is not found.

Regards.
Huka

**Comment by r15ch13** [comment]
Probably means [`scoop install adb`](https://github.com/lukesampson/scoop/blob/master/bucket/adb.json)

**Comment by hukacode** [comment]
I think we should change suggestion.
Thanks, @r15ch13
