### ISSUE TITLE
Postman version does not come up when checking for updates "Scoop Update & Scoop Status"

### ISSUE THREAD

**Issue by desirockstar** [lukesampson/scoop-extras#6664]
Unable to see the latest postman update in the console.
![image](https://user-images.githubusercontent.com/2296964/130193202-306593de-db4f-42d4-a512-6914d4b0cb0b.png)

However, the latest version as per postman is 8.10.0
![image](https://user-images.githubusercontent.com/2296964/130193409-54143f47-fa9e-4475-9189-e3041ef00f32.png)

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop-extras/blob/f4681d748c2906ab85c09f5d7a10f3491439795f/bucket/postman.json#L2

![image](https://user-images.githubusercontent.com/13260377/131224315-9f61147c-1f24-493f-8ff4-c1d904961aec.png)
