### ISSUE TITLE
The download link of tomcat6 , zip and unzip is changed.

### ISSUE THREAD

**Issue by zhoujin7** [lukesampson/scoop-extras#667]
The download link of tomcat6 is changed.
https://www.apache.org --> https://archive.apache.org
zip and unizp cannot also install successfully.

**Comment by se35710** [comment]
PR [#42](https://github.com/scoopinstaller/versions/pull/42) in the [versions](https://github.com/scoopinstaller/versions) bucket would fix that. But Tomcat 6 is [EOL](https://tomcat.apache.org/tomcat-60-eol.html), so maybe it should be removed? @r15ch13

**Comment by rasa** [comment]
Fine with me, but isn't that the point of the versions repo, to keep old crap around? :)

**Comment by zhoujin7** [comment]
Maybe some old projects need old tomcat6.

**Comment by r15ch13** [comment]
Should be fixed now
