### ISSUE TITLE
Issues with the ThrottleStop manifest

### ISSUE THREAD

**Issue by bradenhilton** [lukesampson/scoop-extras#6746]
Currently, [ThrottleStop](https://github.com/lukesampson/scoop-extras/blob/master/bucket/throttlestop.json) fails to install because the URL in the manifest is not correct. I believe there are several problems with the manifest that I will attempt to outline below:
(I'd like to note that I don't intend to slight anyone who has worked on it)

- The current URL uses HTTP when it's possible to use HTTPS.
- The manifest currently installs beta versions with no indication that this is the case.
- The download is available from regional mirrors, which is reflected in the subdomain of the URL (nl2, de1 etc.), and the number suffixes appear to change regularly.
- The URLs are not available on the page, rather one is retrieved when clicking on the button for a region.
- The URL now appears to require some kind of randomized string (perhaps an authentication token).
- Perhaps most importantly - the current host, TechPowerUp, requests that users refrain from hotlinking to their downloads. You can verify this by going to https://nl2-dl.techpowerup.com/files/34qergaerg/1630442183/ThrottleStop_9.4.2.zip.

At a minimum, we should probably change hosts, though I believe TechPowerUp is the original source of ThrottleStop, so there is perhaps some risk involved when going to a 3rd party host.

I'm also of the opinion that the manifest should not install beta versions, though that opinion isn't a particularly strong one. I have some ideas about how to change the `checkver` string to achieve this but I'd like to see if any kind of consensus forms before I commit to something.

If we are unable to find a new host to download from, we should probably deprecate the manifest, as I don't see an easy way around the numbered mirror subdomains and authentication token requirement, not to mention the request to not hotlink.

**Comment by ItzLevvie** [comment]
https://github.com/lukesampson/scoop-extras/issues/6700#issuecomment-906515741

**Comment by bradenhilton** [comment]
@ItzLevvie Thank you for informing me about all of this!

An immediate temporary workaround I can see would be to change the UA to `winget/1.0`. Perhaps we could also change the mirror region to a US one, as they appear to outnumber the other regions, so we can reasonably expect a subdomain like `us2-dl` to be available most of the time.

I'm not sure if we'd be allowed to use a winget UA though.
