### ISSUE TITLE
throttlestop@9.4.2: download via aria2 failed

### ISSUE THREAD

**Issue by Kiskadee-dev** [lukesampson/scoop-extras#6756]
Installing 'throttlestop' (9.4.2) [64bit]
Starting download with aria2 ...
Download: 09/01 03:23:34 [ERROR] CUID#8 - Download aborted. URI=http://nl1-dl.techpowerup.com/files/ThrottleStop_9.4.2.zDownload: Download Results:                                                                                   _9.4.2.zipDownload: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: e3973e|ERR |       0B/s|C:/Users/Kiskadee/scoop/cache/throttlestop#9.4.2#http_nl1-dl.techpowerup.com_files_ThrottleStop_9.4.2.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR http://nl1-dl.techpowerup.com/files/ThrottleStop_9.4.2.zip
    referer=http://nl1-dl.techpowerup.com/files/
    dir=C:\Users\Kiskadee\scoop\cache
    out=throttlestop#9.4.2#http_nl1-dl.techpowerup.com_files_ThrottleStop_9.4.2.zip

ERROR & 'C:\Users\Kiskadee\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Kiskadee\scoop\cache\throttlestop.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8480 --continue --summary-interval 0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=throttlestop%409.4.2%3a+download+via+aria2+failed

The page requested returns error 404

**Comment by ItzLevvie** [comment]
https://github.com/lukesampson/scoop-extras/issues/6700#issuecomment-906515741

**Comment by W1zzardTPU** [comment]
This should be fixed now: https://github.com/lukesampson/scoop-extras/issues/6754
