### ISSUE TITLE
Sysinternals has a shortcut that doesnt exist

### ISSUE THREAD

**Issue by Zezypisa** [lukesampson/scoop-extras#6764]
In sysinternals.json, there is a shortcut trying to be created called "pagedfrg.exe", but the executable doesn't exist inside sysinternals, this should be removed

Lines are 142, 358-362, 452, 564-568

This is my first post here, hopefully I didnt do anything wrong (I couldn't make a PR, so this is my next best bug report)

**Comment by HUMORCE** [comment]
`pagedfrg.exe` are removed from the package after `August 18, 2021`, but the update date in [this page](https://docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite) has not changed.
