### ISSUE TITLE
Install ios-webkit-debug-proxy using scoop extras

### ISSUE THREAD

**Issue by ricardofreeman** [lukesampson/scoop-extras#678]
Hi, when I try to install ios-webkit-debug-proxy I'm getting this error

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Ricardo> scoop install ios-webkit-debug-proxy
Installing 'ios-webkit-debug-proxy' (1.8).
Linking ~\scoop\apps\ios-webkit-debug-proxy\current => ~\scoop\apps\ios-webkit-debug-proxy\1.8
Creating shim for 'ios_webkit_debug_proxy'.
Can't shim 'ios_webkit_debug_proxy.exe': File doesn't exist.
PS C:\Users\Ricardo>
```

I followed the instructions
```
scoop bucket add extras
scoop install ios-webkit-debug-proxy
```
The first command worked okay.

After running **scoop install ios-webkit-debug-proxy** I noticed that the folders 1.8 and current inside scoop\apps\ios-webkit-debug-proxy are empty.

Can anyone help me with this installation?

Thanks in advance.

**Comment by r15ch13** [comment]
Are you using 32bit Windows?
This error occurs if I try to install it like this `scoop install -a 32bit ios-webkit-debug-proxy`
It's declared as 64bit only [ios-webkit-debug-proxy.json](https://github.com/lukesampson/scoop-extras/blob/master/ios-webkit-debug-proxy.json)

**Comment by ricardofreeman** [comment]
Thank you so much for the hint @r15ch13 

I was running an instance of Powershell based on x86
![2017-12-07 4](https://user-images.githubusercontent.com/17456791/33732983-2812d956-db80-11e7-88a7-205e8d8cc446.png)

Running on a x64 instance it all went smoothly
![2017-12-07 5](https://user-images.githubusercontent.com/17456791/33733032-43d3ca1a-db80-11e7-8695-045002df1bfd.png)

Problem fixed.

Do you want me to leave it open to remind you to add the message?

**Comment by r15ch13** [comment]
Yes, leave it open. Will close it with a commit. 😁

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop/commit/a9c2d4c48625b1c24961cc232d6e1d1f653f467a
