### ISSUE TITLE
Terminus Update to version 1.0.157

### ISSUE THREAD

**Issue by DoveBoy** [lukesampson/scoop-extras#6852]
[Terminus](https://eugeny.github.io/terminus/) Update to version [1.0.157](https://github.com/lukesampson/scoop-extras/pull/6851).  [Terminus](https://github.com/Eugeny/tabby) has been significantly updated and the new program is now called [tabby](https://github.com/Eugeny/tabby/releases/tag/v1.0.157).

**Comment by Ash258** [comment]
91a573bfcf2a9d2aba9d5572294bdc1bbe2c8ec5
