### ISSUE TITLE
302 Error when trying to install OracleJDK

### ISSUE THREAD

**Issue by barchard** [lukesampson/scoop-extras#687]
Looks like there is a change in the URL for the OracleJDK:

```
scoop install oraclejdk
Updating Scoop...
Updating 'extras' bucket...
Scoop was updated successfully!
Installing 'oraclejdk' (8u151-b12).
The remote server returned an error: (302) Moved Temporarily.
URL http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-windows-x64.exe is not valid
```

Thanks

**Comment by barchard** [comment]
I'm not sure why the URL is returning a `302` because it looks like it *may* be valid:

http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-windows-x64.exe

I also notice that there is a `u152` build at:

http://download.oracle.com/otn-pub/java/jdk/8u152-b16/aa0333dd3019491ca4f6ddbe78cdb6d0/jdk-8u152-windows-x64.exe

**Comment by rasa** [comment]
We’re on 162 now.
