### ISSUE TITLE
Error trying to install zeal

### ISSUE THREAD

**Issue by xgid** [lukesampson/scoop-extras#693]
Hi there, 

First of all, congratulations for the scoop project! It's a great idea.

I've tried to install Zeal today and got this error:
```
PS C:\arrel> scoop install zeal
Installing 'zeal' (0.4.0).
Error en el servidor remoto: (403) Prohibido.
URL https://bintray.com/artifact/download/zealdocs/windows/zeal-portable-0.4.0-windows-x64.7z is not valid
```

After checking their [current download URL](https://zealdocs.org/download.html) (for the portable version), I've manually changed the `architecture.64bit.url` in my local `zeal.json` file to this one:
```
"https://github.com/zealdocs/zeal/releases/download/v0.4.0/zeal-portable-0.4.0-windows-x64.7z"
```

and tried again, and the download has started correctly.

Finally though, the installation has failed due to a timeout, but that's another unrelated issue (I wish):
```
PS C:\arrel> scoop install zeal
Installing 'zeal' (0.4.0).
zeal-portable-0.4.0-windows-x64.7z (19,2 MB) [==================================>                           ]  57%
No se puede escribir datos de en la conexión de transporte: Se ha forzado la interrupción de una conexión existente por el host remoto.
URL https://github.com/zealdocs/zeal/releases/download/v0.4.0/zeal-portable-0.4.0-windows-x64.7z is not valid
```

I don't know what should be set under `autoupdate` and so on,... just wanted you to know about this.

Is the error from bintray.com a temporal one? Should the URL for Zeal be changed to the github.com one?

**Comment by r15ch13** [comment]
Fixed. Since the Github URL seems to be the official one now, let's switch to that. 👍
