### ISSUE TITLE
HWiNFO@7.12-4580: hash check failed

### ISSUE THREAD

**Issue by drui** [lukesampson/scoop-extras#6963]
Updating 'HWiNFO' (7.10-4540 -> 7.12-4580)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 7270c0|OK  |    23KiB/s|C:/Users/psych/scoop/cache/HWiNFO#7.12-4580#https_www.hwinfo.com_files_hwi_712.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of hwi_712.zip ... ERROR Hash check failed!
App:         extras/HWiNFO
URL:         https://www.hwinfo.com/files/hwi_712.zip
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    1ca729f1ff7b8fc3c4b4063dc99aa4b79644ce9937ffd0a00dde68cb3f10b9bd
Actual:      6367824d9dfa0a50965ada6997c68419197c85ce6615d601b5ef52ad34c957fb

**Comment by Ash258** [comment]
https://github.com/lukesampson/scoop-extras/pull/6964#issuecomment-933777394
https://github.com/lukesampson/scoop-extras/pull/6964#issuecomment-933778005
