### ISSUE TITLE
logseq@0.4.3: Hash check failed

### ISSUE THREAD

**Issue by Paxxs** [lukesampson/scoop-extras#7005]
Hash check failed!
App:         extras/logseq
URL:         https://github.com/logseq/logseq/releases/download/0.4.3/logseq-win-x64-0.4.3.exe#/dl.7z
First bytes: 77 90 144 0 3 0 0 0
Expected:    41e174cf355ad093b7d03ac2e8a17177135fb8a09526d54448c9483d4536db46
Actual:      48790e1009661f92d7457a9431c611fc1b6475ab4379efe0c8956743ac83f6fc

**Comment by Ash258** [comment]
687f06dad1538cbb4da76430c53d018f121b46a5
