### ISSUE TITLE
Notepad++ session not persisted on update

### ISSUE THREAD

**Issue by NemoStein** [lukesampson/scoop-extras#736]
Updating Notepad++ doesn't "migrate" the session to the new version.
If you open/create a file in Notepad++, close and open it, the files should be there, but after updating the session is missing.
If you open the previous version instead of `current` symlink the session is there.

**Comment by r15ch13** [comment]
Is there a directory/file that's missing in the updated directory? Seems we forgot to add the file/dir to `persist` property.

**Comment by NemoStein** [comment]
I think I just found the problem.
The `backup` folder is persisted, but the `session.xml` file (which lists the persisted files) isn't.

**Comment by r15ch13** [comment]
Added the `session.xml` to the `persist` property. Should work the next time.

**Comment by NemoStein** [comment]
I think we have a regression on this issue.
Although the `backup` and `plugins` folders are persisted correctly, the `config.xml` and `session.xml` aren't.

**Comment by rasa** [comment]
Yes, they are:
https://github.com/lukesampson/scoop-extras/blob/62bc1ec46a079d6a6e959d37638df9b55d96bac3/notepadplusplus.json#L21-L23

**Comment by NemoStein** [comment]
No, they aren't:

![not-persisted](https://user-images.githubusercontent.com/2738812/42633520-2069c87c-85b7-11e8-91af-785f937f0c20.png)

**Comment by rasa** [comment]
You're right, sorry for saying otherwise:
```
Installing 'notepadplusplus' (7.5.7) [64bit]
Downloading https://notepad-plus-plus.org/repository/7.x/7.5.7/npp.7.5.7.bin.x64.7z (-1 B)...

Checking hash of npp.7.5.7.bin.x64.7z... ok.
Extracting... done.
Linking ~\scoop\apps\notepadplusplus\current => ~\scoop\apps\notepadplusplus\7.5.7
Creating shim for 'notepad++'.
Creating shortcut for Notepad++ (notepad++.exe)
Persisting backup
Persisting plugins
Persisting config.xml
The system cannot find the file specified.
Persisting session.xml
The system cannot find the file specified.
'notepadplusplus' (7.5.7) was installed successfully!

**Comment by NemoStein** [comment]
Interesting fix... The problem was that the files didn't exist originally (first install) so the links couldn't be created?
That would explain why the original fix worked for me (because I had the n++ installed before) but wouldn't work now (newly formatted HD).

I'll try it right now!
