### ISSUE TITLE
Slack hash check failed

### ISSUE THREAD

**Issue by andiskrauklis** [lukesampson/scoop-extras#738]
λ scoop install slack
Installing 'slack' (3.0.3) [64bit]
slack-3.0.3-full.nupkg (72,8 MB) [==================================================================================================================================================================================================] 100%
Checking hash of slack-3.0.3-full.nupkg... Hash check failed for 'https://downloads.slack-edge.com/releases_x64/slack-3.0.3-full.nupkg#/dl.7z'.
Expected:
    F8F65ADB935055D4E3D96A564B658163EB3F0504
Actual:
    697890614d0eb62e1bbcb5dd8c94887aa33a857c

**Comment by r15ch13** [comment]
Fixed 👍
