### ISSUE TITLE
Irregular Chromium/Chrome install...

### ISSUE THREAD

**Issue by Nefariis** [lukesampson/scoop-extras#759]
Hey I was continuing my Jenkins work (I submitted the ie11Webdriver) and I wanted to make a feature request for the Chromium/Chrome install. 

The install works fine but there is a subtle difference between installing it from scoop and using the regular installation executable. 

The scoop install doesn't install the application in the `C:\Program Files (x86)\Google\Chrome` folder like the executable does. It ended up putting it in `C:\Users\mcphzw1\AppData\Local\Microsoft\AppV\Client\Integration\13A6E3E6-6B56-4432-9933-2CA1F112248D\Root\VFS\ProgramFilesX86\Google\Chrome\`

Is there any way to add this to the installation json so Selenium can find chrome natively? 

I tried looking at firefox and a few other programs that I know need installation but Im not quite grasping the syntax.

Thank you for all your work,
- Zach

**Comment by yeikel** [comment]
I think this is issue is more related to selenium than this project

**Comment by Nefariis** [comment]
So I tracked down the issue - 

when you use `scoop install chromium` it installs both chromium and chrome.

The default base install directory for chrome is `C:\Program Files (x86)\Google\Chrome`

however scoop is installing chrome in this folder -
`C:\Users\mcphzw1\AppData\Local\Microsoft\AppV\Client\Integration\13A6E3E6-6B56-4432-9933-2CA1F112248D\Root\VFS\ProgramFilesX86\Google\Chrome\`

Instead of interpreting my root drive as `C:\`, scoop is interpreting my root drive as 
`C:\Users\mcphzw1\AppData\Local\Microsoft\AppV\Client\Integration\13A6E3E6-6B56-4432-9933-2CA1F112248D\Root\VFS\`

Both scoop and chrome want to install in `\Program Files (x86)\Google\Chrome` - the only difference is how they are interpreting the root folder. 

So the question is - can anything be done in the json installer to install chrome in the proper folder.

Thank you

**Comment by r15ch13** [comment]
Installing chromium via scoop can't result in a `C:\Program Files (x86)\Google\Chrome` directory or something in `%localappdata%` because it just uncompresses a zip file. See [chromium.json](https://github.com/lukesampson/scoop-extras/blob/master/chromium.json) 😕
It also doesn't install chromium and chrome. 😕

**Comment by Nefariis** [comment]
Actually - I think I take this back. 

I've been installing/uninstalling both chrome and chromium so many times on so many different computers, its hard to tell what's coming from where. This might be a VM issue.

**Comment by Nefariis** [comment]
yeah - you're right.

I'm just seeing remnants of previous installs on the virtual machines.

This can be closed - I will just add a symlink in the batch file that is setting up the VM's
