### ISSUE TITLE
Anaconda3 and miniconda3 fails to install properly

### ISSUE THREAD

**Issue by PranavSK** [lukesampson/scoop-extras#765]
The command `scoop install anaconda3` fails with an error.

    > scoop install anaconda3
    Installing 'anaconda3' (5.0.1) [64bit]
    Anaconda3-5.0.1-Windows-x86_64.exe (514.8 MB) [=======================] 100%
    Checking hash of Anaconda3-5.0.1-Windows-x86_64.exe... ok.
    Running pre-install script...
    Installing Anaconda 3. This can take up to 30 minutes on an HDD.
    Running installer... Exit code was -1073741819.
    Installation aborted. You might need to run 'scoop uninstall anaconda3' before trying again.
The command `scoop install miniconda3` shows this,

    > scoop install miniconda3
    Installing 'miniconda3' (4.3.31) [64bit]
    Miniconda3-4.3.31-Windows-x86_64.exe (55.8 MB) [======================] 100%
    Checking hash of Miniconda3-4.3.31-Windows-x86_64.exe... ok.
    Running installer... done.
    Linking ~\scoop\apps\miniconda3\current => ~\scoop\apps\miniconda3\4.3.31
    Creating shim for 'python'.
    Can't shim 'python.exe': File doesn't exist.

After checking the scoop folder i.e, `%USERPROFILE%\scoop\apps\miniconda3` it was empty. The files had been installed to `%USERPROFILE%\Miniconda3`. Not sure why this is happening. A similar folder for anaconda3 was also found but this did not have all the files (probably because the installer failed).

I have a windows 10 machine, scoop installed a few other apps fine (7zip, gimp, IrfanView etc).

**Comment by PranavSK** [comment]
A quick look at the .json files and the [docs](https://conda.io/docs/user-guide/install/windows.html) suggests the quotes around $dir may be the issue. 

> `/D=<installation path>`—Destination installation path. Must be the last argument. Do not wrap in quotation marks. Required if you use `/S`.

**Comment by r15ch13** [comment]
Removed the quotes. Does it work now?

**Comment by PranavSK** [comment]
Unfortunately no, the same issue persists.

**Comment by r15ch13** [comment]
Did you run `scoop update`?

**Comment by PranavSK** [comment]
Oh Nope, I didn't. Will check and report.

**Comment by PranavSK** [comment]
Yes, it has installed properly thank you.
