### ISSUE TITLE
Weird behavior on some package such as sourcetree

### ISSUE THREAD

**Issue by fboyer** [lukesampson/scoop-extras#773]
See the following logs:

```
PS K:\> scoop install sourcetree -g
Installing 'sourcetree' (2.4.8) [64bit]
Loading SourceTree-2.4.8-full.nupkg from cache
Checking hash of SourceTree-2.4.8-full.nupkg... ok.
Extracting... done.
Linking C:\ProgramData\scoop\apps\sourcetree\current => C:\ProgramData\scoop\apps\sourcetree\2.4.8
Creating shim for 'sourcetree'.
Creating shortcut for Atlassian SourceTree (sourcetree.exe)
Running post-install script...
Type:
New-Item : Cannot process argument because the value of argument "type" is not valid. Change the value of the "type"
argument and run the operation again.
At line:1 char:1
+ New-Item "$dir\lib\Update.exe" -force | out-null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-Item], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.NewItemCommand

'sourcetree' (2.4.8) was installed successfully!
```
```
PS K:\> scoop uninstall sourcetree -g
Uninstalling 'sourcetree' (2.4.8).
Removing shim for 'sourcetree'.
Removing shortcut C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Atlassian SourceTree.lnk
Unlinking C:\ProgramData\scoop\apps\sourcetree\current
'sourcetree' was uninstalled.
```
```
PS K:\> scoop install 7zip -g
WARN  '7zip' (18.01) is already installed.
Use 'scoop update 7zip --global' to install a new version.
PS K:\> scoop install sourcetree -g
Installing 'sourcetree' (2.4.8) [64bit]
Loading SourceTree-2.4.8-full.nupkg from cache
Checking hash of SourceTree-2.4.8-full.nupkg... ok.
Extracting... done.
Linking C:\ProgramData\scoop\apps\sourcetree\current => C:\ProgramData\scoop\apps\sourcetree\2.4.8
Creating shim for 'sourcetree'.
Creating shortcut for Atlassian SourceTree (sourcetree.exe)
Running post-install script...
Type: File
'sourcetree' (2.4.8) was installed successfully!
PS K:\>
```

When I install sourcetree it asks for some user input about a "Type" during/after the post-install script. 

The first time I did not enter anything and the install failed. Searching a bit for the New-Item function, I figured I should enter "File" instead and that did the trick. 

Could you help me understand if this required user input is the expected behavior?

Thank you!

PS: 
- Isn't it weird that scoop, whether an install is successful or not, tells you that "xxx was installed successfully"? It requires the end user to manually keep track of apps that are actually successfully installed vs those that weren't and fiddle around with uninstall/reinstall to fix scoop internal state. 
- scoop also removes previous versions and shims before it confirms that the new version has been successfully deployed so you often end up with some missing tools because scoop preemptively removed them during a failed install. Maybe the removal of previous version/shims should be done after the new version has been installed instead of before? With scoop approach of having different versions deployed in different folders and using shims, that should not be an issue. Thoughts?

PPS: Maybe my PS should be logged as another issue. Let me know!

**Comment by r15ch13** [comment]
The `ItemType` is set to `file` now. 

Yeah, the process after an unsuccessful installation is a bit cumbersome. Rolling back to the last installed version after a failed update would also be a good idea. The error handling is not that great at the moment.

**Comment by rasa** [comment]
Seems this has been addressed. Please let us know if this appear reappears. Thanks.
