### ISSUE TITLE
nirlauncher installation issues [manifest outdated]

### ISSUE THREAD

**Issue by brandon93s** [lukesampson/scoop-extras#780]
It looks like the download link has changed for `nirlauncher`. Along with that, the zip now appears to be password protected. The version has not changed: 

> This zip file is password-protected. The password for extracting the files is nirsoft9876$

Website:      https://launcher.nirsoft.net/downloads/index.html
Manifest:     https://github.com/lukesampson/scoop-extras/blob/master/nirlauncher.json

cc: @rasa

**Comment by r15ch13** [comment]
Fixed

**Comment by rasa** [comment]
Thanks, I missed this.
