### ISSUE TITLE
[Request] Add Launchy

### ISSUE THREAD

**Issue by daniel-liuzzi** [lukesampson/scoop-extras#781]
Yes, I know… at this point [Launchy](https://launchy.net/) can be considered Jurassic, but it's still so incredibly useful I just can't use Windows without it. So I tried creating a manifest by following the instructions on the Wiki and also looking at other manifests here in scoop-extras and came up with this:

**launchy.json**
```json
{
    "version": "2.5",
    "url": "https://www.launchy.net/downloads/win/Launchy2.5.exe#/dl.7z"
}
```

But then when I try `scoop install launchy`, everything blows up:

```
Installing '7zip' (18.01) [64bit]
7z1801-x64.msi (1.6 MB) [===========================================================================] 100%
Checking hash of 7z1801-x64.msi... ok.
Extracting... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\18.01
Creating shim for '7z'.
Creating shortcut for 7zip (7zFM.exe)
'7zip' (18.01) was installed successfully!
Installing 'launchy' (2.5) [64bit]
Launchy2.5.exe (4.3 MB) [===========================================================================] 100%
WARN  Warning: No hash in manifest. SHA256 is:
    4271e8f3969dc11259bc2791ce89b6eb73cb36eb663872792c0c4dfa87fa1916
Extracting... ERROR: C:\Users\Daniel\scoop\apps\launchy\2.5\dl.7z
C:\Users\Daniel\scoop\apps\launchy\2.5\dl.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Is not archive
Exit code was 2.
```

If I try to open Launchy2.5.exe manually with 7-Zip, it barks at me with a _Can not open file 'Launchy2.5.exe' as archive_ error. I'm assuming this must be due to Launchy using some obscure installer with an archive format 7-Zip can't understand (its [BUILD.txt](https://sourceforge.net/p/launchy/code/HEAD/tree/tags/2.5/BUILD.txt) file does mention "QT 4.6 or greater" among the requirements, so there's that.) 

Is there any trick to make this work? TIA!

**Comment by stkb** [comment]
Launchy uses an InnoSetup installer. You need the (undocumented) `innosetup` flag in the manifest, and then you don't need the `#dl.7z` part either. So:

```
{
    "version": "2.5",
    "url": "https://www.launchy.net/downloads/win/Launchy2.5.exe",
    "innosetup": true
}
```

However while I tested this and it installed, the program had an error when I tried to run it. I didn't investigate further but that will need doing.

**Comment by stkb** [comment]
Ok it runs fine when you launch it from the `2.5` folder but not from `current` ... it doesn't like the symlink. Not sure how to go about fixing that.

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Runtime Error!

Program: C:\Users\Steve\Apps\launchy\current\Launchy.exe



This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by r15ch13** [comment]
Does not solve the Problem, but did you consider using one of these?
[keypirinha.json](https://github.com/lukesampson/scoop-extras/blob/master/keypirinha.json) (http://keypirinha.com)
[wox.json](https://github.com/lukesampson/scoop-extras/blob/master/wox.json) (http://www.getwox.com/)
[hain.json](https://github.com/lukesampson/scoop-extras/blob/master/hain.json) (http://hainproject.github.io/hain/)

**Comment by dliuzzi** [comment]
@stkb So close… yet so far! :( That's life. Anyway, thanks a lot for taking the time to give this a shot. Appreciate it!

@r15ch13 I've tried Hain and Wox in the past. Neither felt like a true replacement. I remember Hein feeling rather sluggish; Wox seemed okay, but it uses space instead of tab for sub-commands, with no way to customize that. I don't think I've tried Keypirinha. I'll give it a try, it might just work. Thanks for the suggestions!

**Comment by asmgf** [comment]
@dliuzzi, have you tried this fork of Lanchy: https://openningia.github.io/Launchy
I tried installing it with scoop (#806) and it worked fine for me (haven't tested it thoroughly though).

**Comment by dliuzzi** [comment]
Hey @asmgf I wasn't aware of this fork, but I'll be sure to check it out. Thanks for the heads up!

**Comment by gitolicious** [comment]
Launchy has been added a while ago: [launchy.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/launchy.json)
I think this can be closed.
