### ISSUE TITLE
vim/gvim confusion on what should be in scoop-extras

### ISSUE THREAD

**Issue by SimplyKnownAsG** [lukesampson/scoop-extras#786]
Scoop contains scoop/buckets/vim.json which contains a `gvim.exe`. The `scoop-extras` bucket contains `gvim.json` (from a different source). Are these both OK? If so, why? `scoop/buckets/vim.json` could be renamed to `scoop/buckets/vim-win-installer` and `scoop-extras` could be renamed to `vim-ftp.json`.

Additionally, within `scoop-extras/gvim.json` contains a post_install that would create `.vimrc`, it should instead create `_vimrc`.

**Comment by LexSong** [comment]
I don't think we should keep the `gvim.json` in extras bucket. The FTP version doesn't get updated frequently and is quite outdated.

**Comment by rasa** [comment]
Agreed. @r15ch13 ?
