### ISSUE TITLE
wsltty: wrong license tag

### ISSUE THREAD

**Issue by mintty** [lukesampson/scoop-extras#788]
Please fix the license tag in wsltty.json (it's GPL).
Licensing is a delicate issue, I suggest to attach license tags more carefully.

**Comment by r15ch13** [comment]
Fixed

**Comment by mintty** [comment]
Thanks; actually, could you please update the hash as well. I replaced the installer with a freshly built one yesterday, trying to resolve mintty/wsltty#94. (I know, hidden replacement isn't quite appreciated but this was a special situation, with the virus reports...)

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop-extras/commit/e7656a9d05f4e738224d7cd7fcf7e5853576aeeb 👍
