### ISSUE TITLE
qbittorrent 4.0.4 x64 hash check failed - downloads web page instead of setup.exe

### ISSUE THREAD

**Issue by Arnavion** [lukesampson/scoop-extras#789]
```
Installing 'qbittorrent' (4.0.4) [64bit]
qbittorrent_4.0.4_x64_setup.exe (240.9 KB) [==================================================================================================================================================] 100%
Checking hash of qbittorrent_4.0.4_x64_setup.exe... Hash check failed for 'https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.0.4/qbittorrent_4.0.4_x64_setup.exe#/dl.7z'.
Expected:
    27420dec31a55b6e4745be7db1e12feb82a5a18b8186a7f0fc339fc97a7b612f
Actual:
    d68ff402d0856231401581e42053ee16055eba55b0b983b9a37646caa929ee46
```

Ref https://github.com/lukesampson/scoop-extras/commit/b883c6e823b342ec6d81e2afb0f71eac54f00a76

It's downloading a 240 KiB webpage instead of the EXE. May be a problem for other sourceforge-hosted downloads as well.

---

Workaround:

1. Manually download the setup.exe using the same URL.
1. `$(Get-FileHash -Algorithm SHA256 ./qbittorrent_4.0.4_x64_setup.exe | % Hash) -eq '27420dec31a55b6e4745be7db1e12feb82a5a18b8186a7f0fc339fc97a7b612f'`
1. `mv ./qbittorrent_4.0.4_x64_setup.exe '~/scoop/cache/qbittorrent#4.0.4#https_sourceforge.net_projects_qbittorrent_files_qbittorrent-win32_qbittorrent-4.0.4_qbittorrent_4.0.4_x64_setup.exe_dl.7z'`
1. `scoop update qbittorrent`

**Comment by stkb** [comment]
A fix is in #794. I tried a couple of other sourceforge-hosted downloads and they were fine, so it doesn't seem to be for everything.

**Comment by r15ch13** [comment]
Sourceforge has moved to another Datacenter in last couple days, that might be the problem here. (See https://twitter.com/sfnet_ops)

**Comment by Arnavion** [comment]
(Just to be clear, the web page it was downloading was not the "offline" web page but the "Your download will start shortly" web page you get in a browser.)
