### ISSUE TITLE
Write - incorrect hash.

### ISSUE THREAD

**Issue by gbursson** [lukesampson/scoop-extras#811]
write.json has incorrect hash.
download link errors out at 404. 

from PS:
Checking hash of Write!-v1.0b8.4.exe... Hash check failed for 'http://dl.wri.tt/releases/Write!-v1.0b8.4.exe'.
Expected:
    7b73af32816cb0a426e57bcf89a971d96c8bec7f0f040c6f595b3e75c9197fff
Actual:
    e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

**Comment by r15ch13** [comment]
Moved it to my Keybase public directory
