### ISSUE TITLE
winscp link broken

### ISSUE THREAD

**Issue by marknelissen** [lukesampson/scoop-extras#827]
When installing winscp 5.13, I get an error 500 on the used url.
`URL https://sourceforge.net/projects/winscp/files/WinSCP/5.13/WinSCP-5.13-Portable.zip is not valid`

**Comment by r15ch13** [comment]
This seems to be a SourceForge problem.
Even https://sourceforge.net/projects/winscp/files/ doesn't work.

**Comment by marknelissen** [comment]
Is the version on sourceforge a repackaged version? Why not use the one directly from winscp.net?

I can download it from there, but don't know how to manually inject it into scoop, as a temporary workaround.

**Comment by marknelissen** [comment]
Situation is back to normal.
