### ISSUE TITLE
camunda-modeler - Hash check failed

### ISSUE THREAD

**Issue by andiskrauklis** [lukesampson/scoop-extras#885]
λ scoop install camunda-modeler
Installing 'camunda-modeler' (1.13.0) [64bit]
camunda-modeler-1.13.0-win32-x64.zip (58,2 MB) [==========================================================] 100%
Checking hash of camunda-modeler-1.13.0-win32-x64.zip... Hash check failed for 'https://camunda.org/release/camunda-modeler/1.13.0/camunda-modeler-1.13.0-win32-x64.zip'.
Expected:
    7326673decb7452be058c32df496f7c48d553e0df3bcc59735ed2e54c2ed452c
Actual:
    1e78e18176282b0b1229e9b31ea2f7b0555f6724415d8d314c7b771e438591e1

**Comment by r15ch13** [comment]
Fixed
