### ISSUE TITLE
Persist Settings for ConEmu

### ISSUE THREAD

**Issue by boxfoot** [lukesampson/scoop-extras#888]
Would you be willing to update the conemu manifest to persist settings across updates?  I think it would mean setting the following:

* `persist`: `ConEmu.xml`
* Tell ConEmu to load the xml file from the persist folder.  This I'm less sure about - looks like it by default will load from the same folder as the exe.  There's a command line switch `-LoadCfgFile file`.  Can scoop make it always use this?

Thanks!

**Comment by r15ch13** [comment]
Fixed. You could move the `ConEmu.xml` to `%APPDATA%\ConEmu.xml`. See: https://conemu.github.io/en/SettingsFast.html

**Comment by boxfoot** [comment]
Thanks!
