### ISSUE TITLE
Rambox install failed

### ISSUE THREAD

**Issue by andiskrauklis** [lukesampson/scoop-extras#910]
λ scoop install rambox
Installing 'rambox' (0.5.17) [64bit]
Loading Rambox-0.5.17-x64-win.zip from cache
Checking hash of Rambox-0.5.17-x64-win.zip... ok.
Extracting... Error moving directory:

**Comment by rasa** [comment]
Fixed in https://github.com/lukesampson/scoop-extras/commit/dcd70ea41eb072889faf37a3492a3a17ba0e12a6
