### ISSUE TITLE
302 on trying to install jdk

### ISSUE THREAD

**Issue by fsb2278** [lukesampson/scoop-extras#913]
$ scoop install oraclejdk
Installing 'oraclejdk' (10.0.1-10) [64bit]
The remote server returned an error: (302) Moved Temporarily.
URL http://download.oracle.com/otn-pub/java/jdk/10.0.1+10/fb4372174a714e6b8c52526dc134031e/jdk-10.0.1_windows-x64_bin.exe#/dl.7z is not valid

 $ scoop install oraclejdk-lts
Installing 'oraclejdk-lts' (8u172-b11) [64bit]
The remote server returned an error: (302) Moved Temporarily.
URL http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-windows-x64.exe#/dl.exe is not valid

**Comment by BjoernPetersen** [comment]
I think this belongs [here](https://github.com/se35710/scoop-java).

**Comment by se35710** [comment]
@rasa I think there might be a redirection issue in some scenarios. I have not been able to reproduce the errors, and I cannot find any errors in the manifests. One user experiencing the problem [had upgraded from Windows 8 to Windows 10](https://github.com/se35710/scoop-java/issues/7#issuecomment-396468731) but scoop was installed in Windows 8. Not sure how that would be relevant…

Maybe we can reopen this issue to allow tracking of the specifics and find a solution for those effected?
