### ISSUE TITLE
add kdenlive

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [lukesampson/scoop-extras#919]
https://kdenlive.org/en/

**Comment by pedzed** [comment]
Download page: https://kdenlive.org/en/download/
Releases: https://files.kde.org/kdenlive/release/
Current latest version: https://files.kde.org/kdenlive/release/Kdenlive-18.04.1d-w64.zip

(Offtopic: Also check out [Davinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve/) for video editing.)
