### ISSUE TITLE
Add Intellij Datagrip

### ISSUE THREAD

**Issue by lllvantis** [lukesampson/scoop-extras#923]
I'm trying to install Datagrip but it seems not found.

**Comment by r15ch13** [comment]
I recommend installing [jetbrains-toolbox](https://github.com/lukesampson/scoop/blob/master/bucket/jetbrains-toolbox.json)

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/commit/2867ab0ac37f8d7012c1e2611c2f5556d3caedba
