### ISSUE TITLE
accesschk is a duplicate

### ISSUE THREAD

**Issue by gbursson** [lukesampson/scoop-extras#935]
Access check is found in sysinternals suite, also available in the bucket.
Maybe this should be removed or does it warrant a standalone install?

[accesschk.json](https://github.com/lukesampson/scoop-extras/blob/master/accesschk.json)
[sysinternals.json](https://github.com/lukesampson/scoop-extras/blob/master/sysinternals.json)

**Comment by rasa** [comment]
+1 to delete all the sysinternals apps: accesschk, autoruns, procexp, pstools, strings, and whois
