### ISSUE TITLE
Update gitextensions.json autoupdate for new naming convention

### ISSUE THREAD

**Issue by devhawk** [lukesampson/scoop-extras#964]
It looks like GitExtensions has changed their naming convention from GitExtensions-$version-Mono.zip to GitExtensions-$version-portable.zip as of version 2.51.02 (https://github.com/gitextensions/gitextensions/releases/tag/v2.51.02). So autoupdate isn't picking it up as I think it's supposed to

**Comment by devhawk** [comment]
FYI, I ran scoop update and scoop status. I saw 9421d1b in the list of updates to the extras bucket, but when I ran scoop status I did *NOT* see an available update to git extensions

**Comment by rasa** [comment]
Updated to 2.51.02 in https://github.com/lukesampson/scoop-extras/commit/f27b61c8a50c5fab62a28240aa3f3544c9a94d31

**Comment by devhawk** [comment]
Thanks! scoop update of git extensions worked for me after this change.
