### ISSUE TITLE
Slack 3.2.0 hash check failed

### ISSUE THREAD

**Issue by mserge** [lukesampson/scoop-extras#967]
> slack-3.2.0-full.nupkg (73,4 MB) [============================================================================] 100%
> Checking hash of slack-3.2.0-full.nupkg... Hash check failed for 'https://downloads.slack-edge.com/releases_x64/slack-3.2.0-full.nupkg#/dl.7z'.
> Expected:
>     A9CF27F7A5222CF52DE1C5F26A665635C5BD1A09
> Actual:
>     cc5b4698b02fdd5c6b74fc1803716a4e8fcad15d
> 

Currently have to shift back to 3.1.1

**Comment by r15ch13** [comment]
Fixed
