### ISSUE TITLE
Add go-jira

### ISSUE THREAD

**Issue by LexSong** [lukesampson/scoop-extras#968]
https://github.com/Netflix-Skunkworks/go-jira

`go-jira` is a simple command line client for Atlassian's Jira.

I have created a manifest file in my personal bucket:
https://github.com/LexSong/my-bucket/blob/master/go-jira.json

If people are interested we could merge this into the extra bucket.

**Comment by r15ch13** [comment]
Added with https://github.com/lukesampson/scoop/commit/a2348b858ca52f741ff7f04b86a53094d7a54f8c
